### ISSUE TITLE
Unhandled exception: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#1031]
on this site:
http://127.0.0.1:43110/1GnTA9B5JDSsAEk63LyDCQkbmoiFDSVxad
im getting this error on reload db console command : 

Site:1GnTA9..Vxad Importing data...
Unhandled exception: 'list' object has no attribute 'keys'
Traceback (most recent call last):
  File "zeronet.py", line 19, in main
    main.start()
  File "/vagrant/src/main.py", line 492, in start
    actions.call(config.action, action_kwargs)
  File "/vagrant/src/main.py", line 155, in call
    func(**kwargs)
  File "/vagrant/src/main.py", line 280, in dbRebuild
    site.storage.rebuildDb()
  File "/vagrant/src/Site/SiteStorage.py", line 124, in rebuildDb
    db_files = list(self.getDbFiles())
  File "plugins/MergerSite/MergerSitePlugin.py", line 214, in getDbFiles
    for item in super(SiteStoragePlugin, self).getDbFiles():
  File "/vagrant/src/Site/SiteStorage.py", line 87, in getDbFiles
    for file_relative_path in content.get("files", {}).keys() + content.get("files_optional", {}).keys():
AttributeError: 'list' object has no attribute 'keys'

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed in https://github.com/HelloZeroNet/ZeroNet/commit/2aba9cc3c28a879d2ae9f5aa8d956b40be3bff7a
