### ISSUE TITLE
Unhandled exception: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#1035]
on this site:
http://127.0.0.1:43110/1NYDdJ2JqMHsuD1Seau87BfGKbwEPEft8r/

when trying to rebuild from sidebar -
Internal error: AttributeError: 'list' object has no attribute 'keys'

when trying to rebuild from console -
 Unhandled exception: 'list' object has no attribute 'keys'
Traceback (most recent call last):
  File "zeronet.py", line 19, in main
    main.start()
  File "/vagrant/src/main.py", line 492, in start
    actions.call(config.action, action_kwargs)
  File "/vagrant/src/main.py", line 155, in call
    func(**kwargs)
  File "/vagrant/src/main.py", line 280, in dbRebuild
    site.storage.rebuildDb()
  File "/vagrant/src/Site/SiteStorage.py", line 124, in rebuildDb
    db_files = list(self.getDbFiles())
  File "plugins/MergerSite/MergerSitePlugin.py", line 238, in getDbFiles
    for file_relative_path in content.get("files", {}).keys() + content.get("files_optional", {}).keys():
AttributeError: 'list' object has no attribute 'keys'

and this error shows up on the debug.log -
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/vagrant/src/Worker/Worker.py", line 70, in downloader
    site.storage.write(task["inner_path"], buff)
  File "/vagrant/src/Site/SiteStorage.py", line 191, in write
    self.onUpdated(inner_path)
  File "plugins/MergerSite/MergerSitePlugin.py", line 251, in onUpdated
    super(SiteStoragePlugin, self).onUpdated(inner_path, file)
  File "/vagrant/src/Site/SiteStorage.py", line 241, in onUpdated
    self.openDb()
  File "/vagrant/src/Site/SiteStorage.py", line 47, in openDb
    self.rebuildDb()
  File "/vagrant/src/Site/SiteStorage.py", line 117, in rebuildDb
    self.db.checkTables()
  File "/vagrant/src/Db/Db.py", line 212, in checkTables
    table_settings["indexes"], version=table_settings["schema_changed"]
  File "/vagrant/src/Db/DbCursor.py", line 109, in needTable
    self.createIndexes(table, indexes)
  File "/vagrant/src/Db/DbCursor.py", line 99, in createIndexes
    self.execute(index)
  File "/vagrant/src/Db/DbCursor.py", line 53, in execute
    res = self.cursor.execute(query)
sqlite3.OperationalError: table user has no column named user_date_created

its mentions "table user has no column named user_date_created" but there is not table named user, its named USERS and there is no mention of a column "user date created" anywhere i looked, so i dont understand why it gives me this error.

this is after updating zeronet

**Comment by HelloZeroNet** [comment]
Try stop zeronet, delete data/content.db, then start again

**Comment by imachug** [comment]
@dnelband @HelloZeroNet I think this is outdated. Could you close this issue please?
