### ISSUE TITLE
SiteManager Deleting orphan site from content.db // Unhandled exception: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by grinapo** [HelloZeroNet/ZeroNet#1040]
[19:33:13] - Version: 0.5.6 r2109, Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 

This is problematic since zeronet cannot start:

[19:29:07] SiteManager Deleting orphan site from content.db: ***********
[19:29:07] - Unhandled exception: FOREIGN KEY constraint failed
Traceback (most recent call last):
  File "/var/tmp/work/zeronet/ZeroBundle/ZeroNet/zeronet.py", line 18, in main
    main.start()
  File "/var/tmp/work/zeronet/ZeroBundle/ZeroNet/src/main.py", line 476, in start
    actions.call(config.action, action_kwargs)
  File "/var/tmp/work/zeronet/ZeroBundle/ZeroNet/src/main.py", line 151, in call
    func(**kwargs)
  File "/var/tmp/work/zeronet/ZeroBundle/ZeroNet/src/main.py", line 161, in main
    ui_server = UiServer()
  File "/var/tmp/work/zeronet/ZeroBundle/ZeroNet/src/Ui/UiServer.py", line 73, in __init__
    self.sites = SiteManager.site_manager.list()
  File "/var/tmp/work/zeronet/ZeroBundle/ZeroNet/src/Site/SiteManager.py", line 155, in list
    self.load()
  File "plugins/Zeroname/SiteManagerPlugin.py", line 20, in load
    super(SiteManagerPlugin, self).load(*args, **kwargs)
  File "plugins/MergerSite/MergerSitePlugin.py", line 338, in load
    super(SiteManagerPlugin, self).load(*args, **kwags)
  File "/var/tmp/work/zeronet/ZeroBundle/ZeroNet/src/Site/SiteManager.py", line 63, in load
    content_db.execute("DELETE FROM site WHERE ?", {"address": address})
  File "/var/tmp/work/zeronet/ZeroBundle/ZeroNet/src/Db/Db.py", line 80, in execute
    return self.cur.execute(query, params)
  File "/var/tmp/work/zeronet/ZeroBundle/ZeroNet/src/Db/DbCursor.py", line 49, in execute
    res = self.cursor.execute(query, params)
IntegrityError: FOREIGN KEY constraint failed

I will probably figure out which sqlite it wanted to delete from _[ZeroNet/data/content.db]_,  but not obvious from the message either, as well as the solution (I have deleted the records manually, no foreign constraints complained).

**Comment by antilibrary** [comment]
I'm getting the same error when trying to post to my ZeroMe:

```
[21:14:21] Site:1MeFqF..q7nH Signing: data/users/1KN1Au7SRmeTmffcxxoyPABDpvqmq7i
MbN/data.json
[21:14:21] Site:1RedkC..uFdL data/users/1KN1Au7SRmeTmffcxxoyPABDpvqmq7iMbN/conte
nt.json parse error: IntegrityError: foreign key constraint failed in ContentMan
ager.py line 222 > ContentDbDict.py line 61 > ContentDbPlugin.py line 203 > Cont
entDb.py line 97 > Db.py line 87 > DbCursor.py line 80 > DbCursor.py line 49
[21:14:21] Site:1RedkC..uFdL Opening site data directory: data/1RedkCkVaXuVXrqCM
poXQS29bwaqsuFdL/data/users/1KN1Au7SRmeTmffcxxoyPABDpvqmq7iMbN/...
```

**Comment by HelloZeroNet** [comment]
Please try stop zeronet, delete data/content.db file, then start again (it will take some minute to regenerate the file)

**Comment by Plasmmer** [comment]
Isn't good people needing to do it.
Please, can you fix it?

**Comment by HelloZeroNet** [comment]
I tried to reproduce it, but I have no idea how "IntegrityError: FOREIGN KEY constraint failed" can happen on `DELETE` command as we have `ON DELETE CASCADE` on all foreign key definion.

**Comment by grinapo** [comment]
@HelloZeroNet the message may be misleading since, as I mentioned, I have manually just did the exact same delete which succeeded. As a wild guess is it possible that something is locking a table or tuple which would be required to be written by the cascade delete?

**Comment by grinapo** [comment]
(or circular reference like mentioned in https://stackoverflow.com/questions/15443913/sqlite3-foreign-key-constraint-failed )

**Comment by HelloZeroNet** [comment]
It can be problematic if you edited it without enabling the foreign key function by `PRAGMA foreign_keys = ON;`
I made this error non-fatal https://github.com/HelloZeroNet/ZeroNet/commit/ac230219eed41102b8442288a9f945f937e3bd44 and also fixed a bug that caused malfunction in the cleanup process.  (it did not worked well if it had more than one site to cleanup)https://github.com/HelloZeroNet/ZeroNet/commit/c96dce3d0b4c4fec11accc1fb0e6b3b7823abf4b

**Comment by grinapo** [comment]
Okay, I have actually saved the old db, it seems, so tried with pragma. Indeed fails with FK viola. Seems that you have a CASCADE on content, but not vice versa, so when deleting from 'site' which is being referred by 'content' (or files or else) then the content/else FK stops removing the site referenced.

If you intended to have a cascade on table site then it have failed to propagate throughout upgrades.

```
CREATE TABLE site (site_id INTEGER  PRIMARY KEY ASC NOT NULL UNIQUE,address TEXT NOT NULL);

CREATE TABLE content (content_id INTEGER PRIMARY KEY UNIQUE NOT NULL,site_id INTEGER REFERENCES site (site_id) ON DELETE CASCADE,inner_path TEXT,size INTEGER,size_files INTEGER,size_files_optional INTEGER,modified INTEGER);

CREATE TABLE file_optional (file_id INTEGER PRIMARY KEY UNIQUE NOT NULL,site_id INTEGER REFERENCES site (site_id) ON DELETE CASCADE,inner_path TEXT,hash_id INTEGER,size INTEGER,peer INTEGER DEFAULT 0,uploaded INTEGER DEFAULT 0,is_downloaded INTEGER DEFAULT 0,is_pinned INTEGER DEFAULT 0,time_added INTEGER DEFAULT 0,time_downloaded INTEGER DEFAULT 0,time_accessed INTEGER DEFAULT 0);

```

**Comment by imachug** [comment]
@HelloZeroNet Was this resolved? Can this issue be closed?

**Comment by HelloZeroNet** [comment]
Hopefully it won't happen with the new db sync mode that was implemented in the py3 client
