### ISSUE TITLE
what's this

### ISSUE THREAD

**Issue by mercurydarkork** [HelloZeroNet/ZeroNet#1047]
- Unhandled exception
None
Traceback (most recent call last):
  File "gevent/hub.pyo", line 857, in switch
  File "/Users/lihaoxuan/Downloads/ZeroNet-mac-dist/ZeroNet.app/Contents/Resources/boot.py", line 137, in signalHandler
    raise ExitCommand()
__main__.ExitCommand
- Unhandled exception
None
Traceback (most recent call last):
  File "/Users/lihaoxuan/Downloads/ZeroNet-mac-dist/ZeroNet.app/Contents/Resources/__boot__.py", line 81, in <module>
    _run()
  File "/Users/lihaoxuan/Downloads/ZeroNet-mac-dist/ZeroNet.app/Contents/Resources/__boot__.py", line 66, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/lihaoxuan/Downloads/ZeroNet-mac-dist/ZeroNet.app/Contents/Resources/boot.py", line 179, in <module>
    gui()
  File "/Users/lihaoxuan/Downloads/ZeroNet-mac-dist/ZeroNet.app/Contents/Resources/boot.py", line 106, in gui
    time.sleep(0.1)
  File "gevent/hub.pyo", line 169, in sleep
  File "gevent/hub.pyo", line 651, in wait
  File "gevent/hub.pyo", line 899, in get
  File "gevent/hub.pyo", line 630, in switch
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x103c1b2d0 select pending=0 ref=0>)
2017-07-25 12:01:54.928 ZeroNet[8806:247298] ZeroNet Error
2017-07-25 12:01:54.928 ZeroNet[8806:247298] ZeroNet Error

**Comment by Plasmmer** [comment]
@shortcutme

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in latest version. (you have to download ZeroNet.app again from zeronet.io homepage)
You may need to define the data directory manually as by default it creates it right next to ZeroNet.app. Example.: `MacOS zeronet$ ./ZeroNet --data_dir "/Users/zeronet/Library/Application Support/ZeroNet/data" siteCreate`
