### ISSUE TITLE
Batch FileDone event to avoid websocket flood

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#11]
```
Error catched (<type 'exceptions.AssertionError'>, AssertionError("This event is already used by another greenl
et: (<ErrorhookedGreenlet at 0x2a8f958: <bound method Worker.downloader of <Worker.Worker.Worker instance at 0x
2c03f38>>>, timeout('timed out',))",), <traceback object at 0x2abbcb0>)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/gevent/greenlet.py", line 390, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/sumo/p-private/dev1/bin-zeronet/src/Worker/Worker.py", line 47, in downloader
    self.manager.doneTask(task)
  File "/home/sumo/p-private/dev1/bin-zeronet/src/Worker/WorkerManager.py", line 128, in doneTask
    self.site.onFileDone(task["inner_path"])
  File "/home/sumo/p-private/dev1/bin-zeronet/src/util/Event.py", line 8, in __call__
    f(*args, **kwargs)
  File "/home/sumo/p-private/dev1/bin-zeronet/src/Site/Site.py", line 275, in <lambda>
    self.onFileDone.append(lambda inner_path: self.fileDone(inner_path))
  File "/home/sumo/p-private/dev1/bin-zeronet/src/Site/Site.py", line 307, in fileDone
    self.updateWebsocket(file_done=inner_path)
  File "/home/sumo/p-private/dev1/bin-zeronet/src/Site/Site.py", line 286, in updateWebsocket
    ws.event("siteChanged", self, param)
  File "/home/sumo/p-private/dev1/bin-zeronet/src/Ui/UiWebsocket.py", line 50, in event
    self.cmd("setSiteInfo", site_info)
  File "/home/sumo/p-private/dev1/bin-zeronet/src/Ui/UiWebsocket.py", line 60, in cmd
    self.send({"cmd": cmd, "params": params}, cb)
  File "/home/sumo/p-private/dev1/bin-zeronet/src/Ui/UiWebsocket.py", line 67, in send
    self.ws.send(json.dumps(message))
  File "/home/sumo/p-private/dev1/bin-zeronet/src/lib/geventwebsocket/websocket.py", line 345, in send
    self.send_frame(message, opcode)
  File "/home/sumo/p-private/dev1/bin-zeronet/src/lib/geventwebsocket/websocket.py", line 331, in send_frame
    self.raw_write(header + message)
  File "/usr/lib/pymodules/python2.7/gevent/socket.py", line 504, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/usr/lib/pymodules/python2.7/gevent/socket.py", line 484, in send
    wait_write(sock.fileno(), timeout=timeout, event=self._write_event)
  File "/usr/lib/pymodules/python2.7/gevent/socket.py", line 188, in wait_write
    assert event.arg is None, 'This event is already used by another greenlet: %r' % (event.arg, )
AssertionError: This event is already used by another greenlet: (<ErrorhookedGreenlet at 0x2a8f958: <bound method Worker.downloader of <Worker.Worker.Worker instance at 0x2c03f38>>>, timeout('timed out',))
```

**Comment by HelloZeroNet** [comment]
+ queue for websocket messages

**Comment by shakna-israel** [comment]
Would async managing this be able to help? Or is it because the greenlets are trying to attach to the same socket?

**Comment by HelloZeroNet** [comment]
It happened when i ran the zeronet on remote machine (around ~40ms away) and downloaded a site with many small files.
The ZeroNet pushes pushes an event over websocket after every file download, and maybe the last event message was still not finished when the next came.
I think it could be fixed like this:
```
def send(message):
 self.message_queue.append(message)
 if not self.sending:
    self.sending = True
    while self.message_queue:
      self.socket.send(self.message_queue.pop(0))
    self.sending = False
```
Maybe there is a better solution with gevent, but i like pure-python solutions, its easier to understand whats really happening.
Btw I optimized the Websocket to much smaller event messages, maybe its not an issue anymore, im going to test it later.

**Comment by ymski** [comment]
The gevent queue is as understandable as a straight python implemented queue and it seems easy to use.

http://www.gevent.org/gevent.queue.html

one example they use at the bottom:

```
def worker():
    while True:
        item = q.get()
        try:
            do_work(item)
        finally:
            q.task_done()

q = JoinableQueue()
for i in range(num_worker_threads):
     gevent.spawn(worker)

for item in source():
    q.put(item)

q.join()  # block until all tasks are done
```

**Comment by HelloZeroNet** [comment]
I think this model will not work in this case, because we dont want to send messages in parallel and we dont want to wait until the message is sent, so no reason to pop a greenlet for every message

**Comment by HelloZeroNet** [comment]
ran into this problem again, so i fixed it: https://github.com/HelloZeroNet/ZeroNet/blob/e8368a8da1478ec370a129e96aa89e9fb638b9ad/src/Ui/UiWebsocket.py#L71
