### ISSUE TITLE
cant create a site in LinuxOS64bit ZeroNet.py siteCreate

### ISSUE THREAD

**Issue by shitface666** [HelloZeroNet/ZeroNet#1104]
./zeronet.py siteCreate

- Starting ZeroNet...
ERROR:root:Unhandled exception: No module named gevent
Traceback (most recent call last):
  File "./zeronet.py", line 18, in main
    import main
  File "/home/myfilepath/", line 9, in <module>
    import gevent
ImportError: No module named gevent
Traceback (most recent call last):
  File "./zeronet.py", line 91, in <module>
    main()
  File "./zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'

what i did was
su
1.chmod +x zeronet.py
2.chmod +x main.py

i run ZeroNet.sh in root when i first try it

**Comment by mkg20001** [comment]
You need to install gevent first. See the [project page](../) for more details

**Comment by JazzMaster** [comment]
theres a few packages we need to warn people about...it works.
