### ISSUE TITLE
IOError: cannot watch more than 1024 sockets

### ISSUE THREAD

**Issue by cxgreat2014** [HelloZeroNet/ZeroNet#1136]
```
[14:07:23] - Unhandled exception
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
[14:07:23] - Unhandled exception
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
[14:07:24] - Unhandled exception
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
[14:07:29] - Unhandled exception
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
[14:07:32] - Unhandled exception
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "plugins\AnnounceZero\AnnounceZeroPlugin.py", line 49, in announceTracker
    tracker_protocol, tracker_address, fileserver_port, add_types, my_peer_id, mode
  File "D:\ZeroBundle\ZeroNet\src\Site\Site.py", line 823, in announceTracker
    tracker = UdpTrackerClient(ip, int(port))
  File "D:\ZeroBundle\ZeroNet\src\lib\subtl\subtl.py", line 43, in __init__
    self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "plugins\AnnounceZero\AnnounceZeroPlugin.py", line 49, in announceTracker
    tracker_protocol, tracker_address, fileserver_port, add_types, my_peer_id, mode
  File "D:\ZeroBundle\ZeroNet\src\Site\Site.py", line 823, in announceTracker
    tracker = UdpTrackerClient(ip, int(port))
  File "D:\ZeroBundle\ZeroNet\src\lib\subtl\subtl.py", line 43, in __init__
    self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\_socket2.py", line 122, in __init__
    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
```
I can't visit http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D to surf zeronet, what should I do?

**Comment by AnthyG** [comment]
I'm also experiencing this error.
It just happens, after some time, restarting the client helps, though, only for limited time until I have to repeat the process.

**Comment by cxgreat2014** [comment]
Yes, restart ZeroNet helps, but after some time again..

**Comment by HelloZeroNet** [comment]
How many http://127.0.0.1:43110/Stats shows to you? (eg.: `Connections (69, total made: 360)`)

**Comment by cxgreat2014** [comment]
@HelloZeroNet  ScreenShot:
![image](https://user-images.githubusercontent.com/15062548/31423083-f655a218-ae84-11e7-883a-58d8a6cb3e06.png)

**Comment by HelloZeroNet** [comment]
Hmm that's weird
How much site you have in your client? 
How much time does it takes until it gets filled?
Have you modified any settings of your client?

**Comment by badounan** [comment]
I'm sorry, I'm afraid that is one of many hard coded limitations of gevent and libev on windows.

**Comment by cxgreat2014** [comment]
Catch again.

196 site, haven't modified setting.

debug.log.zip(base64):
[debug.log.zip](https://github.com/HelloZeroNet/ZeroNet/files/1516330/debug.log.zip)

**Comment by slrslr** [comment]
> afraid that is one of many hard coded limitations of gevent and libev on windows
[it seems](https://github.com/gevent/gevent/issues/854#issuecomment-244650637) like that

Connections (997, total made: 10819)
Is it possible make Zeronet limit the connections ZeroHello (i assume it is main connections hog in this case) is producing so it do not affect regular browsing behavior? I mean ZeroHello on WIndows should leave reasonable amount of sockets available out of 1024 limit so it do not affect regular browsing (example 5 zites loading at a time)? https://www.reddit.com/r/learnpython/comments/3ml5zo/grequestsgevent_io_limit_help/

I am not a programmer, so i am asking You programmers. Thank you

**Comment by HelloZeroNet** [comment]
I have added a modification in Rev3229 that [should keep the connections under 512](https://github.com/HelloZeroNet/ZeroNet/commit/4afb6b3d9c1edb954dd74c4155a7ed8790ab82be) (by default) and it should [stop keeping open connections](https://github.com/HelloZeroNet/ZeroNet/commit/d44677e46f83d436012524498d2219128cc5067c) for sites that not modified in the last 7 days.
Please update and see if it's working better.

**Comment by slrslr** [comment]
@HelloZeroNet my status after ~7 hours of running zeronet:
Connections (517, total made: 8072)
I am "connected to" (visited and not deleted) roughly 600 zites.
it seems like You solved it, because for last around 7 hours i seen no "[Connection with UiServer Websocket was lost](https://github.com/HelloZeroNet/ZeroNet/issues/1249)" and have no issue browsing zeronet.

**Comment by slrslr** [comment]
Just now i found zites are not loading in TorBrowser, it resulted in default browser error: The connection was reset.
At http://127.0.0.1:43110/Stats i seen: Connections (1034, total made: 34205)
If i can supply any other specific details, let me know which/where. Thank you

**Comment by HelloZeroNet** [comment]
Can you please send the log to tamas@zeronet.io ?

**Comment by HelloZeroNet** [comment]
@slrslr Thanks for the log I was able to spot and fix the [problem](https://github.com/HelloZeroNet/ZeroNet/commit/97d1d0d63b719777b0dabb47781dc1b4adce0504) in Rev3233 that broke the cleanup method.

Please update and see if it's works now.

**Comment by slrslr** [comment]
Hello, i am following our communication and reporting that after update and
after runing zeronet around one hour maybe i again see connection
issue Connection
with *UiServer Websocket* was lost.
So i quit zeronet and attaching the log. If you want i report the issue
different way so you can better read it, please let me know. I am on
Windows 10 64bit

2018-01-30 14:36 GMT+01:00 ZeroNet <notifications@github.com>:

**Comment by slrslr** [comment]
@HelloZeroNet Thanks, issue reappeared probably, so i sent you my log via yours mentioned e-mail.

**Comment by HelloZeroNet** [comment]
Thanks, I have added a new update to fix connection error with unknown characters: https://github.com/HelloZeroNet/ZeroNet/commit/6fb9c6ef05aa7578bd0529c4022657612bcaf9c8
Please update to Rev3234 and let me know if the problem still exists.

**Comment by slrslr** [comment]
I am happy to report i have seen no connections issue since your fix on my Windows.

**Comment by HelloZeroNet** [comment]
Nice to hear, and how many active connections do you have after this fix?

**Comment by slrslr** [comment]
I think that yesterday i was seeing 150 when i was idle, then after more active surfing i think i seen something like 250.

**Comment by blurHY** [comment]
Maybe this should be reopen

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme

**Comment by blurHY** [comment]
#1663
