### ISSUE TITLE
Unable to start after update to newest version

### ISSUE THREAD

**Issue by saber28** [HelloZeroNet/ZeroNet#1139]
- Starting ZeroNet...
[06:55:05] - OpenSSL loaded, version: 0100020CF
[06:55:05] - Unhandled exception: argument --autodownload_bigfile_size_limit: conflicting option string(s): --autodownload_bigfile_size_limit
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/root/zeronet/src/main.py", line 108, in <module>
    config.loadPlugins()
  File "/root/zeronet/src/Config.py", line 379, in loadPlugins
    ConfigPlugin(self)
  File "/root/zeronet/src/Config.py", line 374, in __init__
    self.createArguments()
  File "plugins/Zeroname/UiRequestPlugin.py", line 30, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "plugins/UiPassword/UiPasswordPlugin.py", line 115, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "plugins/OptionalManager/OptionalManagerPlugin.py", line 136, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "plugins/Bigfile/BigfilePlugin.py", line 680, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "plugins/BigFile/BigfilePlugin.py", line 678, in createArguments
    group.add_argument('--autodownload_bigfile_size_limit', help='Also download bigfiles until this limit if help distribute option is checked', default=1, metavar="MB", type=int)
  File "/usr/lib/python2.7/argparse.py", line 1308, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
ArgumentError: argument --autodownload_bigfile_size_limit: conflicting option string(s): --autodownload_bigfile_size_limit

**Comment by HelloZeroNet** [comment]
There was a mistake with directory casing. I suspect there is two `plugin/Bigfile` directory for you with different casing. Please delete the BigFile one and keep the Bigfile directory
