### ISSUE TITLE
No zeronet.conf available

### ISSUE THREAD

**Issue by matthiasbeyer** [HelloZeroNet/ZeroNet#1192]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0
  * Operating system: NixOS

### Step 2: Describe the problem:

Trying to package zeronet, but cannot start as there is no `zeronet.conf` and there is also no template on how such a file should look like

#### Observed Results:

  * zeronet fails to start:

```
- Starting ZeroNet...
ERROR:root:Unhandled exception: [Errno 30] Read-only file system: 'log'
Traceback (most recent call last):
  File "/nix/store/3p5qvhnblipf23v4326cg9kg0pph459r-zeronet-0.6.0/bin/.zeronet.py-wrapped", line 19, in main
    import main
  File "/nix/store/3p5qvhnblipf23v4326cg9kg0pph459r-zeronet-0.6.0/bin/src/main.py", line 32, in <module>
    os.mkdir(config.log_dir)
OSError: [Errno 30] Read-only file system: 'log'
Traceback (most recent call last):
  File "/nix/store/3p5qvhnblipf23v4326cg9kg0pph459r-zeronet-0.6.0/bin/.zeronet.py-wrapped", line 92, in <module>
    main()
  File "/nix/store/3p5qvhnblipf23v4326cg9kg0pph459r-zeronet-0.6.0/bin/.zeronet.py-wrapped", line 65, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
IOError: [Errno 2] No such file or directory: 'log/error.log'
```

#### Expected Results:

  * zeronet should start

**Comment by HelloZeroNet** [comment]
example `zeronet.conf`:
```
[global]
data_dir = my-data-dir
log_dir = my-log-dir
ui_restrict =
 1.2.3.4
 2.3.4.5
```
You can list the possible configuration options with `zeronet.py --help`

**Comment by matthiasbeyer** [comment]
No, I cannot. I tried, but it failed because there was no config available.

**Comment by HelloZeroNet** [comment]
by default it tries to load the config from the working dir. You can override this with `--config_file "/etc/zeronet.conf"` startup argument

**Comment by matthiasbeyer** [comment]
Sure, but I still have no idea how such a file should look like and the `--help` argument does not work as long as there is no config available... do you get my point?

No config -> no --help -> No Config.

Why don't you provide an example configuration file in the repository?

**Comment by HelloZeroNet** [comment]
I gave you an example in comment https://github.com/HelloZeroNet/ZeroNet/issues/1192#issuecomment-346219984
I will consider adding .conf file by default
