### ISSUE TITLE
Latest update fails to run on Mac

### ISSUE THREAD

**Issue by April93** [HelloZeroNet/ZeroNet#1252]
### Step 1: Please describe your environment

  * ZeroNet version: Latest (Version: 0.6.1 r3221 I think)
  * Operating system: MacOS Sierra 10.12.6 (16G29)
  * Web browser: Irrelevant. Though I normally use Firefox Nightly
  * Tor status: Default setting
  * Opened port: Either way, both fail.
  * Special configuration: Nothing

### Step 2: Describe the problem:

ZeroNet fails to start. The error log is as follows:

```
$ python zeronet.py
- Starting ZeroNet...
[19:02:39] - OpenSSL loaded, version: 0009081DF
[19:02:39] - Version: 0.6.1 r3221, Python 2.7.6 (v2.7.6:3a1db0d2747e, Nov 10 2013, 00:42:54)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)], Gevent: 1.2.2
[19:02:39] - Unhandled exception: unqualified exec is not allowed in function 'bench' it is a nested function (UiRequest.py, line 645)
Traceback (most recent call last):
  File "zeronet.py", line 19, in main
    main.start()
  File "/Users/Kafke/Downloads/ZeroNet-master/src/main.py", line 502, in start
    actions.call(config.action, action_kwargs)
  File "/Users/Kafke/Downloads/ZeroNet-master/src/main.py", line 155, in call
    func(**kwargs)
  File "/Users/Kafke/Downloads/ZeroNet-master/src/main.py", line 161, in main
    from Ui import UiServer
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Users/Kafke/Downloads/ZeroNet-master/src/Ui/__init__.py", line 1, in <module>
    from UiServer import UiServer
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Users/Kafke/Downloads/ZeroNet-master/src/Ui/UiServer.py", line 12, in <module>
    from UiRequest import UiRequest
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
SyntaxError: unqualified exec is not allowed in function 'bench' it is a nested function (UiRequest.py, line 645)
[19:02:39] - Unhandled exception
None
Traceback (most recent call last):
  File "zeronet.py", line 91, in <module>
    main()
  File "zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'
```

**Comment by japzone1** [comment]
Looking for similar errors, looks like it might be related to a bug that was fixed in Python 2.7.9. Maybe try updating it?

**Comment by April93** [comment]
I'm not sure what the fix was for the config thing, but that went away eventually. The other error had an issue with this line in /src/ui/uirequest.py

```
 exec(init, globals(), locals())
```

I changed it to:

```
exec init in globals(), locals()
```

And it worked fine. Is it due to an older python version? I'll have to look into updating.

**Comment by japzone1** [comment]
My ZeroNet on Windows is running off of Python 2.7.9(pure coincidence) and didn't encounter this. So it probably is related to that old bug I mentioned.

**Comment by imachug** [comment]
@April93 Weird, that `exec init in globals(), locals()` is Python3-style.

**Comment by April93** [comment]
[Here's the stackoverflow page](https://stackoverflow.com/questions/4484872/why-doesnt-exec-work-in-a-function-with-a-subfunction) I read on how to 'fix' the problem. No idea what's going on tbh.

**Comment by imachug** [comment]
PR: #1253.

**Comment by April93** [comment]
I tried updating to python 2.7.14 and it works fine without the fix.

**Comment by japzone1** [comment]
Yeah, looks like this was a bug in Python <=2.7.8, which was fixed in 2.7.9.

[This answer](https://stackoverflow.com/a/41368813) on that Stackoverflow page you linked explains it.

**Comment by HelloZeroNet** [comment]
Thanks for reporting. I switched to eval from exec: https://github.com/HelloZeroNet/ZeroNet/commit/0c6c7d27252f01cddbc8cc7109082f6a72afb7d7#diff-7fa31802ec08bb55f5128c3e841b5f34R645

Can you please verify if it's fixed the problem?
You have to save https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/0c6c7d27252f01cddbc8cc7109082f6a72afb7d7/src/Ui/UiRequest.py to Users/Kafke/Downloads/ZeroNet-master/src/Ui directory

**Comment by April93** [comment]
Unfortunately as I mentioned, I already updated my python version. I'm unsure of how to downgrade.

**Comment by HelloZeroNet** [comment]
I just tested it with python 2.6.x and it works (the exec code drops the same error as you described), so I suppose it will work with 2.7.6
