### ISSUE TITLE
should zeronet.conf need to have all the configuration as shared in the example ?

### ISSUE THREAD

**Issue by shirishag75** [HelloZeroNet/ZeroNet#1271]
### Step 1: Please describe your environment

  * ZeroNet version:  0.6.1 r3234
  * Operating system: Debian buster
  * Web browser: 52.6.0
  * Tor status: always
  * Opened port: no 
  * Special configuration:      in /etc/tor

```
ControlPort 9051
CookieAuthentication 1
```
from https://zeronet.readthedocs.io/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linux

### Step 2: Describe the problem:

I just want to have the log directory in a separate directory not anything else. 

See  https://zeronet.readthedocs.io/en/latest/faq/#is-it-possible-to-use-a-configuration-file

I want/ed to do - 

You can put your configuration options to a zeronet.conf file. Example:

```
[global]
log_dir = ~/log/

```

I get the following error message - 

```
- Starting ZeroNet...
ERROR:root:Unhandled exception: [Errno 2] No such file or directory: '~/log/'
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/home/shirish/games/ZeroNet-master/src/main.py", line 32, in <module>
    os.mkdir(config.log_dir)
OSError: [Errno 2] No such file or directory: '~/log/'
Traceback (most recent call last):
  File "zeronet.py", line 91, in <module>
    main()
  File "zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'

```

This is when I have made - 

```
/home/shirish/games/ZeroNet-master> ls -l | grep log
drwxr-xr-x  2 shirish shirish  4096 Jan 31 12:58 log
```

I have tried it both with zeronet-stable 0.6.1 and zeronet-master and got the same error message. 

I am happy with all the other defaults hence don't want to change anything and don't even know why I need to change the other options such as data-dir and UI-restrict bits.  There is simply no explanation of what those options do. 

  * What did you expect to happen?

I expected it to run without issues as I have given the path. I actually expected to make the log directory when it was not there but didn't and had to create it manually.

**Comment by imachug** [comment]
Try not to set `~/log` - instead, set `/home/whatever/log`. AFAIK ZeroNet doesn't do alias expansion.

**Comment by shirishag75** [comment]
I actually tried it both ways, using `/home/whatever/log/` and the other way but got the same error. AIUI from the FAQ it's a log directory and not log so each time when I disconnect and reconnect again to zeronet a new file will be made or am I misunderstanding something ?

**Comment by imachug** [comment]
Wait what? Please replace that with `/home/whatever/log` and post the error again please - it should be changed.

**Comment by shirishag75** [comment]
Yes, did that and again got the same error. 

See - 
```

/home/shirish/games/ZeroNet-master> cat zeronet.conf
[global]
log_dir = /home/shirish/games/Zeronet-master/log/
```

and 

```
/home/shirish/games/ZeroNet-master> python zeronet.py
- Starting ZeroNet...
ERROR:root:Unhandled exception: [Errno 2] No such file or directory: '/home/shirish/games/Zeronet-master/log/'
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/home/shirish/games/ZeroNet-master/src/main.py", line 32, in <module>
    os.mkdir(config.log_dir)
OSError: [Errno 2] No such file or directory: '/home/shirish/games/Zeronet-master/log/'
Traceback (most recent call last):
  File "zeronet.py", line 91, in <module>
    main()
  File "zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))

```

I just ran it again, got the same error as above.

**Comment by imachug** [comment]
Try to delete `/` from the end.

**Comment by shirishag75** [comment]
Did that got the same error without the / 

```
/home/shirish/games/ZeroNet-master> cat zeronet.conf
[global]
log_dir = /home/shirish/games/Zeronet-master/log
```

```
- Starting ZeroNet...
ERROR:root:Unhandled exception: [Errno 2] No such file or directory: '/home/shirish/games/Zeronet-master/log'
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/home/shirish/games/ZeroNet-master/src/main.py", line 32, in <module>
    os.mkdir(config.log_dir)
OSError: [Errno 2] No such file or directory: '/home/shirish/games/Zeronet-master/log'
Traceback (most recent call last):
  File "zeronet.py", line 91, in <module>
    main()
  File "zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'
```

Didn't make much of a difference.

**Comment by shirishag75** [comment]
Whether I create the log directory within the `/home/shirish/games/Zeronet-master` or not doesn't make any difference, get the same error as above.  Weird to say the least.

**Comment by imachug** [comment]
Yeah, weird. You mentioned headless Linux. What if ZeroNet is running under some other user or whatever?

**Comment by shirishag75** [comment]
no, I never mentioned headless Linux anywhere. From where did you get that assumption ?

**Comment by imachug** [comment]
@shirishag75 Seriously? Looks like I should to sleep more.
