### ISSUE TITLE
gevent.hub.Hub.handle_error not found using old gevent hooks

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1278]
Hello is this because of old Python/old OS? Because on newer OS version i do not have this error:

```
$ python zeronet.py siteDownload ziteAddress
- Starting ZeroNet...
- gevent.hub.Hub.handle_error not found using old gevent hooks
PluginManager Plugin Bigfile load error: SyntaxError: invalid syntax (BigfilePlugin.py, line 564) in PluginManager.py line 40 > __init__.py line 1
PluginManager Plugin Chart load error: SyntaxError: invalid syntax (Db.py, line 305) in PluginManager.py line 40 > __init__.py line 1 > ChartPlugin.py line 9 > ChartDb.py line 2 > __init__.py line 1
PluginManager Plugin CryptMessage load error: AttributeError: 'tuple' object has no attribute 'major' in PluginManager.py line 40 > __init__.py line 1 > CryptMessagePlugin.py line 5 > CryptBitcoin.py line 4 > __init__.py line 1 > py2specials.py line 7
PluginManager Plugin Newsfeed load error: SyntaxError: invalid syntax (Db.py, line 305) in PluginManager.py line 40 > __init__.py line 1 > NewsfeedPlugin.py line 5 > __init__.py line 1
PluginManager Plugin OptionalManager load error: SyntaxError: invalid syntax (ContentDbPlugin.py, line 91) in PluginManager.py line 40 > __init__.py line 1 > OptionalManagerPlugin.py line 6
- Unhandled exception: invalid syntax (Peer.py, line 295)
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/root/ZeroBundle/ZeroNet/src/main.py", line 107, in <module>
    PluginManager.plugin_manager.loadPlugins()
  File "/root/ZeroBundle/ZeroNet/src/Plugin/PluginManager.py", line 47, in loadPlugins
    func()
  File "plugins/AnnounceZero/AnnounceZeroPlugin.py", line 17, in importErrors
    from Peer import Peer
  File "/root/ZeroBundle/ZeroNet/src/Peer/__init__.py", line 1, in <module>
    from Peer import Peer
  File "/root/ZeroBundle/ZeroNet/src/Peer/Peer.py", line 295
     back = {key: map(helper.unpackAddress, val) for key, val in res["peers"].items()[0:30]}
                                                   ^
 SyntaxError: invalid syntax
- Unhandled exception
None
Traceback (most recent call last):
  File "zeronet.py", line 91, in <module>
    main()
  File "zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'
```
-----

Non working server:
Python 2.6.6 (today's latest zeronet version rev3234)

Working server:
Python 2.7.5 (rev3221)

If you can not discover cause, please close this issue as it may not be Zeronet issue.

**Comment by HelloZeroNet** [comment]
I'm afraid python 2.7.x version is the minimum required (2.6.6 is released 10 years ago)
