### ISSUE TITLE
Please update installation guide

### ISSUE THREAD

**Issue by beenotung** [HelloZeroNet/ZeroNet#1302]
If I clone this projec then run the zeronet.py, it doesn't work.

Even after I run `sudo pip install -r requirements.txt`, It doesn't works.

```
beenotung:ZeroNet$ ./zeronet.py 
- Starting ZeroNet...
ERROR:root:Unhandled exception: No module named gevent
Traceback (most recent call last):
  File "./zeronet.py", line 18, in main
    import main
  File "/home/beenotung/local/opt/ZeroNet/src/main.py", line 9, in <module>
    import gevent
ImportError: No module named gevent
Traceback (most recent call last):
  File "./zeronet.py", line 91, in <module>
    main()
  File "./zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'

```

Maybe related to https://github.com/HelloZeroNet/ZeroNet/issues/1056

**Comment by beenotung** [comment]
Solution:
```
sudo pip2 install -r requirements.txt
```

Note that it's using python 2.
I suggest to include a install script in the root folder, so people not familiar with python (2 v.s. 3) can get started easily.

**Comment by beenotung** [comment]
created this pull request: https://github.com/HelloZeroNet/ZeroNet/pull/1303

**Comment by jebuscraisp** [comment]
Hi @beenotung , am curious about this output , is it not connecting to the tor network?

**Comment by beenotung** [comment]
I wonder why the pull reuest is not accepted yet.
It works.
