### ISSUE TITLE
sitePublish is not working

### ISSUE THREAD

**Issue by bitcoren** [HelloZeroNet/ZeroNet#1404]
### Step 1: Please describe your environment

  * ZeroNet version: 3417
  * Operating system: Ubuntu 16.04
  * Web browser: -
  * Tor status: always
  * Opened port: yes
  * Special configuration: -

sitePublish is not working after changing zite

bitcoren@nCoin:~$ ~/ZeroNet-0.6.2/zeronet.py sitePublish 1FbmSKV653gt8Q7Cf6ozAf2CUCTmwmtSkE
- Starting ZeroNet...
- OpenSSL loaded, version: 01000207F
- Version: 0.6.2 r3417, Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609], Gevent: 1.2.2
- Loading site...
- Unhandled exception: 'NoneType' object has no attribute 'settings'
Traceback (most recent call last):
  File "/home/bitcoren/ZeroNet-0.6.2/zeronet.py", line 19, in main
    main.start()
  File "/home/bitcoren/ZeroNet-0.6.2/src/main.py", line 537, in start
    actions.call(config.action, action_kwargs)
  File "/home/bitcoren/ZeroNet-0.6.2/src/main.py", line 157, in call
    back = func(**kwargs)
  File "/home/bitcoren/ZeroNet-0.6.2/src/main.py", line 395, in sitePublish
    site.settings["serving"] = True  # Serving the site even if its disabled
AttributeError: 'NoneType' object has no attribute 'settings'
- Unhandled exception
None
Traceback (most recent call last):
  File "/home/bitcoren/ZeroNet-0.6.2/zeronet.py", line 91, in <module>
    main()
  File "/home/bitcoren/ZeroNet-0.6.2/zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'

**Comment by bitcoren** [comment]
Thanks, i open 43110 port on VPS NAT and all is woking.
