### ISSUE TITLE
Failed to execute script boot: No module named gevent

### ISSUE THREAD

**Issue by eddiejibson** [HelloZeroNet/ZeroNet#1409]
### Step 1: Please describe your environment

  * ZeroNet version: Latest (0.6.2)
  * Operating system: Windows 10
  * Python Version: 3.6.5

### Step 2: Describe the problem:
When I try and launch ZeroNet.exe I get the error "Failed to execute script boot". So, I decided to try and execute zeronet.py from within the core directory and this gave a bit more detail:
```
ERROR:root:Unhandled exception: No module named gevent
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "C:\Users\Eddie\Documents\ZeroNet\ZeroNet-win-dist\core\src\main.py", line 9, in <module>
    import gevent
ImportError: No module named gevent
- Starting ZeroNet...
Traceback (most recent call last):
  File "zeronet.py", line 91, in <module>
    main()
  File "zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'
```
Thing is, I have already installed gevent with pip even with the --user arguments as I saw suggested on another issue...

It literally worked on the same machine about 1 week ago but I since removed the directory by accident and was going to try again...

Any ideas?

**Comment by grez911** [comment]
ZeroNet works only with Python 2, not 3.
And this is not an error in ZeroNet code. If you create a Python script with just one line:
```
import gevent
```
and run it you will get the same error: `ImportError: No module named gevent`.

You can list all installed modules by the following command:
```
python -c "modules"
```

**Comment by eddiejibson** [comment]
Hi, @grez911 
Thanks for you reply.
I uninstalled Python 3 fully and replaced with Python 2.7.15 and the same issue is occurring...

**Comment by HelloZeroNet** [comment]
You have to install gevent and msgpack using `python2 -m pip install gevent msgpack`

**Comment by MountainMaster** [comment]
Same error here.
Python 2.7.14 with installed gevent and msgpack on Windows 10.

ZeroNet.exe shows "Failed to execute script boot"

**Comment by HelloZeroNet** [comment]
If you use ZeroNet.exe, then you don't installed python, everything is included. Are you sure everything is unpacked to the same directory? Do you have "core" and "lib" directories beside ZeroNet.exe?

**Comment by Tallefer** [comment]
@HelloZeroNet sorry for being slightly offtopic, but since I couldn't find any relevant info and it's not big enough a reason to make a new issue, so: is ZeroNet portable (everything is placed inside one directory, including configs and user-generated data)?

**Comment by HelloZeroNet** [comment]
Yes, on Windows/Linux it's portable. On MacOS it writes to ~/Library/Application Support/ZeroNet due sandboxing restrictions.

**Comment by Tallefer** [comment]
Ah, thanks, good to know. Probably worth mentioning that in the readme?

**Comment by DaniellMesquita** [comment]
@MountainMaster
@eddiejibson

This occurs when the ZeroNet's drive is removed while it is running, or when you turn off your computer with ZeroNet running, and uses the drive in another device.
The files are corrupted, so you need to move the important things to a new/fresh ZeroNet installation.
@HelloZeroNet should fix this issue of file corruption when removing drive/using drive in another device while ZeroNet was open.
