### ISSUE TITLE
Tor Error: Status: Error ([Errno 13] Permission denied: '/var/lib/tor/control_auth_cookie')

### ISSUE THREAD

**Issue by ilovelinux** [HelloZeroNet/ZeroNet#1440]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2 (rev3467)
  * Operating system: Archlinux
  * Web browser: Firefox Developer Edition 61.0
  * Tor status: not available(?)
  * Opened port: no
  * Special configuration: no

#### Steps to reproduce:

  1. Install ZeroNet
  2. Follow these instructions: https://wiki.archlinux.org/index.php/ZeroNet
  3. Try to make ZeroNet connect through Tor

#### Observed Results:

  * ZeroNet can't access to tor Control Auth Cookie

#### Expected Results:

  * Zeronet should be allowed to read Control Auth Cookie

```
$ groups zeronet
tor zeronet
```
/etc/tor/torrc:
```
## Configuration file for a typical Tor user
## Last updated 22 April 2012 for Tor 0.2.3.14-alpha.
## (may or may not work for much older or much newer versions of Tor.)
##
## Lines that begin with "## " try to explain what's going on. Lines
## that begin with just "#" are disabled commands: you can enable them
## by removing the "#" symbol.
##
## See 'man tor', or https://www.torproject.org/docs/tor-manual.html,
## for more options you can use in this file.
##
## Tor will look for this file in various places based on your platform:
## https://www.torproject.org/docs/faq#torrc

## Tor opens a socks proxy on port 9050 by default -- even if you don't
## configure one below. Set "SocksPort 0" if you plan to run Tor only
## as a relay, and not make any local application connections yourself.
#SocksPort 9050 # Default: Bind to localhost:9050 for local connections.
#SocksPort 192.168.0.1:9100 # Bind to this adddress:port too.

## Entry policies to allow/deny SOCKS requests based on IP address.
## First entry that matches wins. If no SocksPolicy is set, we accept
## all (and only) requests that reach a SocksPort. Untrusted users who
## can access your SocksPort may be able to learn about the connections
## you make.
#SocksPolicy accept 192.168.0.0/16
#SocksPolicy reject *

## Logs go to stdout at level "notice" unless redirected by something
## else, like one of the below lines. You can have as many Log lines as
## you want.
##
## We advise using "notice" in most cases, since anything more verbose
## may provide sensitive information to an attacker who obtains the logs.
##
## Send all messages of level 'notice' or higher to /var/log/tor/notices.log
#Log notice file /var/log/tor/notices.log
## Send every possible message to /var/log/tor/debug.log
#Log debug file /var/log/tor/debug.log
## Use the system log instead of Tor's logfiles
Log notice syslog
## To send all messages to stderr:
#Log debug stderr

## Uncomment this to start the process in the background... or use
## --runasdaemon 1 on the command line. This is ignored on Windows;
## see the FAQ entry if you want Tor to run as an NT service.
#RunAsDaemon 1

## The directory for keeping all the keys/etc. By default, we store
## things in $HOME/.tor on Unix, and in Application Data\tor on Windows.
DataDirectory /var/lib/tor
DataDirectoryGroupReadable 1

## The port on which Tor will listen for local connections from Tor
## controller applications, as documented in control-spec.txt.
ControlPort 9051
## If you enable the controlport, be sure to enable one of these
## authentication methods, to prevent attackers from accessing it.
#HashedControlPassword 16:872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
CookieAuthentication 1
CookieAuthFileGroupReadable 1
CookieAuthFile /var/lib/tor/control_auth_cookie

############### This section is just for location-hidden services ###

## Once you have configured a hidden service, you can look at the
## contents of the file ".../hidden_service/hostname" for the address
## to tell people.
##
## HiddenServicePort x y:z says to redirect requests on port x to the
## address y:z.

#HiddenServiceDir /var/lib/tor/hidden_service/
#HiddenServicePort 80 127.0.0.1:80

#HiddenServiceDir /var/lib/tor/other_hidden_service/
#HiddenServicePort 80 127.0.0.1:80
#HiddenServicePort 22 127.0.0.1:22

################ This section is just for relays #####################
#
## See https://www.torproject.org/docs/tor-doc-relay for details.

## Required: what port to advertise for incoming Tor connections.
#ORPort 9001
## If you want to listen on a port other than the one advertised in
## ORPort (e.g. to advertise 443 but bind to 9090), you can do it as
## follows.  You'll need to do ipchains or other port forwarding
## yourself to make this work.
#ORPort 443 NoListen
#ORPort 127.0.0.1:9090 NoAdvertise

## The IP address or full DNS name for incoming connections to your
## relay. Leave commented out and Tor will guess.
#Address noname.example.com

## If you have multiple network interfaces, you can specify one for
## outgoing traffic to use.
# OutboundBindAddress 10.0.0.5

## A handle for your relay, so people don't have to refer to it by key.
#Nickname ididnteditheconfig

## Define these to limit how much relayed traffic you will allow. Your
## own traffic is still unthrottled. Note that RelayBandwidthRate must
## be at least 20 KB.
## Note that units for these config options are bytes per second, not bits
## per second, and that prefixes are binary prefixes, i.e. 2^10, 2^20, etc.
#RelayBandwidthRate 100 KB  # Throttle traffic to 100KB/s (800Kbps)
#RelayBandwidthBurst 200 KB # But allow bursts up to 200KB/s (1600Kbps)

## Use these to restrict the maximum traffic per day, week, or month.
## Note that this threshold applies separately to sent and received bytes,
## not to their sum: setting "4 GB" may allow up to 8 GB total before
## hibernating.
##
## Set a maximum of 4 gigabytes each way per period.
#AccountingMax 4 GB
## Each period starts daily at midnight (AccountingMax is per day)
#AccountingStart day 00:00
## Each period starts on the 3rd of the month at 15:00 (AccountingMax
## is per month)
#AccountingStart month 3 15:00

## Contact info to be published in the directory, so we can contact you
## if your relay is misconfigured or something else goes wrong. Google
## indexes this, so spammers might also collect it.
#ContactInfo Random Person <nobody AT example dot com>
## You might also include your PGP or GPG fingerprint if you have one:
#ContactInfo 0xFFFFFFFF Random Person <nobody AT example dot com>

## Uncomment this to mirror directory information for others. Please do
## if you have enough bandwidth.
#DirPort 9030 # what port to advertise for directory connections
## If you want to listen on a port other than the one advertised in
## DirPort (e.g. to advertise 80 but bind to 9091), you can do it as
## follows.  below too. You'll need to do ipchains or other port
## forwarding yourself to make this work.
#DirPort 80 NoListen
#DirPort 127.0.0.1:9091 NoAdvertise
## Uncomment to return an arbitrary blob of html on your DirPort. Now you
## can explain what Tor is if anybody wonders why your IP address is
## contacting them. See contrib/tor-exit-notice.html in Tor's source
## distribution for a sample.
#DirPortFrontPage /etc/tor/tor-exit-notice.html

## Uncomment this if you run more than one Tor relay, and add the identity
## key fingerprint of each Tor relay you control, even if they're on
## different networks. You declare it here so Tor clients can avoid
## using more than one of your relays in a single circuit. See
## https://www.torproject.org/docs/faq#MultipleRelays
## However, you should never include a bridge's fingerprint here, as it would
## break its concealability and potentionally reveal its IP/TCP address.
#MyFamily $keyid,$keyid,...

## A comma-separated list of exit policies. They're considered first
## to last, and the first match wins. If you want to _replace_
## the default exit policy, end this with either a reject *:* or an
## accept *:*. Otherwise, you're _augmenting_ (prepending to) the
## default exit policy. Leave commented to just use the default, which is
## described in the man page or at
## https://www.torproject.org/documentation.html
##
## Look at https://www.torproject.org/faq-abuse.html#TypicalAbuses
## for issues you might encounter if you use the default exit policy.
##
## If certain IPs and ports are blocked externally, e.g. by your firewall,
## you should update your exit policy to reflect this -- otherwise Tor
## users will be told that those destinations are down.
##
## For security, by default Tor rejects connections to private (local)
## networks, including to your public IP address. See the man page entry
## for ExitPolicyRejectPrivate if you want to allow "exit enclaving".
##
#ExitPolicy accept *:6660-6667,reject *:* # allow irc ports but no more
#ExitPolicy accept *:119 # accept nntp as well as default exit policy
#ExitPolicy reject *:* # no exits allowed

## Bridge relays (or "bridges") are Tor relays that aren't listed in the
## main directory. Since there is no complete public list of them, even an
## ISP that filters connections to all the known Tor relays probably
## won't be able to block all the bridges. Also, websites won't treat you
## differently because they won't know you're running Tor. If you can
## be a real relay, please do; but if not, be a bridge!
#BridgeRelay 1
## By default, Tor will advertise your bridge to users through various
## mechanisms like https://bridges.torproject.org/. If you want to run
## a private bridge, for example because you'll give out your bridge
## address manually to your friends, uncomment this line:
#PublishServerDescriptor 0
```
I recently updated tor, and I noticed this issue only after that:
```
$ tor --version
Tor version 0.3.3.6 (git-7dd0813e783ae16e).
```

**Comment by grez911** [comment]
Please, show:
```
$ sudo -u zeronet ls -l /var/lib/tor/control_auth_cookie
```

**Comment by HelloZeroNet** [comment]
Probably its related: https://github.com/HelloZeroNet/ZeroNet/issues/1331

Looks like the Tor package on arch has a configuration that does not adds group read permissions to the tor socket file

**Comment by ilovelinux** [comment]
@grez911
```
$ sudo -u zeronet ls -l /var/lib/tor/control_auth_cookie
ls: cannot access '/var/lib/tor/control_auth_cookie': Permission denied
```

@HelloZeroNet I think so

**Comment by ilovelinux** [comment]
```
$ ls -l /var/lib/
...
drwx------   4 tor            tor             4096 May 28 20:28 tor
...
```
and
```$ ls -l /var/lib/tor/
total 5484
drwx------  3 tor  tor     4096 May 28 20:32 .
drwxr-xr-x 28 root root    4096 May 28 20:31 ..
-rw-------  1 tor  tor    20442 May 28 20:32 cached-certs
-rw-------  1 tor  tor  1986837 May 28 20:32 cached-microdesc-consensus
-rw-------  1 tor  tor  3583528 May 28 20:32 cached-microdescs.new
-rw-r-----  1 tor  tor       32 May 28 20:32 control_auth_cookie
drwx------  2 tor  tor     4096 May 28 20:32 keys
-rw-------  1 tor  tor        0 May 28 20:32 lock
-rw-------  1 tor  tor      215 May 28 20:32 state
```

**Comment by donni3** [comment]
+1

**Comment by HelloZeroNet** [comment]
According to http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1528116214_16CWdkXYYRnpct8GYS7GgD6yFcJHPXfMy8 this configuration of Tor works:
```
CookieAuthentication 1
DataDirectoryGroupReadable 1
CookieAuthFileGroupReadable 1
ExtORPortCookieAuthFileGroupReadable 1
CacheDirectoryGroupReadable 1
CookieAuthFile /var/lib/tor/control_auth_cookie
```

**Comment by ilovelinux** [comment]
It works! Thanks

**Comment by aspiringguru** [comment]
Found this in November 2019.
tried adding CacheDirectoryGroupReadable 1 to /etc/tor/torrc 

sudo service tor restart
[warn] Failed to parse/validate config: Unknown option 'CacheDirectoryGroupReadable'.  Failing.



fwiw, I'm new to using tor with coding, trying this example > https://www.sylvaindurand.org/use-tor-with-python/

from stem import Signal
from stem.control import Controller

with Controller.from_port(port = 9051) as c:
    c.authenticate()
    c.signal(Signal.NEWNYM)


above code returns this error.
stem.connection.UnreadableCookieFile: Authentication failed: unable to read '/var/run/tor/control.authcookie' ([Errno 13] Permission denied: '/var/run/tor/control.authcookie')


#currently my /etc/tor/torrc only has these lines.
ControlPort 9051                                                                                                                                                                   CookieAuthentication 1     

#stepping back and realising the obvious
ls -la /var/run/tor/control.authcookie
returned 
-rw-r----- 1 debian-tor debian-tor 32 Nov  8 17:22 /var/run/tor/control.authcookie

#so it's obvious how to fix. :)
chmod 777 /var/run/tor/control.authcookie

just leaving this for future alternate versions of me experiencing similar problems to find.

**Comment by purplesyringa** [comment]
> chmod 777 /var/run/tor/control.authcookie

Don't do this! It allows all programs to control Tor settings. Instead, create a separate user for ZeroNet, do chown for control.authcookie and ZeroNet files, then chmod 700 for control.authcookie and optionally chmod +s for ZeroNet executable if you want to.

**Comment by parsandvenom** [comment]
Traceback (most recent call last):
  File "/usr/bin/torghost", line 183, in <module>
    start_torghost()
  File "/usr/bin/torghost", line 99, in start_torghost
    with open(Torrc, "a") as myfile:
IOError: [Errno 13] Permission denied: '/etc/tor/torrc'


yardımcı olabilecek birileri var mı ,?
