### ISSUE TITLE
ChartCollector.py: list index out of range 

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1544]
rev3571
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "plugins\Chart\ChartCollector.py", line 171, in collector
    collectors = self.getCollectors()
  File "plugins\Chart\ChartCollector.py", line 30, in getCollectors
    content_db = sites.values()[0].content_manager.contents.db
IndexError: list index out of range

**Comment by HelloZeroNet** [comment]
Thanks, fixed in Rev3576: https://github.com/HelloZeroNet/ZeroNet/commit/1cf50e5fcd81e279e77eec4d8f59a2bd94795830
