### ISSUE TITLE
Android client BUG log. Looking forward to your reply

### ISSUE THREAD

**Issue by YXG1994** [HelloZeroNet/ZeroNet#1624]
Zeronet version 0.6.3.3

After opening the client, it flashes back. I don't know what the reason is. Is it related to the lack of space on the phone? Looking forward for your reply, thank you

#######RuntimeEnvironmentInforation#######
crash time=2018-09-19 22:10:36.988
model=SM-N9100
android version=4.4.4(19)
brand=samsung
manufacturer=samsung
board=APQ8084
hardware=qcom
device=trltechn
version name=0.6.3.3
cpu_abi=armeabi-v7a
cpu_abi2=armeabi
display=KTU84P.N9100ZCU1AOB1
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: net.mkg20001.zeronet, PID: 32329
java.lang.UnsatisfiedLinkError: Native method not found: org.libsdl.app.SDLActivity.nativeSetEnv:(Ljava/lang/String;Ljava/lang/String;)V
	at org.libsdl.app.SDLActivity.nativeSetEnv(Native Method)
	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:167)
	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:114)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5748)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by DaniellMesquita** [comment]
@mkg20001
How Python can work trought Cordova, like Electron supports?

**Comment by mkg20001** [comment]
@DaniellMesquita I'm not using cordva, I'm using python-for-android. Using cordova  would be more trouble than it's worth it considering the already overly complex build process with python-buildozer.
