### ISSUE TITLE
Unhandled exception: 'Config' object has no attribute 'trackers_file'

### ISSUE THREAD

**Issue by rllola** [HelloZeroNet/ZeroNet#1661]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.3
  * Operating system: Ubuntu 18.04
  * Web browser: Firefox
  * Tor status: disabled
  * Opened port: yes
  * Special configuration: None
### Step 2: Describe the problem:

I am trying to sign a site but it failed with an "Unhandled exception" message.

#### Steps to reproduce:

  1. Try to signSite : 
```
python zeronet.py signSite 1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

#### Observed Results:

Error message : 
```
- Starting ZeroNet...
ERROR:root:Unhandled exception: 'Config' object has no attribute 'trackers_file'
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/home/lola/Workspace/ZeroNet/ZeroNet-master/src/main.py", line 27, in <module>
    config.parse(silent=True)  # Plugins need to access the configuration
  File "/home/lola/Workspace/ZeroNet/ZeroNet-master/src/Config.py", line 370, in parse
    self.loadTrackersFile()
  File "/home/lola/Workspace/ZeroNet/ZeroNet-master/src/Config.py", line 286, in loadTrackersFile
    if not self.trackers_file:
AttributeError: 'Config' object has no attribute 'trackers_file'
Traceback (most recent call last):
  File "zeronet.py", line 88, in <module>
    main()
  File "zeronet.py", line 53, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'
```

#### Expected Results:

We expect the site to be signed.

**Comment by rllola** [comment]
Ok. I understand what happened. 
I used the wrong command : `signSite` instead of `siteSign`

However it should have shown me the help section but instead I got this error message. A proper fix should verify if the command entered exist before trying to do anything. A quick fix would just initialize `tracker_files` with `None`.

**Comment by DaniellMesquita** [comment]
@rllola
I've forked KopyKate and begining the NetVision project, that will have hubs (then it can be cloneable when abandonned) and is intended to be maintened.
http://127.0.0.1:43110/netvision.bit
Tell me if you want to also manage it (I believe ZeroNet needs more projects with multiple owners).
I can send the privatekey to your ZeroMail.

**Comment by rllola** [comment]
@DaniellMesquita 
Thanks for the update. I am going to take a look at it. 

But in the future please contact me via ZeroMail or on ThunderWave. Try to keep issues dedicated to Zeronet issues :wink:

**Comment by DaniellMesquita** [comment]
@rllola
Emails sent on ZeroMail.
Thanks, and sorry for the off-topic here.
