### ISSUE TITLE
self.checkBadFiles()  AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1664]
```
Traceback (most recent call last):
  File "site-packages\gevent\greenlet.py", line 536, in run
  File "F:\Zeronet2\core\src\Site\Site.py", line 431, in update
    self.checkBadFiles()
  File "F:\Zeronet2\core\src\Site\Site.py", line 285, in checkBadFiles
    file_info = self.content_manager.getFileInfo(bad_file)
  File "plugins\Bigfile\BigfilePlugin.py", line 191, in getFileInfo
    return super(ContentManagerPlugin, self).getFileInfo(inner_path, *args, **kwargs)
  File "F:\Zeronet2\core\src\Content\ContentManager.py", line 349, in getFileInfo
    user_auth_address = re.match("([A-Za-z0-9]+)/.*", relative_content_path).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

rev 3611

**Comment by HelloZeroNet** [comment]
Can you please give me the site address that caused the error?

**Comment by blurHY** [comment]
Oh,i forgot that.
