### ISSUE TITLE
Restart fails

### ISSUE THREAD

**Issue by lezsakdomi** [HelloZeroNet/ZeroNet#1768]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.4
  * Operating system: Gentoo (`Linux ledomi-pc 4.12.5-gentoo #3 SMP Sat Jun 2 11:29:07 CEST 2018 x86_64 Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz GenuineIntel GNU/Linux`)
  * Web browser: Firefox 58.0.1
  * Tor status: not available
  * Opened port: no
  * Special configuration: Installed from the respository

### Step 2: Describe the problem:

When I try to update ZeroNet, becomes unavailable

#### Steps to reproduce:

  1. In ZeroHello click on three-dot menu
  2. Click on _Version 0.6.4 (rev3670): Up to date!_
  3. Click the yellow _Update ZeroNet_ button on top-right

*__Or__*

  1. Change a config
  2. Click on the restart button which appears

#### Observed Results:

Zeronet gone down for restart, but didn't start after.

Here's a log from systemd:

```
systemd[2]: Started ZeroNet: Decentralized websites using Bitcoin crypto and BitTorrent network.
zeronet[10319]: [19:19:50] - OpenSSL loaded, version: 0100020FF
zeronet[10319]: [19:19:50] - Version: 0.6.4 r3670, Python 2.7.14 (default, Mar 31 2018, 04:20:41)
zeronet[10319]: [GCC 6.4.0], Gevent: 1.2.1
zeronet[10319]: [19:19:50] - Creating FileServer....
zeronet[10319]: [19:19:50] - Creating UiServer....
zeronet[10319]: [19:19:50] - Removing old SSL certs...
zeronet[10319]: [19:19:50] - Starting servers....
zeronet[10319]: [19:19:50] Ui.UiServer --------------------------------------
zeronet[10319]: [19:19:50] Ui.UiServer Web interface: http://127.0.0.1:43110/
zeronet[10319]: [19:19:50] Ui.UiServer --------------------------------------
zeronet[10319]: [19:19:50] TorManager Connecting to Tor Controller 127.0.0.1:9051
zeronet[10319]: [19:19:50] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 190 > _socket2.py line 231
zeronet[10319]: [19:19:50] TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: No connection
zeronet[10319]: [19:19:50] Site:1Name2..hM9F Tracker udp://5.79.83.193:6969 announce failed: [Errno 111] Connection refused in mode startup
zeronet[10319]: [19:19:51] ConnServer Checking port 23239 using portchecker.co...
zeronet[10319]: [19:19:52] ConnServer [BAD :(] Port closed: Port 23239 is closed.
zeronet[10319]: [19:19:52] ConnServer Trying to open port using UpnpPunch...
zeronet[10319]: [19:19:59] Site:1HeLLo..Tf3D Tracker udp://5.79.83.193:6969 announce failed: Could not connect in mode startup
zeronet[10319]: [19:20:02] ConnServer UpnpPunch run error: UpnpError: Failed to communicate with igd using port 23239 on local machine after 3 tries. in FileServer.py line 118 > UpnpPunch.py line 349 > UpnpPunch>
zeronet[10319]: [19:20:03] - All server stopped
zeronet[10319]: [19:20:03] - Unhandled exception: No module named update
zeronet[10319]: Traceback (most recent call last):
zeronet[10319]:   File "/usr/share/zeronet/zeronet.py", line 22, in main
zeronet[10319]:     import update
zeronet[10319]:   File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
zeronet[10319]:     result = _import(*args, **kwargs)
zeronet[10319]: ImportError: No module named update
zeronet[10319]: No handlers could be found for logger "SiteManager"
zeronet[10319]: DEBUG:-:Trying using local ip: 192.168.1.54
zeronet[10319]: DEBUG:Ui.UiServer:127.0.0.1 - - [2018-11-06 19:20:04] "GET /Websocket?wrapper_key=c470351a0993ef674929395eed87f5a763b8bae2645743ca73f887764794208d HTTP/1.1" 101 129 12.305931
zeronet[10319]: - Starting ZeroNet...
zeronet[10319]: Can't open lock file, your ZeroNet client is probably already running, exiting... ([Errno 11] Resource temporarily unavailable)
```

And service goes failed status.

*__Or__*

When installed manually and started using `./ZeroNet.sh`:

```
...
[20:22:06] - All server stopped
Restarting...
No handlers could be found for logger "SiteManager"
DEBUG:-:Gevent block detected: 0.124728918076
DEBUG:Ui.UiServer:127.0.0.1 - - [2018-11-06 20:22:07] "GET /Websocket?wrapper_key=b25fc570c362b991eb24aef00a1323733e2a94cf542550c5c430956b24db755b HTTP/1.1" 101 129 8.978960
Executing /home/led/Downloads/ZeroBundle/ZeroNet/../Python/python2.7 ['/home/led/Downloads/ZeroBundle/ZeroNet/../Python/python2.7', 'start.py', '--open_browser', 'default_browser']
- Starting ZeroNet...
Can't open lock file, your ZeroNet client is probably already running, exiting... ([Errno 11] Resource temporarily unavailable)
Opening browser: %s... default_browser
This tool has been deprecated, use 'gio open' instead.
See 'gio help open' for more info.

```

#### Expected Results:

ZeroNet simply restarts.

**Comment by HelloZeroNet** [comment]
Probably it's something related to the package. Can you please run an `ls -al /usr/share/zeronet/`?

**Comment by lezsakdomi** [comment]
In the meantime, I went over the GitHub version, and I couldn't reproduce it any more :(
