### ISSUE TITLE
Site:1TaLkF..jipT FileWrite forbidden - sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1782]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.4 r3703
  * Operating system: Linux debian
  * Web browser: FF
  * Tor status: error
  * Opened port: no

### Step 2: Describe the problem:

When i tried to do an action like upvote on ZeroTalk, it says: "File write error: Forbidden, you can only modify your own files"
And debug.log shows:
Site:1TaLkF..jipT FileWrite forbidden MyPublicKeyHere not in valid_signers [u'1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT']
I tried to "Check files", "Update", "Reload" db, and Rebuild db. Rebuilding was done instantly and db shows 20kb which is wrong, a few minutes back same happened to other zerotalk clone forum and when i deleted and revisited that clone site, site started working, but i lost all following of topics, i do not want same happen to ZeroTalk, do i have to manually backup my ZeroNet/data/users.json, or what else to try?

debug.log upon ZN start shows:
```
[***] - Unhandled exception
Traceback (most recent call last):
  File "/home/me/Apps/ZeroBundle/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/me/Apps/ZeroBundle/ZeroNet/plugins/Chart/ChartCollector.py", line 178, in collector
    self.collectGlobal(collectors, self.last_values)
  File "/home/me/Apps/ZeroBundle/ZeroNet/plugins/Chart/ChartCollector.py", line 148, in collectGlobal
    cur.cursor.executemany("INSERT INTO data (type_id, value, date_added) VALUES (?, ?, ?)", values)
DatabaseError: database disk image is malformed
Traceback (most recent call last):
  File "/home/me/Apps/ZeroBundle/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/me/Apps/ZeroBundle/ZeroNet/plugins/Chart/ChartCollector.py", line 178, in collector
    self.collectGlobal(collectors, self.last_values)
  File "/home/me/Apps/ZeroBundle/ZeroNet/plugins/Chart/ChartCollector.py", line 148, in collectGlobal
    cur.cursor.executemany("INSERT INTO data (type_id, value, date_added) VALUES (?, ?, ?)", values)
sqlite3.DatabaseError: database disk image is malformed
```

When my ZeroNet data HDD disconnects, then Zeronet apparently gets damaged, this happen not so rarely, it can be good if zeronet has some protection against this.

So what i did is to quit ZN and delete ZeroNet/data/content.db + Zarotalk .db file and start ZN, it lags my Linux PC ([high start.py RAM usage](https://github.com/HelloZeroNet/ZeroNet/issues/1774), resulting in high HDD activity because of swapping), takes like 30 minutes  to rebuild because of possibly like 1000 zites, that time is OK, but excessive ZN RAM usage seems not good. Then after start ZeroNet still shows ZeroTalk DB size 20KB and rebuilding also the same and ZeroTalk topic does not loading.
```
[11:12:27] Site:1TaLkF..jipT Deleting /media/veracrypt1/ZeroNet/data/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/data/users/zerotalk.db
[11:12:27] Site:1TaLkF..jipT Creating tables...
[11:12:28] Db:ZeroTalk Table keyvalue outdated...version: False need: 2, rebuilding...
[11:12:28] Db:ZeroTalk Table json outdated...version: 0 need: 2, rebuilding...
[11:12:28] Db:ZeroTalk Table topic outdated...version: 0 need: 1, rebuilding...
[11:12:28] Db:ZeroTalk Table comment outdated...version: 0 need: 1, rebuilding...
[11:12:28] Db:ZeroTalk Table comment_vote outdated...version: 0 need: 1, rebuilding...
[11:12:28] Db:ZeroTalk Table topic_vote outdated...version: 0 need: 1, rebuilding...
[11:12:28] Site:1TaLkF..jipT Getting db files...
[11:12:28] Site:1TaLkF..jipT Importing data...
[11:12:28] Site:1TaLkF..jipT Closing Db: <Db#139636007075920:/media/veracrypt1/ZeroNet/data/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/data/users/zerotalk.db close_idle:False>
[11:12:28] Site:1TaLkF..jipT Imported 0 data file in 0.00374007225037s
```

Update, Check files, nothing. So after a few minutes i shutdown ZN and try to start it again, log again shows:

```
[11:14:09] ConnServer Trying to open port using UpnpPunch...
[11:16:10] - Unhandled exception
Traceback (most recent call last):
  File "/home/me/Apps/ZeroBundle/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/me/Apps/ZeroBundle/ZeroNet/plugins/Chart/ChartCollector.py", line 178, in collector
    self.collectGlobal(collectors, self.last_values)
  File "/home/me/Apps/ZeroBundle/ZeroNet/plugins/Chart/ChartCollector.py", line 148, in collectGlobal
    cur.cursor.executemany("INSERT INTO data (type_id, value, date_added) VALUES (?, ?, ?)", values)
DatabaseError: database disk image is malformed
Traceback (most recent call last):
  File "/home/me/Apps/ZeroBundle/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/me/Apps/ZeroBundle/ZeroNet/plugins/Chart/ChartCollector.py", line 178, in collector
    self.collectGlobal(collectors, self.last_values)
  File "/home/me/Apps/ZeroBundle/ZeroNet/plugins/Chart/ChartCollector.py", line 148, in collectGlobal
    cur.cursor.executemany("INSERT INTO data (type_id, value, date_added) VALUES (?, ?, ?)", values)
sqlite3.DatabaseError: database disk image is malformed
```

So it is permanently malformed? Do you suggest to try anything?

**Comment by slrslr** [comment]
@HelloZeroNet thank You for the attention. /Stats page indicate it is loading, but do not loads fully (i let it load around 20 minutes) and it shows Connections, Trackers and erroneous Tor service status, but no database statuses.

last debug.log lines:
[xx:14:53] Site:1iD5ZQ..duGz [OK] 187.34.228.***:14194: File not changed 8/3
[xx:15:45] - UiWSGIHandler error: DatabaseError: database disk image is malformed in UiServer.py line 40 > pywsgi.py line 495 > pywsgi.py line 484 > StatsPlugin.py line 174 > Db.py line 75 > DbCursor.py line 74

content.db file shows size of 20 megabytes on HDD. 1104 sites per ZeroHello

I tried to shut down ZN, deleted content.db and zerotalk .db and add line:
db_mode = security
into zeronet.conf on my Linux computer and started ZN. After like 35 minutes, while it was using very high memory causing lags to PC.

debug.log here: https://defuse.ca/b/txDJEWyFxQB7BDwwGUAWOW (password: zero ; can take a few seconds to decrypt)

So zeronet started and rebuilt the db, but ZeroTalk still do not show topics, showing its db is 20KB and rebuilding db not fix it. 

After shutdown ZN and started it, it is using normal memory, not excessive like during rebuilding of content.db
But i think on all zeronet sites, i can not participate, because i am getting error:
File write error: Forbidden, you can only modify your own files
And databases will probably fail rebuilding (or not rebuild) same as happened to me in zerotalk as mentioned above..

**Comment by slrslr** [comment]
Bump, this issue still exist, now i am on rev. rev3827
But this time, /Stats shows output you requested @HelloZeroNet :
Db:
- 0.041s: /media/volume2/ZeroNet/data/chart.db 164.080MB, table rows: {"data": 3004749, "json": 0, "keyvalue": 5, "site": 1289, "sqlite_sequence": 2, "type": 27}
- 0.019s: /media/volume2/ZeroNet/data/**content.db** 35.535MB, table rows: {"content": 2022, "file_optional": 183190, "json": 0, "keyvalue": 6, "peer": 47732, "site": 1289, "sqlite_sequence": 1}
- 0.000s: /media/volume2/ZeroNet/data/**1TaLk**FrMwvbNsooF4ioKAY9EuxTBTjipT/data/users/zerotalk.db 0.070MB, table rows: {"comment": 5, "comment_vote": 7, "json": 10, "keyvalue": 21, "sqlite_sequence": 2, "topic": 3, "topic_vote": 3}

i tried db_mode security and speed already.

**Comment by slrslr** [comment]
i am no longer using py2 zeronet.. issue is 1+ year old
