### ISSUE TITLE
KeyError self.content_manager.contents[inner_path]["modified"]

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1807]
rev3728
```
[12:27:12] Site:1N1Xdc..W92D [OK] 47.106.79.83:20184: File not changed 1/1
[12:28:07] Site:1White..1o51 [OK] 47.106.79.83:20184: File not changed 1/1
[12:29:24] Site:1UDbAD..MkoV [OK] 47.106.79.83:20184: File not changed 1/1
[12:32:19] - Unhandled exception
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/mnt/d/ZeroNet/core/src/Site/Site.py", line 487, in publisher
    content_json_modified = self.content_manager.contents[inner_path]["modified"]
  File "/mnt/d/ZeroNet/core/src/Content/ContentDbDict.py", line 61, in __getitem__
    return self.loadItem(key)
  File "/mnt/d/ZeroNet/core/src/Content/ContentDbDict.py", line 34, in loadItem
    raise KeyError(key)
KeyError: 'data/users/1Ce77AdELAi3thjyXvNxH5grWPzMhJehRa/content.json'
```

**Comment by blurHY** [comment]
@shortcutme
