### ISSUE TITLE
greenlet.py, worker.py - UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1924]
### Step 1: Please describe your environment

  * ZeroNet version: 3853
  * Operating system: W10
  * Web browser: FF
  * Tor status: available

### Step 2: Describe the problem:

The merger site is not loading content from hubs, so i taken a look into debug.log and found some errors that MAY be related:

```
[2019-03-19 05:12:43,224] DEBUG    WorkerManager:site..addresshere New task: galleries/something2: here/content.json, peer lock: None, priority: 1, optional_hash_id: None, tasks started: 16
[2019-03-19 05:12:43,272] DEBUG    WorkerManager:site..addresshere Timeout, Skipping: {'optional_hash_id': None, 'site': <Site site..addresshere>, 'done': False, 'size': 0, 'inner_path': u'galleries/some: name/content.json', 'peers': None, 'time_started': 1552988370.636, 'time_action': None, 'priority': 1, 'failed': [peershere], 'workers_num': 669, 'time_added': 1552988307.413, 'evt': <gevent.event.AsyncResult object at 0x18BE6F90>}
[2019-03-19 05:12:43,272] DEBUG    WorkerManager:site..addresshere iphere:port: Force skipping
[2019-03-19 05:12:43,272] DEBUG    WorkerManager:site..addresshere iphere:port: Force skipping
[2019-03-19 05:12:43,273] DEBUG    - Gevent block detected: 3.71600008011
[2019-03-19 05:12:43,681] DEBUG    WorkerManager:site..addresshere iphere:port: Verify correct: galleries/something1: here/content.json
[2019-03-19 05:12:43,683] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "site-packages\gevent\greenlet.py", line 536, in run
  File "C:\ZeroNet\core\src\Worker\Worker.py", line 108, in downloader
    self.manager.log.error("%s: Error writing: %s (%s)" % (self.key, task["inner_path"], err))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 13: ordinal not in range(128)
[2019-03-19 05:12:43,940] DEBUG    WorkerManager:site..addresshere iphere:port: Verify correct: galleries/something2: here/content.json
[2019-03-19 05:12:43,940] ERROR    - Unhandled exception
```

Isn't zeronet/plugin or/merger zite/hub having problem with ":" inside the name?
How this can be fixed and where?

https://duckduckgo.com/?q="UnicodeDecodeError%3A+'ascii'+codec+can't+decode+byte"

**Comment by ValdikSS** [comment]
Do you have your ZeroNet folder on the filesystem path with non-latin characters?

**Comment by slrslr** [comment]
Zeronet in my case is on NTFS drive and the path is C:\ZeroNet\, i am on WIndows 10.

**Comment by slrslr** [comment]
UnicodeDecodeError error also prevents the hub site to be deleted (still appears in zerohello site list after page reload):
`ERROR    - Unhandled exception: [(<type 'exceptions.UnicodeDecodeError'>, UnicodeDecodeError('ascii', "[Error 267] N\xe1zev adres\xe1re je neplatn: u'C:/ZeroNet/data/hubsiteaddress/directory/Text Here 2: Test Here'", 13, 14, 'ordinal not in range(128)'), <traceback object at 0x323E87D8>)]`

**Comment by HelloZeroNet** [comment]
Looks like it's because of the foreign-language error message
