### ISSUE TITLE
it is a problem -- using 43110 port on Linux

### ISSUE THREAD

**Issue by polymorphm** [HelloZeroNet/ZeroNet#1948]
## why?

because port range (on Linux by default) from 32768 upto 60999 used for **ephemeral port range** . for outgoing connections mostly and other getting dynamic port purposes.

see -- https://en.wikipedia.org/wiki/Ephemeral_port and https://www.ncftp.com/ncftpd/doc/misc/ephemeral_ports.html .

see sysctl on Arch Linux (all default settings):

```
$ sysctl net.ipv4.ip_local_port_range
net.ipv4.ip_local_port_range = 32768	60999
```

## what the problem with using a port from dynamic (ephemeral) range?

the problem is -- every time there is a chance (it is a low chance) that ZeroNet failes to start with some probability (it is a low probability).

there is a chance that ANY PORT from range 32768~60999 is **already busy**  (and you CAN NOT PREDICATE IT!) when you are starting a ZeroNet on 43110 port.

you could replace 43110 for example to 23110. it would solve conflict with ephemeral range!

## what if I use FreeBSD, not Linux?

in this case you have not problems. you can close the issue-ticket with ``WONTFIX``. and you could suggest to Linux-users to apply Barmin's patch on their computers.

FreeBSD follows IANA recommendations.

## 43110 is a legacy! we can not just change this to another port. all instructions are written to using 43110 port. all URLs are with port. how it could be changed now?!

you **should** to do port changing. you should to admit wrong port selecting was.

the early admit it, the less consequestions would be in long perpective.

today almost nobody knows about ZeroNet -- few people would suffer from port changing.

but tomorrow more people could be suffer from port changing.

## what the problem if the program starts successfully not every time? it is the low probability to fail! and failure doesn't happen on FreeBSD!

making or not making bugged software -- is philosophical questing. life is short. I would understand if you didn't want to fix it.

thanks in advance

**Comment by tangdou1** [comment]
write `ui_port = any number you like` in zeronet.conf file.

**Comment by HelloZeroNet** [comment]
Thanks for the info, is there any other application that uses this port range beside ftp servers?

**Comment by polymorphm** [comment]
> write ui_port = any number you like in zeronet.conf file.

it is issue about the default configuration. and therefore about all URLs that people share to each other.

not about individual (non-standard) configs

**Comment by polymorphm** [comment]
> is there any other known application that uses this port range beside ftp servers?

all applications that use outgoing tcp connections.

ssh (client), web-browser, DNS-client, e.t.c, *whatever that makes connection* ( IRC-chat-client and others...)...

if you don't understand what I mean, here it is an example:

the first application session:

```
[regular-user@plm-notebook ~]$ python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> sock = socket.create_connection(('google.com', 80))
>>> sock
<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.20.255.175', 44938), raddr=('216.58.211.110', 80)>
>>> 
```

the second application session:

```
[regular-user@plm-notebook ~]$ python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> serv_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
>>> serv_sock.bind(('0.0.0.0', 44938))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 98] Address already in use
>>> 
```

![Screenshot from 2019-04-04 12-37-56](https://user-images.githubusercontent.com/422741/55545818-b4557400-56d6-11e9-9268-392b0cae6edd.png)

the port ``44938`` (from the axample above) is like ``43110`` -- they both are from **ephemeral port range**.

**Comment by HelloZeroNet** [comment]
It can be a problem if someone want to bind it to "0.0.0.0", but by default we bind to "127.0.0.1", which does not affected by this problem:
```
>>> serv_sock.bind(('0.0.0.0', 58370))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 98] Address already in use
>>> serv_sock.bind(('127.0.0.1', 58370))
```

**Comment by polymorphm** [comment]
> It can be a problem if someone want to bind it to "0.0.0.0", but by default we bind to "127.0.0.1", which does not affected by this problem:

hmm... you are right, partly..

sorry for confusion. not all those programs I mentied *could* create a problem.

not any outgoing connection makes a problem. sorry again, please.

but problem of using of port 43110 (ephemeral port range) **still exists**.. (but for **less** count of cases).

if any outgoing tcp connection that makes connection to 127.0.0.1 (CUPS-server, TOR-server, i2p-server, Ethereum any web-ui server, etc., .... ... ...).

example:

the first application session:

```
[regular-user@plm-notebook ~]$ python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> sock = socket.create_connection(('127.0.0.1', 631)) # CUPS server
>>> sock
<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53722), raddr=('127.0.0.1', 631)>
>>> 
```

the second application session:

```
[regular-user@plm-notebook ~]$ python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> serv_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
>>> serv_sock.bind(('0.0.0.0', 53722))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 98] Address already in use
>>> serv_sock.bind(('127.0.0.1', 53722))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 98] Address already in use
>>> 
```
