### ISSUE TITLE
Two TypeError after upgrade to py3

### ISSUE THREAD

**Issue by krzotr** [HelloZeroNet/ZeroNet#1980]
### Step 1: Please describe your environment

  * ZeroNet version: **py3 - Rev4059** - **Python 3.6.6**
  * Operating system: **Centos 7**
  * Web browser: **Chrome 73**
  * Tor status: **enabled**
  * Opened port: **yes**
  * Special configuration: 
```
[global]
fileserver_ip_type=ipv4
log_dir=/zeronet/log
data_dir=/zeronet/data
fileserver_port=26552
fileserver_ip=0.0.0.0
use_openssl=true
ui_ip=127.0.0.1
download_optional=auto
ui_trans_proxy
autodownload_bigfile_size_limit = 5000
bigfile_size_limit = 5000
workers=15
connected_limit=20
global_connected_limit=2048
optional_limit=1000
```

### Step 2: Describe the problem:

I have two identical environments - the same version of Python, Zeronet, the same OS. On one of them, I have a huge number of sites and a huge number of `Optional Files` - On that machine, I see errors in console/log file.

At the moment I do not see any unexpected problems. Maybe something is wrong with downloading or saving files - I do not know.

#### Steps to reproduce:

I do not know how to reproduce - I tried a fresh instance of ZeroNet and download, redownload `Optional Files` - no results.
I see errors in the log file and in the console after upgrade to py3 branch.

#### Observed Results:

After upgrade to py3, I see two types of errors
- Error1 - `TypeError: ljust() argument 2 must be a byte string of length 1, not str`
- Error2 - `TypeError: can't concat str to bytes`

In both log files, I get one line before and after.
What I see, before error function has triggered `Downloaded optional file in 1.582s, adding to hashfield`

##### Error 1
```
[09:44:28] - Unhandled exception: [(<class 'TypeError'>, TypeError('ljust() argument 2 must be a byte string of length 1, not str',), <traceback object at 0x7fa087c501c8>)]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/zeronet/zeronet-py3/src/Worker/Worker.py", line 122, in downloader
    self.manager.doneTask(task)
  File "/home/zeronet/zeronet-py3/plugins/OptionalManager/OptionalManagerPlugin.py", line 145, in doneTask
    super(WorkerManagerPlugin, self).doneTask(task)
  File "/home/zeronet/zeronet-py3/src/Worker/WorkerManager.py", line 553, in doneTask
    self.site.content_manager.optionalDownloaded(task["inner_path"], task["optional_hash_id"], task["size"])
  File "/home/zeronet/zeronet-py3/plugins/OptionalManager/OptionalManagerPlugin.py", line 72, in optionalDownloaded
    return super(ContentManagerPlugin, self).optionalDownloaded(inner_path, hash_id, size, own)
  File "/home/zeronet/zeronet-py3/plugins/Bigfile/BigfilePlugin.py", line 364, in optionalDownloaded
    self.site.storage.piecefields[file_info["sha512"]][piece_i] = True
  File "/home/zeronet/zeronet-py3/plugins/Bigfile/BigfilePiecefield.py", line 74, in __setitem__
    data = data.ljust(key + 1, "0")
TypeError: ljust() argument 2 must be a byte string of length 1, not str
```

[log1.txt](https://github.com/HelloZeroNet/ZeroNet/files/3075888/log1.txt)

### Error 2
```
[10:01:31] - Unhandled exception: [(<class 'TypeError'>, TypeError("can't concat str to bytes",), <traceback object at 0x7fa0ac56eb48>)]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/zeronet/zeronet-py3/src/Worker/Worker.py", line 122, in downloader
    self.manager.doneTask(task)
  File "/home/zeronet/zeronet-py3/plugins/OptionalManager/OptionalManagerPlugin.py", line 145, in doneTask
    super(WorkerManagerPlugin, self).doneTask(task)
  File "/home/zeronet/zeronet-py3/src/Worker/WorkerManager.py", line 553, in doneTask
    self.site.content_manager.optionalDownloaded(task["inner_path"], task["optional_hash_id"], task["size"])
  File "/home/zeronet/zeronet-py3/plugins/OptionalManager/OptionalManagerPlugin.py", line 72, in optionalDownloaded
    return super(ContentManagerPlugin, self).optionalDownloaded(inner_path, hash_id, size, own)
  File "/home/zeronet/zeronet-py3/plugins/Bigfile/BigfilePlugin.py", line 364, in optionalDownloaded
    self.site.storage.piecefields[file_info["sha512"]][piece_i] = True
  File "/home/zeronet/zeronet-py3/plugins/Bigfile/BigfilePiecefield.py", line 75, in __setitem__
    data = data[:key] + str(int(value)) + data[key + 1:]
TypeError: can't concat str to bytes
```

[log2.txt](https://github.com/HelloZeroNet/ZeroNet/files/3075890/log2.txt)

**Comment by radfish** [comment]
Try with PR #1982

**Comment by krzotr** [comment]
After applying your patch I got a different error when I visit `Files` page on `ZeroHello` - http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/?Files

```
[2019-04-13 23:32:42,706] ERROR    Site:1HeLLo..Tf3D WebSocket handleRequest error: TypeError: a bytes-like object is required, not 'str' in UiWebsocket.py line 84 > UiWebsocket.py line 268 > OptionalManager/UiWebsocketPlugin.py line 159 > OptionalManager/UiWebsocketPlugin.py line 69
 {"cmd":"optionalFileList","params":{"address":"all","filter":"downloaded,bigfile","limit":101,"orderby":"time_downloaded DESC"},"wrapper_nonce":"2b75b784dd3abdda0513148948c987b5e4bd96b3c902f273bcf755cda1a99241","id":91}
```

**Comment by radfish** [comment]
#krzotr Looks like I missed one more place. Pushed again. Please re-merge and retry. Thanks. I tried with ZeroUp bigfiles and Files tab appears to work.

**Comment by krzotr** [comment]
@radfish After 16 hours of running ZeroNet with your patch I can confirm - I do not see both errors.

Your patch solved `TypeError` errors which I described in this ticket.

**Comment by radfish** [comment]
#1982 merged. @krzotr please close if all good. Thanks.
