### ISSUE TITLE
Unable to launch zeronet on Linux Ubuntu Arm with 

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2002]
### Step 1: Please describe your environment

  * ZeroNet version: ? can not launch Zeronet
  * Operating system: Ubuntu 16.04 ARM kernel 4.9.160-armada375
  * Web browser: FF

### Step 2: Describe the problem:

I have downloaded Zeronet yesterday from https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz
And after trying to u[nsuccessfuly install gevent](https://github.com/pypa/pip/issues/6454), i tried to launch zeronet:

```python zeronet.py
- Starting ZeroNet...
ERROR:root:Unhandled exception: The 'cffi>=1.11.5' distribution was not found and is required by the application
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/home/ZeroNet-master/src/main.py", line 13, in <module>
    monkey.patch_all(thread=False, subprocess=False)
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 966, in patch_all
    _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 168, in _notify_patch
    notify_and_call_entry_points(event)
  File "/usr/local/lib/python2.7/dist-packages/gevent/events.py", line 112, in notify_and_call_entry_points
    subscriber = plugin.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'cffi>=1.11.5' distribution was not found and is required by the application
Traceback (most recent call last):
  File "zeronet.py", line 88, in <module>
    main()
  File "zeronet.py", line 53, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'
```

Python 2.7.11+
pip 19.1

I have really basic experience about Linux so do not know how to fix python, pip issue. Can you please help me tell which commands to run?

**Comment by HelloZeroNet** [comment]
please try to run `sudo python -m pip install -U cffi gevent`
if it does not fixes the problem then whats the input for `python -m pip list | grep -E "cffi|gevent|greenlet"`?

**Comment by slrslr** [comment]
The first command fails with [error: ffi.h: No such file or directory](https://pastebin.com/uGcqG8c6)
The output of the second command is:
gevent         1.4.0
greenlet       0.4.15
Then i tried to install yours mentioned packages: "apt install python-gevent python-msgpack"
result:
```
Setting up python-msgpack (0.4.6-1build1) ...
Setting up python-greenlet (0.4.9-2fakesync1) ...
Setting up python-gevent (1.1.0-2) ...
```
complete.
Zeronet seem to continue failing to start with same error as mentioned in the initial post ("Unhandled exception: The 'cffi>=1.11.5' distribution was not found and is required").

**Comment by HelloZeroNet** [comment]
`sudo apt-get install libffi-dev` should fix the ffi.h error

**Comment by slrslr** [comment]
> sudo apt-get install libffi-dev

Setting up libffi-dev:armhf (3.2.1-4) ...

tried to run "python zeronet.py" with same (error) result like i quoted before ("The 'cffi>=1.11.5' distribution was not found and is required")

yours mentioned command `python -m pip list | grep -E "cffi|gevent|greenlet"` does not list cffi. Please what to try?

**Comment by slrslr** [comment]
UPDATE: i tried command "apt-get install python-cffi", it installed:
```
Setting up python-cffi-backend (1.5.2-1ubuntu1) ...
Setting up python-ply (3.7-1) ...
Setting up python-pycparser (2.14+dfsg-2build1) ...
Setting up python-cffi (1.5.2-1ubuntu1) ...
```

And python -m pip list shows "cffi 1.5.2"

The "python zeronet.py" now fails with error: "ERROR:root:Unhandled exception: (cffi 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('cffi>=1.11.5'))"

**Comment by slrslr** [comment]
UPDATE2: i then tried "pip install cffi -U" it said:
Successfully uninstalled cffi-1.5.2
Successfully installed cffi-1.12.3
Zeronet then started, web page shows "Opened as child-window, stopping..."
@HelloZeroNet i am wondering what went wrong that this zeronet setup was so complicated, how this can be fixed? And what are minimum necessary commands that were required. I think this time it was beyond steps described at https://zeronet.io/docs/using_zeronet/installing/

**Comment by HelloZeroNet** [comment]
I think the apt contains old version of cffi that is not compatible with latest version of gevent:

Option A: Try install the latest cffi with `python -m pip install cffi`
Option B: try remove the pip version of gevent with `python -m pip uninstall gevent` and install it with `apt install python-gevent`

**Comment by imachug** [comment]
@slrslr What is the state of this issue? Have you resolved it? Looks like you've upvoted the latest @HelloZeroNet's comment, but that was the only way you've reacted.
