### ISSUE TITLE
Can not recognize gevent and says "ImportError: No module named sysconfig"

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2014]
Today, i have downloaded zeronet master package (i think revision 3864) to my Linux CentOS 6.10 but it complains about gevent:

```
[root@0 ZeroNet-master]# easy_install gevent
Searching for gevent
Best match: gevent 1.1rc3
Adding gevent 1.1rc3 to easy-install.pth file

Using /usr/lib64/python2.6/site-packages
Processing dependencies for gevent
Finished processing dependencies for gevent

[root@0 ZeroNet-master]# python2.7 zeronet.py
- Starting ZeroNet...
ERROR:root:Unhandled exception: No module named gevent
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/home/ZeroNet-master/src/main.py", line 9, in <module>
    import gevent
ImportError: No module named gevent
Traceback (most recent call last):
  File "zeronet.py", line 88, in <module>
    main()
  File "zeronet.py", line 53, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'

[root@0 ZeroNet-master]# which pip
/usr/bin/pip

[root@0 ZeroNet-master]# /usr/bin/pip install gevent
You are using pip version 7.1.0, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): gevent in /usr/lib64/python2.6/site-packages
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.9 in /usr/lib64/python2.6/site-packages (from gevent)

[root@0 ZeroNet-master]# /usr/bin/pip install gevent --upgrade
You are using pip version 7.1.0, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting gevent
  Using cached https://files.pythonhosted.org/packages/ed/27/6c49b70808f569b66ec7fac2e78f076e9b204db9cf5768740cff3d5a07ae/gevent-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/root/tmp/pip-build-mgqKsV/gevent/setup.py", line 7, in <module>
        import sysconfig
    ImportError: No module named sysconfig

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /root/tmp/pip-build-mgqKsV/gevent
```

**Comment by BaRRaKudaRain** [comment]
Hmm... Maybe I'm not right, but I think you should try python3.

-----Original Message-----

**Comment by slrslr** [comment]
I tried to installe python 3 (aside of python 2), but that ended in error.

During install:
```
"Could not build the ssl module!
Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().
LibreSSL 2.6.4 and earlier do not provide the necessary APIs, https://github.com/libressl-portable/portable/issues/381"
```

At the end:
[check here](https://pastebin.com/Y4N6KYc7)

**Comment by BaRRaKudaRain** [comment]
And pip3 to install dependencies.

-----Original Message-----

**Comment by slrslr** [comment]
@BaRRaKudaRain as already shown, python installation failed and i can not find a fix. And pip also fails (possibly as a result):

```
# /usr/local/bin/python3.8 get-pip.py
/tmp/tmpqi_nqf5f/pip.zip/pip/_vendor/ipaddress.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
/tmp/tmpqi_nqf5f/pip.zip/pip/_vendor/ipaddress.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
Traceback (most recent call last):
  File "get-pip.py", line 21492, in <module>
    main()
  File "get-pip.py", line 197, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip._internal
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpqi_nqf5f/pip.zip/pip/_internal/__init__.py", line 40, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpqi_nqf5f/pip.zip/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpqi_nqf5f/pip.zip/pip/_internal/cli/main_parser.py", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpqi_nqf5f/pip.zip/pip/_internal/commands/__init__.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpqi_nqf5f/pip.zip/pip/_internal/commands/completion.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpqi_nqf5f/pip.zip/pip/_internal/cli/base_command.py", line 20, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpqi_nqf5f/pip.zip/pip/_internal/download.py", line 37, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpqi_nqf5f/pip.zip/pip/_internal/utils/glibc.py", line 3, in <module>
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

```

**Comment by HelloZeroNet** [comment]
Please try to install gevent using `python -m pip install gevent`

Have you tried to install python3 from yum or compiled it from source code?

**Comment by slrslr** [comment]
@HelloZeroNet 

[root@0 /]# python -m pip install gevent
/usr/bin/python: pip is a package and cannot be directly executed
[root@0 /]# python3.8 -m pip install gevent
/usr/local/bin/python3.8: No module named pip

No, yum on CentoS 6.x does not have and will not have python3, so in my case i have it compilled from source, though during the process it shown errors as i described and linked 2 comments up in this issue.

**Comment by HelloZeroNet** [comment]
You need to download the openssl source code to compile the module: http://zhang-jc.github.io/2018/11/27/CentOS-6-8-安装-Python3-Could-not-build-the-ssl-module/

There is also a binary for Linux that includes the dependencies: https://github.com/HelloZeroNet/ZeroBundle/raw/master/dist/ZeroBundle-linux64.tar.gz

**Comment by slrslr** [comment]
i installed latest OpenSSL_1_1_1b following steps mentioned on yours linked page.
and then compilled, installed python 3 again with same errors:

```
Could not build the ssl module!
Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().
LibreSSL 2.6.4 and earlier do not provide the necessary APIs, https://github.com/libressl-portable/portable/issues/381

Failed to build these modules:
_ctypes

ModuleNotFoundError: No module named '_ctypes'
make: *** [altinstall] Error 1
```

as i do not know how else to install, i tried that zerobundle and that worked.

I see on https://github.com/HelloZeroNet/ZeroNet#user-content-how-to-join is suggested mainly the bundle package, except for the Debian linux where is suggested "-master" package.
