### ISSUE TITLE
ImportError: bad magic number in 'bencode': b'\x03\xf3\r\n' in PluginManager.py line 58

### ISSUE THREAD

**Issue by 6543** [HelloZeroNet/ZeroNet#2102]
### Step 1: Please describe your environment

  * ZeroNet version: py3 Rev4129
  * Operating system: linux52
  * Web browser: X
  * Tor status: always
  * Opened port: no
  * Special configuration: ____

### Step 2: Describe the problem:

dont start on branch py3; master works fine; complete new py3 works also but then all user data is gone :(

#### Steps to reproduce:

  1. start

#### Observed Results:

[user@pc ZeroNet]$ python3 zeronet.py

```
- Starting ZeroNet...
[02:44:13] PluginManager Plugin AnnounceBitTorrent load error: ImportError: bad magic number in 'bencode': b'\x03\xf3\r\n' in PluginManager.py line 58 > AnnounceBitTorrent/__init__.py line 1 > AnnounceBitTorrent/AnnounceBitTorrentPlugin.py line 6
[02:44:13] PluginManager Plugin Bigfile load error: ImportError: bad magic number in 'merkletools': b'\x03\xf3\r\n' in PluginManager.py line 58 > Bigfile/__init__.py line 1 > Bigfile/BigfilePlugin.py line 20
[02:44:13] - Libsecpk256k1 loaded: CompiledLib in 0.035s
[02:44:13] - Unhandled exception: bad magic number in 'geventwebsocket': b'\x03\xf3\r\n'
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/data/local/ZeroNet/src/main.py", line 63, in <module>
    PluginManager.plugin_manager.loadPlugins()
  File "/data/local/ZeroNet/src/Plugin/PluginManager.py", line 67, in loadPlugins
    func()
  File "/data/local/ZeroNet/plugins/UiConfig/UiConfigPlugin.py", line 14, in importPluginnedClasses
    from Ui import UiWebsocket
  File "/data/local/ZeroNet/src/Ui/__init__.py", line 1, in <module>
    from .UiServer import UiServer
  File "/data/local/ZeroNet/src/Ui/UiServer.py", line 10, in <module>
    from geventwebsocket.handler import WebSocketHandler
ImportError: bad magic number in 'geventwebsocket': b'\x03\xf3\r\n'
---
```

**Comment by 6543** [comment]
```
rm -f -r tools/ src/ plugins/
git checkout py3 -f
./zeronet.py  &
```
