### ISSUE TITLE
python3 -m pip install: 

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2109]
### Step 1: Please describe your environment

  * Operating system: Debian 9 Stretch for ARM, 32bit (soyoustart_com, ohv kernel)

### Step 2: Describe the problem:

The readme.md page says that following command should be used when installing zeronet on Linux:

sudo python3 -m pip install -r requirements.txt

and i ends in error on Debian 9 stretch ARM 32bit:

`root@0:/home/ZeroNet-py3# sudo python3 -m pip install -r requirements.txt
Collecting gevent>=1.1.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ed/27/6c49b70808f569b66ec7fac2e78f076e9b204db9cf5768740cff3d5a07ae/gevent-1.4.0.tar.gz (5.2MB)
    100% |################################| 5.2MB 33kB/s
  Ignoring cffi: markers 'sys_platform == "win32" and platform_python_implementation == "CPython"' don't match your environment
Collecting msgpack>=0.4.4 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/81/9c/0036c66234482044070836cc622266839e2412f8108849ab0bfdeaab8578/msgpack-0.6.1.tar.gz (118kB)
    100% |################################| 122kB 1.1MB/s
Collecting base58 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/09/b2/21ac9591f055acc145afead895edeb73bbd69d95cf366fc5c2233f2434cb/base58-1.0.3-py3-none-any.whl
Collecting merkletools (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/dc/b8/655f9be691387746957834fce8634a827497c62d306b09b557d2970a2672/merkletools-1.0.3.tar.gz
Collecting pyelliptic==1.5.6 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/e6/64/b235f8768dd37891acc924f724e7fd46921063da65e759f8123c6b0b42e9/pyelliptic-1.5.6.tar.gz
Collecting rsa (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting PySocks (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/cd/18/102cc70347486e75235a29a6543f002cf758042189cb063ec25334993e36/PySocks-1.7.0-py3-none-any.whl
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 8))
Collecting websocket_client (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl (200kB)
    100% |################################| 204kB 747kB/s
Collecting gevent-websocket (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/7b/84/2dc373eb6493e00c884cc11e6c059ec97abae2678d42f06bf780570b0193/gevent_websocket-0.10.1-py3-none-any.whl
Collecting bencode.py (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/98/d8/84d31b911a7cab865ec9070a982b9452b15db00373efcf1e4b4314a6a958/bencode.py-2.1.0-py2.py3-none-any.whl
Collecting coincurve (from -r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/4f/4b/c1c0aaa3a09d21e08de158f25e69134ea4b6563a8d5aee8d99e5f3e3447b/coincurve-12.0.0.tar.gz (948kB)
    100% |################################| 952kB 166kB/s
    Complete output from command python setup.py egg_info:
    /usr/lib/python3.5/distutils/dist.py:261: **UserWarning**: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    warning: no files found matching 'NOTICE'
    warning: no files found matching 'requirements.txt'

    Installed /tmp/pip-build-_3eshne2/coincurve/.eggs/requests-2.22.0-py3.5.egg
    Searching for cffi>=1.3.0
    Reading https://pypi.python.org/simple/cffi/
    Downloading https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz#sha256=041c81822e9f84b1d9c401182e174996f0bae9991f33725d059b771744290774
    Best match: cffi 1.12.3
    Processing cffi-1.12.3.tar.gz
    Writing /tmp/easy_install-0s0xymwt/cffi-1.12.3/setup.cfg
    Running cffi-1.12.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0s0xymwt/cffi-1.12.3/egg-dist-tmp-_1autbm2
    c/_cffi_backend.c:15:17: **fatal error**: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
        self.run_command(cmdname)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
        self.build()
      File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-0s0xymwt/cffi-1.12.3/setup.py", line 248, in <module>

      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1131, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 258, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-0s0xymwt/cffi-1.12.3/setup.py", line 248, in <module>

      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_3eshne2/coincurve/setup.py", line 297, in <module>
        **setup_kwargs
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 699, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 725, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 906, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1145, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1133, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_3eshne2/coincurve/
root@0:/home/ZeroNet-py3# uname -a
Linux 0.net.sys 4.5.2-armada375 #1 SMP Tue Oct 25 11:52:56 CEST 2016 armv7l GNU/Linux`

I have only less than 48 hours on this server as it is expiring.

**Comment by HelloZeroNet** [comment]
please try to run `sudo apt-get install libffi-dev` before the install

**Comment by slrslr** [comment]
i just did that, though still there remains some errors in mentioned python3 installation command.
```
    pkg_resources.VersionConflict: (idna 2.2 (/usr/lib/python3/dist-packages), Requirement.parse('idna<2.9,>=2.5'))

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3f43vj01/coincurve/
```

full output [here](https://pastebin.com/6BAhczCV)

**Comment by stbinan** [comment]
@slrslr you need to install the build dependencies from https://github.com/ofek/coincurve#installation

**Comment by HelloZeroNet** [comment]
try execute `python3 -m pip install -U idna` to update the idna package. (not sure why it's not updating itself)

**Comment by slrslr** [comment]
Thank you both for your comments.

> python3 -m pip install -U idna

```
  Found existing installation: idna 2.2
    Not uninstalling idna at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed idna-2.8
```

then "sudo python3 -m pip install -r requirements.txt" ended with:
```
  make[1]: Leaving directory '/tmp/pip-build-hrwor413/coincurve/build/temp.linux-armv7l-3.5'
  error: [Errno 2] No such file or directory: 'pkg-config'

  ----------------------------------------
  Failed building wheel for coincurve
  Running setup.py clean for coincurve
  Running setup.py bdist_wheel for maxminddb ... done
  Stored in directory: /root/.cache/pip/wheels/58/60/71/9d07e2c0999b13b1f3ca3e2167a3436209e24d7f4ef6e8f919
  Running setup.py bdist_wheel for greenlet ... done
  Stored in directory: /root/.cache/pip/wheels/cc/28/5a/2687513046a61b17dd78be058a43a069c271f5d7b7623f3dfd
  Running setup.py bdist_wheel for pysha3 ... done
  Stored in directory: /root/.cache/pip/wheels/fc/85/47/c492f6f4029f9e8d264c23c7ba49f894d5e61589a177b1747a
  Running setup.py bdist_wheel for cffi ... done
  Stored in directory: /root/.cache/pip/wheels/94/a7/7a/9782ab473d88ec2d4994a7dd2d006b1352c71da3ad34ebcaeb
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built gevent msgpack merkletools pyelliptic maxminddb greenlet pysha3 cffi pycparser
Failed to build coincurve
Installing collected packages: greenlet, gevent, msgpack, base58, pysha3, merkletools, pyelliptic, rsa, PySocks, websocket-client, gevent-websocket, bencode.py, asn1crypto, pycparser, cffi, coincurve, python-bitcoinlib, maxminddb
  Found existing installation: greenlet 0.4.11
    Not uninstalling greenlet at /usr/lib/python3/dist-packages, outside environment /usr
  Running setup.py install for coincurve ... -
Using username "root".

```

But fortunately what mentioned @stbinan worked:

> you need to install the build dependencies from https://github.com/ofek/coincurve#installation

I am not sure what these are, so i seen the list of some packages on the linked page so i did:
sudo apt-get install build-essential automake pkg-config libtool libffi-dev python3-dev libgmp-dev

> The following NEW packages will be installed:
>   autoconf automake autotools-dev libgmp-dev libgmpxx4ldbl libltdl-dev libltdl7 libsigsegv2 libtool m4 pkg-config
> 0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.

then, the "sudo python3 -m pip install -r requirements.txt" command succeeded apparently:

> Building wheels for collected packages: coincurve
>   Running setup.py bdist_wheel for coincurve ... done
>   Stored in directory: /root/.cache/pip/wheels/28/6f/63/4047b855e41032bb148fc49ca057bcd3f5a021797041ca8a21
> Successfully built coincurve
> Installing collected packages: coincurve, python-bitcoinlib, maxminddb
> Successfully installed coincurve-12.0.0 maxminddb-1.4.1 python-bitcoinlib-0.10.1
> root@0:/home/ZeroNet-py3#

zeronet starts without errors. So @HelloZeroNet can anything be done so other people that will try to install zeronet on ARM (Debian 9 32bit) do not face complications like me?
