### ISSUE TITLE
Cannot start on termux

### ISSUE THREAD

**Issue by Merith-TK** [HelloZeroNet/ZeroNet#2110]
### Step 1: Please describe your environment

  * ZeroNet version: `git clone`
  * Operating system: Android 8.1 termux
  * Web browser: n/a
  * Tor status: not available/
  * Opened port: n/a
  * Special configuration: termux

### Step 2: Describe the problem:
i used a script to make zn work under termux
https://github.com/WillyPillow/Termux-ZeroNet

I hsve forked it and updated it to work with newer termux and zn versions
https://github.com/Merith-TK/Termux-ZeroNet

```bash
$ python zeronet.py
- Starting ZeroNet...
[15:47:45] PluginManager Plugin AnnounceBitTorrent load error: ModuleNotFoundError: No module named 'bencode' in PluginManager.py line 58 > AnnounceBitTorrent/__init__.py line 1 > AnnounceBitTorrent/AnnounceBitTorrentPlugin.py line 6
[15:47:45] PluginManager Plugin Bigfile load error: ModuleNotFoundError: No module named 'merkletools' in PluginManager.py line 58 > Bigfile/__init__.py line 1 > Bigfile/BigfilePlugin.py line 20
[15:47:45] - Libsecp256k1 load failed: No module named 'coincurve', try to load OpenSSL
[15:47:45] - OpenSSL load failed: No module named 'bitcoin', falling back to slow bitcoin verify
[15:47:45] - Unhandled exception: No module named 'geventwebsocket'
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/data/data/com.termux/files/home/ZeroNet/src/main.py", line 63, in <module>
    PluginManager.plugin_manager.loadPlugins()
  File "/data/data/com.termux/files/home/ZeroNet/src/Plugin/PluginManager.py", line 67, in loadPlugins
    func()
  File "/data/data/com.termux/files/home/ZeroNet/plugins/UiConfig/UiConfigPlugin.py", line 14, in importPluginnedClasses
    from Ui import UiWebsocket
  File "/data/data/com.termux/files/home/ZeroNet/src/Ui/__init__.py", line 1, in <module>
    from .UiServer import UiServer
  File "/data/data/com.termux/files/home/ZeroNet/src/Ui/UiServer.py", line 10, in <module>
    from geventwebsocket.handler import WebSocketHandler
ModuleNotFoundError: No module named 'geventwebsocket'
---
Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md
```
#### Steps to reproduce:
 Unknown

**Comment by HelloZeroNet** [comment]
You need to replace the `EMBED=0 pip install gevent msgpack-python` with `EMBED=0 pip install -r requirements.txt` to install all necessary modules.

**Comment by imachug** [comment]
@HelloZeroNet Closing?
