### ISSUE TITLE
"No JSON object could be decoded" needs to say what file caused the problem

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#2125]
Some file became corrupt, but this error message didn't tell what file this is:
```
[11:10:22] - Unhandled exception: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/share/zeronet/zeronet.py", line 19, in main
    main.start()
  File "/usr/local/share/zeronet/src/main.py", line 508, in start
    actions.call(config.action, action_kwargs)
  File "/usr/local/share/zeronet/src/main.py", line 119, in call
    back = func(**kwargs)
  File "/usr/local/share/zeronet/src/main.py", line 131, in main
    ui_server = UiServer()
  File "/usr/local/share/zeronet/src/Ui/UiServer.py", line 83, in __init__
    self.sites = SiteManager.site_manager.list()
  File "/usr/local/share/zeronet/src/Site/SiteManager.py", line 171, in list
    self.load(startup=True)
  File "/usr/local/share/zeronet/plugins/Zeroname/SiteManagerPlugin.py", line 20, in load
    super(SiteManagerPlugin, self).load(*args, **kwargs)
  File "/usr/local/share/zeronet/plugins/MergerSite/MergerSitePlugin.py", line 379, in load
    super(SiteManagerPlugin, self).load(*args, **kwags)
  File "/usr/local/share/zeronet/plugins/ContentFilter/ContentFilterPlugin.py", line 21, in load
    super(SiteManagerPlugin, self).load(*args, **kwargs)
  File "/usr/local/share/zeronet/plugins/Chart/ChartPlugin.py", line 21, in load
    back = super(SiteManagerPlugin, self).load(*args, **kwargs)
  File "/usr/local/share/zeronet/src/Site/SiteManager.py", line 35, in load
    for address, settings in json.load(open("%s/sites.json" % config.data_dir)).iteritems():
  File "/usr/local/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
- Starting ZeroNet...
```

**Comment by HelloZeroNet** [comment]
based on the `    for address, settings in json.load(open("%s/sites.json" % config.data_dir)).iteritems():` line It's the data/sites.json file

**Comment by yurivict** [comment]
> based on the for address, settings in json.load(open("%s/sites.json" % config.data_dir)).iteritems(): line It's the data/sites.json file


I figured this out, thanks -)

It should print the file name so it would be clear from the message.

**Comment by HelloZeroNet** [comment]
It should be more clean now: https://github.com/HelloZeroNet/ZeroNet/commit/6cd18bbf04c98059dba12244c26831c25b0c3538
