### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by User-Hrsat** [HelloZeroNet/ZeroNet#2142]
➜  ZeroNet git:(py3) python zeronet.py 
- Starting ZeroNet...
[21:03:14] PluginManager Plugin AnnounceBitTorrent load error: ModuleNotFoundError: No module named 'bencode' in PluginManager.py line 138 > AnnounceBitTorrent/__init__.py line 1 > AnnounceBitTorrent/AnnounceBitTorrentPlugin.py line 6
[21:03:14] PluginManager Plugin Bigfile load error: ModuleNotFoundError: No module named 'merkletools' in PluginManager.py line 138 > Bigfile/__init__.py line 1 > Bigfile/BigfilePlugin.py line 20
[21:03:15] Db:Chart Table keyvalue outdated...version: False need: 1, rebuilding...
[21:03:15] Db:Chart Table json outdated...version: 0 need: 1, rebuilding...
[21:03:15] Db:Chart Table data outdated...version: 0 need: 2, rebuilding...
[21:03:15] Db:Chart Table type outdated...version: 0 need: 1, rebuilding...
[21:03:15] Db:Chart Table site outdated...version: 0 need: 1, rebuilding...
[21:03:15] - Libsecp256k1 load failed: No module named 'coincurve', try to load OpenSSL
[21:03:15] - OpenSSL load failed: No module named 'bitcoin', falling back to slow bitcoin verify
[21:03:15] - Unhandled exception: No module named 'geventwebsocket'
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    import main
  File "/home/hrsat/Trings/ZeroNet/src/main.py", line 63, in <module>
    PluginManager.plugin_manager.loadPlugins()
  File "/home/hrsat/Trings/ZeroNet/src/Plugin/PluginManager.py", line 147, in loadPlugins
    func()
  File "/home/hrsat/Trings/ZeroNet/plugins/UiConfig/UiConfigPlugin.py", line 17, in importPluginnedClasses
    from Ui import UiWebsocket
  File "/home/hrsat/Trings/ZeroNet/src/Ui/__init__.py", line 1, in <module>
    from .UiServer import UiServer
  File "/home/hrsat/Trings/ZeroNet/src/Ui/UiServer.py", line 10, in <module>
    from geventwebsocket.handler import WebSocketHandler
ModuleNotFoundError: No module named 'geventwebsocket'
---
Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md

**Comment by imachug** [comment]
Have you installed ZeroNet correctly? It looks like if you're using ZeroNet from source, but you haven't installed the dependencies. Running `python -m pip install -r requirements.txt` from ZeroNet directory should work.

**Comment by User-Hrsat** [comment]
I will try again. Thank you for help.! 


And I lost the "user.json" file for a long time. 


Anyone who know how to restore user identity without that file? 



On Tue, Aug 13, 2019 at 9:47 PM +0800, "Ivanq" <notifications@github.com> wrote:












Have you installed ZeroNet correctly? It looks like if you're using ZeroNet from source, but you haven't installed the dependencies. Running python -m pip install -r requirements.txt from ZeroNet directory should work.

**Comment by imachug** [comment]
It's impossible to recover the account unless you have at least a part of users.json.

**Comment by purplesyringa** [comment]
@HelloZeroNet This issue can be closed.
