### ISSUE TITLE
Unhandled exception <ContentDbPlugin.py loadFilesOptional KeyError> on siteNeedFile cmd start

### ISSUE THREAD

**Issue by peter-tank** [HelloZeroNet/ZeroNet#2145]
---
name: Bug report
about: Create a report to help us improve ZeroNet
title: 'Unhandled exception <ContentDbPlugin.py loadFilesOptional KeyError> on siteNeedFile only from cmdline.'
labels: 'siteNeedFile, cmdline'
assignees: ''

---

### Step 1: Please describe your environment

  * ZeroNet version: rev4176
  * Operating system: centos6
  * Web browser: None
  * Tor status: disabled
  * Opened port: yes
  * Special configuration: None

#### Steps to reproduce:

  1. excuted from shell `python3.7 ./zeronet.py --silent --log_level ERROR siteNeedFile "<source_site_address>" "<site_file_path>"`.

#### Observed Results:

  * start zeronet siteNeedFile cmd, exceptions not on each run:
    > - Unhandled exception: [(<class 'KeyError'>, KeyError('1BwWMbqLbQPks7s1DN3d3zLEkMXvJqQijP'), <traceback object at 0x7f587062cc80>)]
    > Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/root/zeronet/ZeroNet-py3/plugins/OptionalManager/ContentDbPlugin.py", line 97, in loadFilesOptional
    site = self.sites[site_address]
KeyError: '1BwWMbqLbQPks7s1DN3d3zLEkMXvJqQijP'

#### Expected Results:

  * No such error.

**Comment by peter-tank** [comment]
Seems got fixed by recent commits between rev4188 and rev4191.
Have no idea how it's working, maybe: https://github.com/HelloZeroNet/ZeroNet/commit/248fc5f015f846a868b8d1c8168842878151e66d

**Comment by peter-tank** [comment]
resolved after update to: https://github.com/HelloZeroNet/ZeroNet/commit/f5829f60122bd1ea25a92be142820091194e136d
