### ISSUE TITLE
UnicodeDecodeError when start ZeroNet.

### ISSUE THREAD

**Issue by bufgix** [HelloZeroNet/ZeroNet#2180]
### Step 1: Please describe your environment

  * ZeroNet version:  0.7.0 r4197
  * Python version: 3.6.7
  * Operating system: Windows 10 x64
  * Web browser: OperaGX core: 62.0.3331.132
  * Tor status: not available
  * Opened port: no
  * Special configuration: Pipenv virtual management 
  * System Lang: Turkish

### Step 2: Describe the problem:
I getting unhandled exception(UnicodeDecodeError)
```bash
C:\Users\simplex\py_projects\ZeroNet (py3 -> origin)
(ZeroNet-iAvXUjmi) λ python zeronet.py
- Starting ZeroNet...
[15:42:44] - Libsecpk256k1 loaded: FFILibrary_C:\Users\simplex\.virtualenvs\ZeroNet-iAvXUjmi\lib\site-packages\coincurve\libsecp256k1.dll in 0.226s
[15:42:44] - Version: 0.7.0 r4197, Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)], Gevent: 1.4.0
[15:42:44] - Creating FileServer....
[15:42:44] - Creating UiServer....
[15:42:44] SiteManager Deleting orphan site from content.db: 1MgHVPCE1ve6QfKrgsqCURzRj72HrRWioz
[15:42:44] - Removing old SSL certs...
[15:42:44] - Starting servers....
[15:42:44] Ui.UiServer --------------------------------------
[15:42:44] Ui.UiServer Web interface: http://127.0.0.1:43110/
[15:42:44] Ui.UiServer --------------------------------------
[15:42:44] - Unhandled exception: [(<class 'UnicodeDecodeError'>, UnicodeDecodeError('utf-8', b'Sistem belirtilen yolu bulam\x8dyor.', 28, 29, 'invalid start byte'), <traceback object at 0x000001CBFF506188>)]
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "C:\Users\simplex\py_projects\ZeroNet\plugins\AnnounceLocal\AnnounceLocalPlugin.py", line 133, in start
    return super(FileServerPlugin, self).start(*args, **kwargs)
  File "C:\Users\simplex\py_projects\ZeroNet\src\File\FileServer.py", line 349, in start
    ConnectionServer.start(self)
  File "C:\Users\simplex\py_projects\ZeroNet\src\Connection\ConnectionServer.py", line 82, in start
    CryptConnection.manager.loadCerts()
  File "C:\Users\simplex\py_projects\ZeroNet\src\Crypt\CryptConnection.py", line 105, in loadCerts
    if self.createSslRsaCert() and "tls-rsa" not in self.crypt_supported:
  File "C:\Users\simplex\py_projects\ZeroNet\src\Crypt\CryptConnection.py", line 140, in createSslRsaCert
    back = proc.stdout.read().strip().decode().replace("\r", "")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 28: invalid start byte
[15:42:49] Ui.UiServer Added 127.0.0.1:43110 as allowed host
[15:42:50] Site:1MgHVP..Wioz Rebuilding db...
[15:42:50] Site:1MgHVP..Wioz Creating tables...
[15:42:50] Db:NullPaste Table keyvalue outdated...version: False need: 2, rebuilding...
[15:42:50] Db:NullPaste Table json outdated...version: 0 need: 2, rebuilding...
[15:42:50] Db:NullPaste Table paste outdated...version: 0 need: 2, rebuilding...
[15:42:50] Db:NullPaste Table comment outdated...version: 0 need: 1, rebuilding...
[15:42:50] Site:1MgHVP..Wioz Getting db files...
[15:42:50] Site:1MgHVP..Wioz [MISSING] data-default/users/content-default.json
[15:42:50] Site:1MgHVP..Wioz Importing data...
[15:42:50] Site:1MgHVP..Wioz Imported 0 data file in 0.002s
```
But ZeroNet working correctly.

#### Observed Results:
  * Got unhandled exception

**Comment by purplesyringa** [comment]
It looks like something is wrong with OpenSSL. Please run ZeroNet in debug mode (`python zeronet.py --debug`) and check whether the error persists. If it does, post a few lines above it.

**Comment by purplesyringa** [comment]
Additionally, please run `openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -config src/lib/openssl/openssl.cnf -subj "/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon" -keyout data/cakey-rsa.pem -out data/cacert-rsa.pem -batch` in ZeroNet directory and post the result please.

**Comment by bufgix** [comment]
> `openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -config src/lib/openssl/openssl.cnf -subj "/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon" -keyout data/cakey-rsa.pem -out data/cacert-rsa.pem -batch` 

I getting an error in this command
```bash
(ZeroNet-iAvXUjmi) λ openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -config src/lib/openssl/openssl.cnf -subj "/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon" -keyout data/cakey-rsa.pem -out data/cacert-rsa.pem -batch
req: Error on line 57 of config file "src/lib/openssl/openssl.cnf"
Generating a RSA private key
....................................................................................+++++
...............+++++
writing new private key to 'data/cakey-rsa.pem'
-----
unable to find 'distinguished_name' in config
problems making Certificate Request
12208:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:crypto\conf\conf_lib.c:270:
```
my environment property OPENSSL_CONF is
```bash
(ZeroNet-iAvXUjmi) λ echo %OPENSSL_CONF%
D:\Programs\OpenSSL-Win64\bin\openssl.cfg
```
and problem still persists
```bash
C:\Users\simplex\py_projects\ZeroNet (py3 -> origin)
(ZeroNet-iAvXUjmi) λ python zeronet.py --debug
[...]
[16:56:59] - Current maxstdio: 512, changing to 2048...
[16:56:59] CryptConnectionManager Generating RSA CAcert and CAkey PEM files...
[16:56:59] CryptConnectionManager Running: "tools\openssl\openssl.exe" req -new -newkey rsa:2048 -days 3650 -nodes -x509 -config "src/lib/openssl/openssl.cnf" -subj "/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA" -keyout "./data/cakey-rsa.pem" -out "./data/cacert-rsa.pem" -batch
[16:56:59] - Unhandled exception
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "C:\Users\simplex\py_projects\ZeroNet\plugins\AnnounceLocal\AnnounceLocalPlugin.py", line 133, in start
    return super(FileServerPlugin, self).start(*args, **kwargs)
  File "C:\Users\simplex\py_projects\ZeroNet\src\File\FileServer.py", line 349, in start
    ConnectionServer.start(self)
  File "C:\Users\simplex\py_projects\ZeroNet\src\Connection\ConnectionServer.py", line 82, in start
    CryptConnection.manager.loadCerts()
  File "C:\Users\simplex\py_projects\ZeroNet\src\Crypt\CryptConnection.py", line 105, in loadCerts
    if self.createSslRsaCert() and "tls-rsa" not in self.crypt_supported:
  File "C:\Users\simplex\py_projects\ZeroNet\src\Crypt\CryptConnection.py", line 140, in createSslRsaCert
    back = proc.stdout.read().strip().decode().replace("\r", "")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 28: invalid start byte
[16:56:59] SiteManager Saved sites in 0.01s (generate: 0.00s, write: 0.01s)
[16:56:59] SiteManager Updated merger sites in 0.000s
[16:56:59] Site:1Gfey7..fcdp Start downloading, bad_files: {'content.json': 6}, check_size: True, blind_includes: True
[16:56:59] Site:1Gfey7..fcdp Need content.json first
[16:56:59] BroadcastServer Started on port 1544
[...]
```

**Comment by purplesyringa** [comment]
Ok, that's interesting... let's try the following: replace line 140 in src/Crypt/CryptConnection.py with `stdout = proc.stdout.read(); print(stdout); back = stdout.read().strip().decode().replace("\r", "")` please and post the result (it should print some text above the error message). I believe no one has had an issue with OpenSSL before, that might be a localization issue or something.

**Comment by bufgix** [comment]
````python
stdout = proc.stdout.read()
print("-->  ", stdout)
back = proc.stdout.read().strip().decode().replace("\r", "")
````
Output:
```bash
(ZeroNet-iAvXUjmi) λ python zeronet.py
- Starting ZeroNet...
[17:12:50] - Libsecpk256k1 loaded: FFILibrary_C:\Users\simplex\.virtualenvs\ZeroNet-iAvXUjmi\lib\site-packages\coincurve\libsecp256k1.dll in 0.106s
[17:12:50] - Version: 0.7.0 r4197, Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)], Gevent: 1.4.0
[17:12:50] - Creating FileServer....
[17:12:50] - Creating UiServer....
[17:12:50] SiteManager Deleting orphan site from content.db: 1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp
[17:12:50] - Removing old SSL certs...
[17:12:50] - Starting servers....
[17:12:50] Ui.UiServer --------------------------------------
[17:12:50] Ui.UiServer Web interface: http://127.0.0.1:43110/
[17:12:50] Ui.UiServer --------------------------------------
-->   b'Sistem belirtilen yolu bulam\x8dyor.\r\n'
[17:12:50] CryptConnectionManager RSA ECC SSL CAcert generation failed, CAcert or CAkey files not exist. ()
[17:12:52] TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: No connection
[17:12:55] PeerPortchecker Checking port 34885 (ipv4) using checkPortchecker result: {'ip': '37.130.123.6', 'opened': False} in 2.433s
[17:12:55] PeerPortchecker Trying to open port using UpnpPunch...
[17:12:58] PeerPortchecker Checking port 34885 (ipv4) using checkPortchecker result: {'ip': '37.130.123.6', 'opened': False} in 1.845s
[17:12:58] ConnServer Server port opened ipv4: False, ipv6: None
```

I understand. This problem is related to my system language. ` b'Sistem belirtilen yolu bulam\x8dyor.\r\n'` mean `The system cannot find the path specified.`. Classic TR chars problem :/

but as I said, ZeroNet working correctly.

**Comment by purplesyringa** [comment]
Ok, so we need to handle errors better. We should probably handle OpenSSL errors better, I'll make a PR in a few minutes.

**Comment by purplesyringa** [comment]
I added a PR, please check if it fixes your issue.

**Comment by bufgix** [comment]
```bash
(ZeroNet-iAvXUjmi) λ python zeronet.py
- Starting ZeroNet...
[18:00:23] - Libsecpk256k1 loaded: FFILibrary_C:\Users\simplex\.virtualenvs\ZeroNet-iAvXUjmi\lib\site-packages\coincurve\libsecp256k1.dll in 0.106s
[18:00:24] - Version: 0.7.0 r4200, Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)], Gevent: 1.4.0
[18:00:24] - Creating FileServer....
[18:00:24] - Creating UiServer....
[18:00:24] SiteManager Deleting orphan site from content.db: 1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp
[18:00:24] - Removing old SSL certs...
[18:00:24] - Starting servers....
[18:00:24] Ui.UiServer --------------------------------------
[18:00:24] Ui.UiServer Web interface: http://127.0.0.1:43110/
[18:00:24] Ui.UiServer --------------------------------------
[18:00:24] CryptConnectionManager RSA ECC SSL CAcert generation failed, CAcert or CAkey files not exist. (b'Sistem belirtilen yolu bulam\x8dyor.')
[18:00:26] TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: No connection
[18:00:29] PeerPortchecker Checking port 34885 (ipv4) using checkPortchecker result: {'ip': '37.130.123.6', 'opened': False} in 2.645s
```
looks good.
