### ISSUE TITLE
Unhandled exception: database is locked

### ISSUE THREAD

**Issue by SuperSandro2000** [HelloZeroNet/ZeroNet#2185]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1 r4206
  * Operating system: Alpine
  * Web browser: None
  * Tor status: enabled
  * Opened port: no
  * Special configuration: Docker Image (https://github.com/SuperSandro2000/docker-images/blob/master/zeronet/amd64.Dockerfile)

#### Steps to reproduce:

  1. Start an old instance that has content downloaded.

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

[12:24:39] SiteManager Can't delete site ************************** from content_db: database is locked
[12:24:39] - Unhandled exception: database is locked
Traceback (most recent call last):
  File "zeronet.py", line 17, in main
    main.start()
  File "/app/src/main.py", line 537, in start
    actions.call(config.action, action_kwargs)
  File "/app/src/main.py", line 121, in call
    back = func(**kwargs)
  File "/app/src/main.py", line 133, in main
    ui_server = UiServer()
  File "/app/src/Ui/UiServer.py", line 86, in __init__
    self.sites = SiteManager.site_manager.list()
  File "/app/src/Site/SiteManager.py", line 196, in list
    self.load(startup=True)
  File "/app/plugins/Zeroname/SiteManagerPlugin.py", line 22, in load
    self.need(config.bit_resolver)  # Need ZeroName site
  File "/app/src/Site/SiteManager.py", line 175, in need
    site = Site(address, settings=settings)
  File "/app/src/Site/Site.py", line 56, in __init__
    self.content_manager = ContentManager(self)
  File "/app/plugins/OptionalManager/OptionalManagerPlugin.py", line 59, in __init__
    super(ContentManagerPlugin, self).__init__(*args, **kwargs)
  File "/app/src/Content/ContentManager.py", line 36, in __init__
    self.contents = ContentDbDict(site)
  File "/app/src/Content/ContentDbDict.py", line 16, in __init__
    self.db_id = self.db.needSite(site)
  File "/app/src/Content/ContentDb.py", line 88, in needSite
    self.execute("INSERT OR IGNORE INTO site ?", {"address": site.address})
  File "/app/src/Db/Db.py", line 110, in execute
    return self.cur.execute(query, params)
  File "/app/src/Db/DbCursor.py", line 103, in execute
    res = self.cursor.execute(query, params)
sqlite3.OperationalError: database is locked

#### Expected Results:

  * What did you expect to happen?

Start up correctly like always.

**Comment by SuperSandro2000** [comment]
Fixed in R4210
