### ISSUE TITLE
Upnp router configuration

### ISSUE THREAD

**Issue by sbDevGit** [HelloZeroNet/ZeroNet#223]
Hi, 
I tried ZeroNet on a computer, and it opened Upnp ports on the connected router
Then I tried ZeroNet on another computer behind the same router
and it was not able to open ports for this other IP address,
so I was not able to distribute the network,
so I removed the old UPnP configuration on my router, 
and I reloaded ZeroNet, and it opened the ports of the new IP address.

;)

Hope it helps to improve the software

Error logs :

[mardi 8 décembre 2015, 12:58:47 (UTC+0100)] ZeroNet is starting
- Starting ZeroNet...
[12:58:48] - Version: 0.3.2 r494, Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2], Gevent: 1.1b7.dev0
[12:58:48] - OpenSSL loaded, version: 01000106F
[12:58:48] - Creating FileServer....
[12:58:48] - Creating UiServer....
[12:58:51] - Removing old SSL certs...
[12:58:51] - Starting servers....
[12:58:51] Ui.UiServer --------------------------------------
[12:58:51] Ui.UiServer Web interface: http://127.0.0.1:43110/
[12:58:51] Ui.UiServer --------------------------------------
[12:58:52] FileServer Checking port 15441 using portchecker.co...
[12:58:54] FileServer [BAD :(] Port closed: Port 15441 is closed.
[12:58:54] FileServer Checking port 15441 using canyouseeme.org...
[12:59:07] FileServer [BAD :(] Port closed: Error: I could not see your service on 86.195.53.48 on port (15441) Reason: Connection timed out
[12:59:07] FileServer Trying to open port using UpnpPunch...
[12:59:07] - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/util/UpnpPunch.py", line 171, in _send_soap_request
    return _parse_for_errors(response)
  File "src/util/UpnpPunch.py", line 139, in _parse_for_errors
    err_dom = parseString(soap_response.read())
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: no element found: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/util/UpnpPunch.py", line 171, in _send_soap_request
    return _parse_for_errors(response)
  File "src/util/UpnpPunch.py", line 139, in _parse_for_errors
    err_dom = parseString(soap_response.read())
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
[12:59:07] - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/util/UpnpPunch.py", line 171, in _send_soap_request
    return _parse_for_errors(response)
  File "src/util/UpnpPunch.py", line 139, in _parse_for_errors
    err_dom = parseString(soap_response.read())
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: no element found: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 523, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/util/UpnpPunch.py", line 171, in _send_soap_request
    return _parse_for_errors(response)
  File "src/util/UpnpPunch.py", line 139, in _parse_for_errors
    err_dom = parseString(soap_response.read())
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
[12:59:11] FileServer Checking port 15441 using portchecker.co...
[12:59:13] FileServer [BAD :(] Port closed: Port 15441 is closed.
[12:59:13] FileServer Checking port 15441 using canyouseeme.org...
[12:59:21] FileServer [BAD :(] Port closed: Error: I could not see your service on 86.195.53.48 on port (15441) Reason: Connection timed out
[12:59:21] FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress

**Comment by nikolay** [comment]
:+1: Same issue. This thing doesn't work on Vagrant, now doesn't work on Docker either.

**Comment by HelloZeroNet** [comment]
It's hard to make it work without direct hardware access, but you are also fine without opened port.

**Comment by bryque** [comment]
Same issue.

**Comment by stephan1932** [comment]
I've the same issue, can someone explain what causes it and what are the consequences of having the port closed?

**Comment by Kogurex** [comment]
Same Thing Here... My partner at my side using Windows 10 connected successfully. Here's the terminal description:
`aoryu@LOCALFROST:~/ZeroBundle$ sudo ./ZeroNet.sh 
- Starting ZeroNet...
[08:50:38] - OpenSSL loaded, version: 01000207F
[08:50:38] - Version: 0.3.6 r1089, Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)], Gevent: 1.0.2
[08:50:38] - Creating FileServer....
[08:50:38] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > socket.py line 344
[08:50:38] - Creating UiServer....
[08:50:38] - Removing old SSL certs...
[08:50:38] - Starting servers....
[08:50:38] Ui.UiServer --------------------------------------
[08:50:38] Ui.UiServer Web interface: http://127.0.0.1:43110/
[08:50:38] Ui.UiServer --------------------------------------
[08:50:38] - Opening browser: default_browser...
[08:50:40] FileServer Checking port 15441 using portchecker.co...
[08:50:41] FileServer [BAD :(] Port closed: Port 15441 is closed.
[08:50:41] FileServer Trying to open port using UpnpPunch...
[08:50:56] FileServer Checking port 15441 using portchecker.co...
[08:50:58] FileServer [BAD :(] Port closed: Port 15441 is closed.
[08:50:58] FileServer Checking port 15441 using canyouseeme.org...
[08:51:06] FileServer [BAD :(] Port closed: Error: I could not see your service on 186.67.115.230 on port (15441) Reason: Connection timed out
[08:51:06] FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress
`

**Comment by HelloZeroNet** [comment]
You are safe to ignore it, opened port is not required to use zeronet

**Comment by xbee** [comment]
Could you explained it's theory?

**Comment by xbee** [comment]
I have the same things. But when I run UpnpPunch.py , I found it can addportmapping ok.
```
- Starting ZeroNet...
[19:29:52] - OpenSSL loaded, version: 0009081DF
[19:29:52] - Version: 0.3.7 r1287, Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)], Gevent: 1.1.1
[19:29:52] - Creating FileServer....
[19:29:52] TorManager Tor controller connect error: error: [Errno 61] Connection refused in TorManager.py line 154 > _socket2.py line 228
[19:29:52] - Creating UiServer....
[19:29:59] - Removing old SSL certs...
[19:29:59] - Starting servers....
[19:29:59] Ui.UiServer --------------------------------------
[19:29:59] Ui.UiServer Web interface: http://127.0.0.1:43110/
[19:29:59] Ui.UiServer --------------------------------------
[19:29:59] - Opening browser: default_browser...
[19:30:01] FileServer Checking port 15441 using portchecker.co...
[19:30:03] FileServer [BAD :(] Port closed: Port 15441 is closed.
[19:30:03] FileServer Trying to open port using UpnpPunch...
[19:30:04] FileServer Checking port 15441 using portchecker.co...
[19:30:06] FileServer [BAD :(] Port closed: Port 15441 is closed.
[19:30:06] FileServer Checking port 15441 using canyouseeme.org...
[19:30:15] FileServer [BAD :(] Port closed: Error: I could not see your service on 111.193.200.234 on port (15441) Reason: Connection timed out
[19:30:15] FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress
[19:30:47] Site:1MaiL5..Ju27 data/users/1NS9qMabhcMJpQqeqeFy14j3z9DkqNCWzS/content.json: Site too large 10486472 > 10485760, aborting task...
```

I think the open_port is working, But why it tell me upnp mapping failed? 
```
> python UpnpPunch.py
DEBUG:root:Found local ips: ['192.168.xx.xx']
DEBUG:root:Trying using local ip: 192.168.xx.xx
DEBUG:root:Sending UPnP request to 192.168.xx.1:37215...
DEBUG:root:Sending UPnP request to 192.168.xx.1:37215...
True
Done in 0.22724199295
```

**Comment by HelloZeroNet** [comment]
Probably an another router/isp is blocking your port.

**Comment by border0464111** [comment]
Have you managed to solve the problem @ghost ?
