### ISSUE TITLE
socks module missing from python3 even after it's installation

### ISSUE THREAD

**Issue by ManoaNosea** [HelloZeroNet/ZeroNet#2230]
* ZeroNet version: 0.7.1 r4206, Python 3.7.3 (default, Mar 27 2019, 22:11:17)
  * Operating system: Devuan jessie
  * Web browser: Firefox 45.9.0
  * Tor status: TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: No connection
  * Opened port: yes

### Step 2: Describe the problem: #### Steps to reproduce:
$ python3 zeronet.py siteCreate
- Site private key: ...
-                   !!! ^ Save it now, required to modify the site ^ !!!
- Site address:     ...
- ----------------------------------------------------------------------
? Have you secured your private key? (yes, no) > yes
- Creating directory structure...
- Unhandled exception: No module named 'socks'
Traceback (most recent call last):
  File "zeronet.py", line 17, in main
    main.start()
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/main.py", line 537, in start
    actions.call(config.action, action_kwargs)
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/main.py", line 121, in call
    back = func(**kwargs)
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/main.py", line 164, in siteCreate
    from Site.Site import Site
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/Site/Site.py", line 26, in <module>
    from File import FileServer
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/File/__init__.py", line 1, in <module>
    from .FileServer import FileServer
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/File/FileServer.py", line 16, in <module>
    from Connection import ConnectionServer
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/Connection/__init__.py", line 1, in <module>
    from .ConnectionServer import ConnectionServer
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/Connection/ConnectionServer.py", line 19, in <module>
    from Tor import TorManager
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/Tor/__init__.py", line 1, in <module>
    from .TorManager import TorManager
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/Tor/TorManager.py", line 17, in <module>
    import socks
ModuleNotFoundError: No module named 'socks'

# pip3 install socks
Collecting socks
  Downloading https://files.pythonhosted.org/packages/3b/a3/2192084c11c90df6947635a06181f5c1f9df94ae71be1808f4df91579640/socks-0.tar.gz
Building wheels for collected packages: socks
  Building wheel for socks (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/fc/ac/43/ca6b803cb5380beec40e3d4bc5907493ebb56615de4544ce01
Successfully built socks
Installing collected packages: socks
Successfully installed socks-0

wtf ?

**Comment by ManoaNosea** [comment]
I "fixed" it with pysocks
but now a new error:

$ python3 zeronet.py sitePublish 1H3gyiLwieUT5Wbb1Di88F6KjzbEwA3D63
- Starting ZeroNet...
PluginManager Plugin AnnounceBitTorrent load error: ModuleNotFoundError: No module named 'BTL' in PluginManager.py line 138 > AnnounceBitTorrent/__init__.py line 1 > AnnounceBitTorrent/AnnounceBitTorrentPlugin.py line 6 > __init__.py line 13
- Libsecpk256k1 loaded: CompiledLib in 0.109s
- Version: 0.7.1 r4206, Python 3.6.5 (default, Jun  8 2018, 16:30:09)
[GCC 7.2.0], Gevent: 1.4.0
- Loading site...
- Unhandled exception: 'NoneType' object has no attribute 'settings'
Traceback (most recent call last):
  File "zeronet.py", line 17, in main
    main.start()
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/main.py", line 537, in start
    actions.call(config.action, action_kwargs)
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/main.py", line 121, in call
    back = func(**kwargs)
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/main.py", line 381, in sitePublish
    site.settings["serving"] = True  # Serving the site even if its disabled
AttributeError: 'NoneType' object has no attribute 'settings'

**Comment by imachug** [comment]
It looks like the site was created incorrectly. Please run `siteCreate` again.

If this is fixed, please close this issue in favor of #2228.

**Comment by ManoaNosea** [comment]
fixed this too with manual bencode wheel download, but now a new error:

$ python3 zeronet.py sitePublish 1H3gyiLwieUT5Wbb1Di88F6KjzbEwA3D63
libhugetlbfs: WARNING: Unable to find default kernel huge page size
- Starting ZeroNet...
- Libsecpk256k1 loaded: CompiledLib in 0.056s
- Version: 0.7.1 r4206, Python 3.6.5 (default, Jun  8 2018, 16:30:09)
[GCC 7.2.0], Gevent: 1.4.0
- Loading site...
- Unhandled exception: 'NoneType' object has no attribute 'settings'
Traceback (most recent call last):
  File "zeronet.py", line 17, in main
    main.start()
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/main.py", line 537, in start
    actions.call(config.action, action_kwargs)
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/main.py", line 121, in call
    back = func(**kwargs)
  File "/mnt/build/ZeroNet-linux-dist-linux64/core/src/main.py", line 381, in sitePublish
    site.settings["serving"] = True  # Serving the site even if its disabled
AttributeError: 'NoneType' object has no attribute 'settings'

**Comment by imachug** [comment]
Btw, as for the socks problem: have you installed all the dependencies with `pip3 install -r requirements.txt`?

**Comment by imachug** [comment]
See, ZeroNet can't publish a site because it doesn't exist in the first place because its creation was aborted. Please re-create it.

**Comment by ManoaNosea** [comment]
what I did was delete the site data directory and created a symlink to my site data files, I think it messed it up, is there any way to tell him from where to take the site data files at creation time ?

**Comment by ManoaNosea** [comment]
pip3 install -r core/requirements.txt was not mentioned in the installation instructions :x
but now I did I guess will have to do everything from scratch :)

**Comment by imachug** [comment]
Delete the symlink, create the site as usual, and replace its directory with symlink.

**Comment by imachug** [comment]
Wait, where did you take the `core` part? It looks like if you downloaded ZeroBundle but instead of running an exe, you manually used python.

**Comment by ManoaNosea** [comment]
the instructions on the page say to run zeronet.py, this is only possible by running python3 no ?

How can I create a ZeroNet site?

Shut down zeronet if you are running it already

$ zeronet.py siteCreate
...
- Site private key: 23DKQpzxhbVBrAtvLEc2uvk7DZweh4qL3fn3jpM3LgHDczMK2TtYUq
- Site address: 13DNDkMUExRf9Xa9ogwPKqp7zyHFEqbhC2
...
- Site created!
$ zeronet.py
...

**Comment by ManoaNosea** [comment]
ZeroNet-linux-dist-linux64$ find . -name zeronet.py
./core/zeronet.py

**Comment by ManoaNosea** [comment]
Delete the symlink, create the site as usual, and replace its directory with symlink.

it's exactly what I did :)
it didn't work :x I try again ....
what about zeronet.py --updatesite 1H3gyiLwieUT5Wbb1Di88F6KjzbEwA3D63
?

**Comment by imachug** [comment]
> the instructions on the page say to run zeronet.py, this is only possible by running python3 no ?

The instructions say to run ZeroNet.py if you're building ZeroNet from source, and ZeroNet.sh if you're using a binary distribution.

**Comment by imachug** [comment]
> what about zeronet.py --updatesite 1H3gyiLwieUT5Wbb1Di88F6KjzbEwA3D63

Nah, this won't work. Tbh I expected siteCreate to fix the problem. Investigating...

**Comment by imachug** [comment]
Btw, I'd recommend you to create the site via web UI (http://127.0.0.1:43110), it's a lot easier and also allows you to restore site privatekey if you forget it.

**Comment by ManoaNosea** [comment]
ok, so I guess I didn't read correctly the instructions, so where are the instructions for creating a site using the binary version ?

**Comment by imachug** [comment]
I could reproduce your issue. Investigating

**Comment by imachug** [comment]
> ok, so I guess I didn't read correctly the instructions, so where are the instructions for creating a site using the binary version ?

You can either use `zeronet.sh siteCreate` which looks broken atm or start ZeroNet, open ZeroHello, open menu next to "Hello ZeroNet_" and click "create new, empty site".

**Comment by ManoaNosea** [comment]
I did from UI, now he is showing the site exist :)
I will check if he is working

**Comment by imachug** [comment]
@HelloZeroNet Can we please have some sort of stable branch and automate master-stable merging? Failing tests and broken features in master are driving me mad.

**Comment by ManoaNosea** [comment]
but when I open it he says: Internal error: KeyError: 'content.json'
UiWebsocket.py line 187 > UiWebsocket.py line 1028 > ContentDbDict.py line 59

**Comment by imachug** [comment]
Please make sure you have some kind of content.json file in site root. Bootstrapping sites is a bit difficult if you already have code, let me make a small instruction:

- Create site via UI;
- Copy `content.json` from the new directory to your old site directory;
- Delete new site directory;
- Move, copy or symlink your old directory to where the new site directory was.

If you've deleted content.json already, you can just copy it from any other site. Make sure to change the title, description and such though.

**Comment by ManoaNosea** [comment]
worked :) he showing some parts of the site :)
some size problem:
Content signing failed
Content too large 7759486398B > 5242880000B, aborting task...

**Comment by imachug** [comment]
It looks like your site takes about 7 GiB. Is that the case?

**Comment by ManoaNosea** [comment]
it's 3.88 BiB

**Comment by imachug** [comment]
Sorry, what is `BiB`?

**Comment by ManoaNosea** [comment]
I think double directory :x I delete the other let see what hapen, need to restart ?

**Comment by ManoaNosea** [comment]
bilion bytes xD

**Comment by imachug** [comment]
> bilion bytes xD

Ah, got it. I think we usually use GiB for that but whatever.

> I think double directory :x I delete the other let see what hapen, need to restart ?

Well you can do that if you want to, but I wouldn't recommend you to publish all those 4 GiB. There's a better solution.

**Comment by ManoaNosea** [comment]
mybe I should prevent the data files from uploading, can I tell him to not upload specific file types and keep those local ?

**Comment by imachug** [comment]
See, ZeroNet has *required* files and *optional* files. Everyone who downloads a site will download all the required files, but they will also download optional files on demand. The default size limit for required files is 10 MiB, with some sites asking for about 100 MiB. See, 4 GiB if a lot more than that and you probably don't want everyone to download 4 GiB (neither they will). Instead, you can make all those big files optional. In this case, ZeroNet will only download those files on-demand, when the user requests them.

---

What files exactly are you storing? Video, music, pictures, just binary data?

**Comment by imachug** [comment]
Interesting, I can reproduce your issue on Android (Termux) but not on Windows.

**Comment by ManoaNosea** [comment]
it's compressed archives, some source code compressed archvies takes some 600 mega :x
ok let's do it, whare do I have to go to tell him which files to classified for optional ?

**Comment by imachug** [comment]
Ah, got it. Optional files work really well in this case. Open `content.json` in site root and add the following line somewhere:

```
"optional": ".*\\.tar",
```

This will include all files ending with `.tar`. `optional` field is just a regex (`^`/`$` are added automatically), so you can set whatever you want.

You can then make sure the regex is correct by signing content.json (via sidebar) and checking `files_optional` field.

**Comment by imachug** [comment]
Some updates, this issue can be reproduced on Android (Termux) natively but not via SSH.

**Comment by ManoaNosea** [comment]
ok I made the changes but I don't see whare in the main page to go to see them, I only have option to update on the sidebar

**Comment by ManoaNosea** [comment]
I think it working, when I load the page he says escaping frames, is that going to be for everyone or just for me ?

**Comment by ManoaNosea** [comment]
he random selecting one of the frames insted of showing them as they supposed to be :x

**Comment by ManoaNosea** [comment]
he is also redirecting links to pictures and prefixing them with /media ?

**Comment by imachug** [comment]
> ok I made the changes but I don't see whare in the main page to go to see them, I only have option to update on the sidebar

Open the sidebar, scroll down, toggle "This is my site", press "Sign & publish".

**Comment by imachug** [comment]
> I think it working, when I load the page he says escaping frames, is that going to be for everyone or just for me ?

That's going to look like that for everyone. It looks like if you were using links or something incorrectly. When do you get that "escaping frame" error?

**Comment by imachug** [comment]
> he random selecting one of the frames insted of showing them as they supposed to be :x

One of the frames? What, are you using frames? Like in `frameset`?

**Comment by imachug** [comment]
> he is also redirecting links to pictures and prefixing them with /media ?

Nope, it shouldn't work like that.

**Comment by ManoaNosea** [comment]
when I load the site itself he starts instantly to escape the frames, this is the index.html:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN"
   "http://www.w3.org/TR/html4/frameset.dtd">
<html>
<head><title>Manoa</title></head>
<FRAMESET cols="100,100%" noresize border=no>
	<FRAME noresize scrolling=no frameborder=1 marginwidth=0 marginheight=0 name="root" src="frame1.html">
  	<FRAME noresize scrolling=auto frameborder=1 marginwidth=0 marginheight=0 name="mainframe" src="frame2.html">
</FRAMESET>
</html>

**Comment by ManoaNosea** [comment]
```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN"
   "http://www.w3.org/TR/html4/frameset.dtd">
<html>
<head><title>Manoa</title></head>
<FRAMESET cols="100,100%" noresize border=no>
	<FRAME noresize scrolling=no frameborder=1 marginwidth=0 marginheight=0 name="root" src="frame1.html">
  	<FRAME noresize scrolling=auto frameborder=1 marginwidth=0 marginheight=0 name="mainframe" src="frame2.html">
</FRAMESET>
</html>```

**Comment by ManoaNosea** [comment]
Open the sidebar, scroll down, toggle "This is my site", press "Sign & publish".
I can't find this :x

**Comment by imachug** [comment]
Ooh, I think I have some bad news for you. ZeroNet doesn't support frames at the moment.

**Comment by imachug** [comment]
> I can't find this :x

What "this"? Can you find the sidebar? Drag the `0` button in the right-top corner to the left.

**Comment by ManoaNosea** [comment]
some of the pictures were prefixed with absolute path /
so he translate them into: http://127.0.0.1:43110/Pics/....png
I replace them now with relative

**Comment by imachug** [comment]
Absolute paths should work if you use the template from the default site. Namely:

```html
<base href="" target="_top" id="base">
<script>base.href = document.location.href.replace("/media", "").replace("index.html", "").replace(/[&?]wrapper=False/, "").replace(/[&?]wrapper_nonce=[A-Za-z0-9]+/, "")</script>
```

**Comment by ManoaNosea** [comment]
Drag the 0 button in the right-top corner to the left.
nice :)
I see it :)
ok well, thanks anyway, im not sure if I wanne rewrite the site now for zeronet, mybe later in the future if I have time and power :)
you were grate guys thank for the help :)

**Comment by ManoaNosea** [comment]
thare is another error mybe it help you to do debuging:
Internal error: JSONDecodeError: Expecting property name enclosed in double quotes: line 5807 column 4 (char 202589)
UiWebsocket.py line 187 > UiWebsocket.py line 1069 > UiWebsocket.py line 1046 > ContentManager.py line 385 > Bigfile/BigfilePlugin.py line 351 > ContentManager.py line 997 > ContentManager.py line 934 > __init__.py line 296 > __init__.py line 348 > decoder.py line 337 > decoder.py line 353

I don't know what's it meens

**Comment by ManoaNosea** [comment]
say if you wanne to close this

**Comment by ManoaNosea** [comment]
say if you wanne to close this

**Comment by imachug** [comment]
> ok well, thanks anyway, im not sure if I wanne rewrite the site now for zeronet, mybe later in the future if I have time and power :)

We're working hard on making frames and such work, do you want me to ping you when we get this done?

> thare is another error mybe it help you to do debuging:

It looks like if some `content.json` is invalid, namely there is a missing quote.

> say if you wanne to close this

Nope, please keep this open for now because the siteCreate/sitePublish bug is unfixed.

**Comment by ManoaNosea** [comment]
yhe sure, ping will be grate :)
he writed this on that line:
  }
 },me
 "ignore": "(js|css)/(?!all.(js|css))",

I don't know whare this "me" come from

**Comment by imachug** [comment]
No idea as well, maybe just a typo. You can just remove those two characters.

**Comment by ManoaNosea** [comment]
I suppose the site will work on his own when the frames will work ?
so you think I should keep the site on and not delete him ?

**Comment by ManoaNosea** [comment]
the optional files is working, he put 2 giga into optional, I think I will put the pictures also into optional :) they take 1 giga of space :x

**Comment by imachug** [comment]
> so you think I should keep the site on and not delete him ?

Right, I think so.

> the optional files is working, he put 2 giga into optional, I think I will put the pictures also into optional :) they take 1 giga of space :x

Huh, that's a lot.

**Comment by ManoaNosea** [comment]
Content signing error
PermissionError: [Errno 13] Permission denied: '/mnt/build/ZeroNet-linux-dist-linux64/data/1NhgYjTLMhjgWyk2aaUsjoMW3xHqG6T5gP/Pics/KF2/KFGame2018-09-1406-16-36.png.piecemap.msgpack' in UiWebsocket.py line 441 > ContentManager.py line 691 > ContentManager.py line 638 > Bigfile/BigfilePlugin.py line 320 > SiteStorage.py line 219

more problems :x
I check chmod this and it's ok :x

**Comment by ManoaNosea** [comment]
I think I understand this, when I add optional png but the png files are alredy in the list that is the problem, I will delete the "files" list and update

**Comment by imachug** [comment]
> more problems :x

That's interesting. IIRC I've never had such an issue with big files. I might have a small fix that might resolve that issue though, wait a sec.

**Comment by imachug** [comment]
Ok, I'm afraid I don't have the fix now. It looks like if ZeroNet opened the file but didn't close it.

**Comment by ManoaNosea** [comment]
ok I restart him :)

**Comment by ManoaNosea** [comment]
how I can do several file types to be as optional ?

**Comment by imachug** [comment]
> how I can do several file types to be as optional ?

Use `|`, like this: `"optional": ".*\\.(png|tar\\.gz)"`

**Comment by ManoaNosea** [comment]
thank :)
but this time he is not loading into optional anything at all :x

**Comment by ManoaNosea** [comment]
"optional": ".*\\.(7z|png|rar|zip|tar\\.xz)",

**Comment by ManoaNosea** [comment]
it shows only one \ but it is two in the file

**Comment by ManoaNosea** [comment]
he is giving the png access denied error again :x

**Comment by ManoaNosea** [comment]
ok the png error is gone and update was successful but he is taking the files into optional at all :x

**Comment by ManoaNosea** [comment]
could be the HUD is not update this information ?

**Comment by imachug** [comment]
Hm, no idea why it doesn't work. It's worth trying the following though: `"optional": ".*\\.tar\\.xz|.*\\.png|..."`.

**Comment by imachug** [comment]
That's fine. This means that your ISP didn't give you an open port.

**Comment by ManoaNosea** [comment]
this is a problem with --tor always, --tor enable is working :)

**Comment by imachug** [comment]
Right, your port is always closed when Tor: Always mode is enabled.

**Comment by ManoaNosea** [comment]
whare can I find information about the modes ?
tor always is recommended right ?
but how to run it ?

**Comment by imachug** [comment]
When Tor is disabled, you can only connect to peers who use Clearnet.

"Tor: Enable" mode means that Tor is used to connect to onion peers and Clearnet is used to connect to Clearnet peers.

"Tor: Always" mode means that Tor is used to connect to onion peers, and peers who only use Clearnet (i.e. those with disabled Tor) cannot be connected to.

---

You can check the current Tor status on ZeroHello in the top-right corner.

**Comment by ManoaNosea** [comment]
the problem was that, as long as the "files" section in the json exists, he will not respect the optional parameter :x

**Comment by imachug** [comment]
> he wanne crate the file *.piecemap.msgpack inside that directory I don't know whay

ZeroNet creates a .msgpack file for big optional files ("big" starts at about 10 MiB).

**Comment by ManoaNosea** [comment]
all done :) thank the help and the explain :)
