### ISSUE TITLE
Unhandled exception: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by 2694513590** [HelloZeroNet/ZeroNet#2267]
### Step 1: Please describe your environment

  * ZeroNet version: _____
  * Operating system: _____
  * Web browser: _____
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: ____

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
Can you please add more details? What have you done? Maybe more details on the error (file names and line numbers)

**Comment by slrslr** [comment]
i have got this error (TypeError: expected str, bytes or os.PathLike object, not NoneType) too. Here are details:

### Step 1: Please describe your environment

  * ZeroNet version: latest as of the date of this comment submission
  * Operating system: Linux Arch
 
### Step 2: Describe the problem:

```
$ ./zeronet.sh
- Starting ZeroNet...
[10:50:48] - Unhandled exception: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/myusername/apps/zeronet/core/zeronet.py", line 16, in main
    import main
  File "/home/myusername/apps/zeronet/core/src/main.py", line 74, in <module>
    from Plugin import PluginManager
  File "/home/myusername/apps/zeronet/core/src/Plugin/PluginManager.py", line 211, in <module>
    plugin_manager = PluginManager()  # Singletone
  File "/home/myusername/apps/zeronet/core/src/Plugin/PluginManager.py", line 19, in __init__
    self.path_plugins = os.path.abspath(os.path.dirname(plugins.__file__))
  File "/home/myusername/apps/zeronet/runtime/lib/python37.zip/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
---
Please report it:
```

```
$ cd core;python3 zeronet.py
- Starting ZeroNet...
ERROR:root:Unhandled exception: No module named 'gevent'
Traceback (most recent call last):
  File "/home/myusername/apps/zeronet/core/zeronet.py", line 16, in main
    import main
  File "/home/myusername/apps/zeronet/core/src/main.py", line 14, in <module>
    import gevent
ModuleNotFoundError: No module named 'gevent'
---
Please report it
```

```
$ pip install gevent
...
Successfully installed gevent-20.12.1 greenlet-0.4.17 zope.event-4.5.0 zope.interface-5.2.0
```

but that not helped, same error happening. Maybe i have some file damaged...? 

update: downloading old zeronet version 0.7.2 r4555 worked, though i still have that damaged files if needed.

I already tried using original files:

cd /path/to/zeronet/core/
file=**start.py** && suff=_old && mv $file $file$suff;wget https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/$file;chmod 664 $file
file=**zeronet.py** && suff=_old && mv $file $file$suff;wget https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/$file;chmod 664 $file
cd src
file=**main.py** && suff=_old && mv $file $file$suff;wget https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/$file;chmod 664 $file
cd Plugin
file=**PluginManager.py** && suff=_old && mv $file $file$suff;wget https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/src/Plugin/$file;chmod 664 $file
--2021-01-07 11:20:02--  https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/src/Plugin/PluginManager.py

Maybe filesystem damage? I tried to move away zeronet.conf that not helped. What to try?

**update:** downloading old zeronet version 0.7.2 r4555 worked, though i still have that damaged files if needed.
