### ISSUE TITLE
errors work on Cygwin

### ISSUE THREAD

**Issue by gema-arta** [HelloZeroNet/ZeroNet#227]
```
$ uname -a
CYGWIN_NT-6.1 Gems 2.3.1(0.291/5/3) 2015-11-14 12:44 x86_64 Cygwin
```

```
$ openssl version
OpenSSL 1.0.2e 3 Dec 2015
```

```
$ python --version
Python 2.7.10
```

```
$ pip list
binwalk (2.1.0)
bsddb3 (6.1.0)
bzr (2.7.0.dev1)
bzr-fastimport (0.13.0.final.0)
cffi (0.9.2)
cryptography (0.8.2)
cvs2svn (2.4.0)
ecdsa (0.13)
enum34 (1.0.4)
fastimport (0.9.2)
getmail (4.36.0)
gevent (1.0.1)
greenlet (0.4.9)
msgpack-python (0.4.6)
Pillow (2.8.1)
pip (7.1.2)
ply (3.6)
pyasn1 (0.1.6)
pycparser (2.12)
pygobject (3.18.2)
pyOpenSSL (0.15.1)
pyzmq (15.0.0)
setuptools (18.5)
simplejson (3.6.5)
six (1.9.0)
urlgrabber (3.1.0)
wheel (0.26.0)
```

```
$ python zeronet.py --version
- Starting ZeroNet...
- OpenSSL *load failed: function 'BN_new' not found*, falling back to slow bitcoin verify
ZeroNet 0.3.4 r664
```

```
$ python zeronet.py
- Starting ZeroNet...
[20:23:43] - OpenSSL load failed: function 'BN_new' not found, falling back to slow bitcoin verify
[20:23:43] - Version: 0.3.4 r664, Python 2.7.10 (default, Jun  1 2015, 18:05:38)
[GCC 4.9.2], Gevent: 1.0.1
Traceback (most recent call last):
  File "zeronet.py", line 15, in main
    main.start()
  File "src/main.py", line 340, in start
    actions.call(config.action, action_kwargs)
  File "src/main.py", line 96, in call
    func(**kwargs)
  File "src/main.py", line 102, in main
    from File import FileServer
  File "src/File/__init__.py", line 1, in <module>
    from FileServer import FileServer
  File "src/File/FileServer.py", line 12, in <module>
    from Connection import ConnectionServer
  File "src/Connection/__init__.py", line 1, in <module>
    from ConnectionServer import ConnectionServer
  File "src/Connection/ConnectionServer.py", line 13, in <module>
    from Connection import Connection
  File "src/Connection/Connection.py", line 10, in <module>
    from Crypt import CryptConnection
  File "src/Crypt/CryptConnection.py", line 7, in <module>
    from util import SslPatch
  File "src/util/SslPatch.py", line 28, in <module>
    disableSSLCompression()
  File "src/util/SslPatch.py", line 22, in disableSSLCompression
    openssl.sk_zero.argtypes = [ctypes.c_void_p]
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'sk_zero' not found

{exit}
```

```
$ python zeronet.py --disable_sslcompression False
- Starting ZeroNet...
[20:41:46] - OpenSSL load failed: function 'BN_new' not found, falling back to slow bitcoin verify
[20:41:46] - Version: 0.3.4 r664, Python 2.7.10 (default, Jun  1 2015, 18:05:38)
[GCC 4.9.2], Gevent: 1.0.1
[20:41:46] - Creating FileServer....
[20:41:46] - Creating UiServer....
[20:41:46] - Removing old SSL certs...
[20:41:46] - Starting servers....
[20:41:46] Ui.UiServer --------------------------------------
[20:41:46] Ui.UiServer Web interface: http://127.0.0.1:43110/
[20:41:46] Ui.UiServer --------------------------------------
[20:41:47] FileServer Checking port 15441 using portchecker.co...
[20:41:48] FileServer [OK :)] Port open: Port 15441 is open.
...
{but}
...
[20:46:27] Site:1MaiL5..Ju27 WebSocket handleRequest error: AttributeError: function 'BN_new' not found in UiWebsocket.py line 65 > UiWebsocket.py line 143 > CryptMessagePlugin.py line 89 > __init__.py line 16 > openssl.py line 449 > openssl.py line 439 > openssl.py line 49 > __init__.py line 378 > __init__.py line 383
[20:46:27] Site:1MaiL5..Ju27 Publishing to 5/27 peers (connected: 21)...

{worked}
```

**Comment by HelloZeroNet** [comment]
Thanks for reporting the disable SSL compression error will be fixed in the next version.

Unfortunately the CryptMessagePlugin (that include cryptography required for ZeroMail) requires OpenSSL, so it will not work without that and for some reasons it could find in enviroment. I will try to find a way to load cygwin's openssl dll.

**Comment by HelloZeroNet** [comment]
Can you please verify if this works for you: `python -c "print __import__('ctypes.util').util.find_library('libcrypto')"` ?

**Comment by gema-arta** [comment]
This don`t work to me 

```
$ python -c "print __import__('ctypes.util').util.find_library('openssl')"
None
```

```
pip list | grep crypto
cryptography (1.1.2)
ctypescrypto (0.3.1)
pycrypto (2.6.1)
```

**Comment by HelloZeroNet** [comment]
It's searching for openssl dll, so its not depends on other python modules installed.

can you check if you have "libcrypto.dll", "crypto.dll", "ssl.dll", "libeay32.dll" or similar in /usr/lib/?

**Comment by gema-arta** [comment]
```
ldd /usr/bin/openssl
        ntdll.dll => /cygdrive/c/Windows/SYSTEM32/ntdll.dll (0x76cb0000)
        kernel32.dll => /cygdrive/c/Windows/system32/kernel32.dll (0x76b90000)
        KERNELBASE.dll => /cygdrive/c/Windows/system32/KERNELBASE.dll (0x7fefcd80000)
        cygcrypto-1.0.0.dll => /usr/bin/cygcrypto-1.0.0.dll (0x5e40e0000)
        cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
        cygz.dll => /usr/bin/cygz.dll (0x3f3280000)
        cygssl-1.0.0.dll => /usr/bin/cygssl-1.0.0.dll (0x5eb130000)
```

```
$ tar tfv x86_64/release/openssl/libopenssl100/libopenssl100-1.0.2e-1.tar.xz
-rwxr-xr-x corinna/vinschen 2270227 2015-12-03 23:47 usr/bin/cygcrypto-1.0.0.dll
-rwxr-xr-x corinna/vinschen  433683 2015-12-03 23:47 usr/bin/cygssl-1.0.0.dll
drwxr-xr-x corinna/vinschen       0 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/
-rwxr-xr-x corinna/vinschen   18451 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/lib4758cca.so
-rwxr-xr-x corinna/vinschen   18963 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libaep.so
-rwxr-xr-x corinna/vinschen   14867 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libatalla.so
-rwxr-xr-x corinna/vinschen   22035 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libcswift.so
-rwxr-xr-x corinna/vinschen    8723 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libgmp.so
-rwxr-xr-x corinna/vinschen   22547 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libchil.so
-rwxr-xr-x corinna/vinschen   13843 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libnuron.so
-rwxr-xr-x corinna/vinschen   25619 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libsureware.so
-rwxr-xr-x corinna/vinschen   19987 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libubsec.so
-rwxr-xr-x corinna/vinschen    8723 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libpadlock.so
-rwxr-xr-x corinna/vinschen    8723 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libcapi.so
-rwxr-xr-x corinna/vinschen   93715 2015-12-03 23:47 usr/lib/openssl-1.0.2/engines/libgost.so
```

**Comment by HelloZeroNet** [comment]
I also installed cygwin and only thing I was able to make it work:
`python -c "print '%.9X' % __import__('ctypes').CDLL('/bin/cygcrypto-1.0.0.dll').SSLeay()"`
please verify if its also works for you

**Comment by gema-arta** [comment]
```
Gem@Gems /cygdrive/c/Program Files/Microsoft SDKs/Windows/v7.1
$ python -c "print '%.9X' % __import__('ctypes').CDLL('/bin/cygcrypto-1.0.0.dll').SSLeay()"
01000205F
```

**Comment by gema-arta** [comment]
```
Microsoft (R) COFF/PE Dumper Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\cygwin64\bin\cygcrypto-1.0.0.dll

File Type: DLL

  Section contains the following exports for cygcrypto-1.0.0.dll

    00000000 characteristics
    5660A83B time date stamp Thu Dec 03 23:38:19 2015
        0.00 version
           1 ordinal base
        4218 number of functions
        4218 number of names

    ordinal hint RVA      name

          1    0 001354B0 ACCESS_DESCRIPTION_free
          2    1 001DA5E0 ACCESS_DESCRIPTION_it
          3    2 001354E0 ACCESS_DESCRIPTION_new
          4    3 000414B0 AES_bi_ige_encrypt
          5    4 00042CD0 AES_cbc_encrypt
          6    5 00040F90 AES_cfb128_encrypt
          7    6 00040FD0 AES_cfb1_encrypt
          8    7 00041010 AES_cfb8_encrypt
          9    8 00041080 AES_ctr128_encrypt
         10    9 000426D0 AES_decrypt
         11    A 00040F70 AES_ecb_encrypt
         12    B 00042120 AES_encrypt
         13    C 000410C0 AES_ige_encrypt
         14    D 00041050 AES_ofb128_encrypt
         15    E 00040F40 AES_options
         16    F 00040F60 AES_set_decrypt_key
         17   10 00040F50 AES_set_encrypt_key
         18   11 00041C80 AES_unwrap_key
         19   12 0018AB20 AES_version
		 ...
		2566  A05 00164C60 SRP_get_default_gN
		2567  A06 00004150 SSLeay
		2568  A07 00004100 SSLeay_version
		2569  A08 001C82C0 STACK_version
		2570  A09 00131410 SXNETID_free
		2571  A0A 001D9260 SXNETID_it
		2572  A0B 00131400 SXNETID_new
		...
		4215 1076 00032F40 whirlpool_block
		4216 1077 0016FF40 x509_dir_lookup
		4217 1078 0016FEC0 x509_file_lookup
		4218 1079 001CF820 x509_name_ff
 ...
```

**Comment by HelloZeroNet** [comment]
Yes, this is what we looking for, I will do some tests then release the patch that fixes cygwin compatiblity

**Comment by HelloZeroNet** [comment]
Pushed the modifications (394a8b16b7521d1885e2e96cb6d0a413b4478bc9) please update your source code and try again.
You can test if the openssl working on http://127.0.0.1:43110/Benchmark page.
`- openssl verify x 100..........0.396s [x0.93: OK]`

**Comment by gema-arta** [comment]
...but no effect - function 'BN_new' not found

```
$ python zeronet.py
- Starting ZeroNet...
[10:41:14] - OpenSSL load failed: function 'BN_new' not found, falling back to slow bitcoin verify
[10:41:14] - Version: 0.3.4 r665, Python 2.7.10 (default, Jun  1 2015, 18:05:38)
[GCC 4.9.2], Gevent: 1.0.1
[10:41:15] - Creating FileServer....
```

requested 

```
Benchmarking ZeroNet 0.3.4 (rev665) Python 2.7.10 (default, Jun 1 2015, 18:05:38) [GCC 4.9.2] on: cygwin...

CryptBitcoin:
- hdPrivatekey x 10..........0.158s [x4.43: Insane!!]
- sign x 10..........0.071s [x4.93: Insane!!]
- openssl verify x 100...not avalible :(
- pure-python verify x 10..........0.352s [x4.55: Insane!!]

CryptHash:
- sha512 x 100 000..........0.374s [x2.67: WOW]
- os.urandom(256) x 100 000..........0.290s [x2.24: Fast]

Msgpack:
- pack 5K x 10 000..........0.334s [x2.34: Fast]
- unpack 5K x 10 000..........0.530s [x2.26: Fast]
- streaming unpack 5K x 10 000..........0.576s [x2.43: Fast]

Db:
- Open x 10..........0.037s [x3.51: Insane!!]
- Insert x 10 x 1000..........0.484s [x2.07: Fast]
- Buffered insert x 100 x 100..........0.641s [x2.03: Fast]
- Total rows in db: 20000
- Indexed query x 1000..........0.356s [x0.70: Goodish]
- Not indexed query x 100..........0.245s [x2.45: Fast]
- Like query x 100..........0.526s [x3.42: WOW]

Done. Total: 5.16s
```

**Comment by HelloZeroNet** [comment]
sorry, my bad, please update and try again 35b0019be285cd81dac9d3e0ed97712c76f88a93

**Comment by gema-arta** [comment]
Fixed

```
$ python zeronet.py
- Starting ZeroNet...
[02:38:17] - OpenSSL loaded, version: 01000205F
[02:38:17] - Version: 0.3.4 r667, Python 2.7.10 (default, Jun  1 2015, 18:05:38)
[GCC 4.9.2], Gevent: 1.0.1
[02:38:17] - Creating FileServer....
[02:38:17] - Creating UiServer....
[02:38:18] - Removing old SSL certs...
[02:38:18] - Starting servers....
[02:38:18] Ui.UiServer --------------------------------------
[02:38:18] Ui.UiServer Web interface: http://127.0.0.1:43110/
[02:38:18] Ui.UiServer --------------------------------------
[02:38:19] FileServer Checking port 15441 using portchecker.co...
[02:38:20] FileServer [OK :)] Port open: Port 15441 is open.
```
