### ISSUE TITLE
Unhandled exception: AttributeError: 'ConfigPlugin' object has no attribute 'getCmdlineValue'

### ISSUE THREAD

**Issue by Noruka** [HelloZeroNet/ZeroNet#2336]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1
  * Operating system: Windows 10
  * Web browser: Google Chrome
  * Tor status: not available
  * Opened port: no
  * Special configuration: ____

### Step 2: Describe the problem:
Error when opening zeronet client after trying to update.
#### Steps to reproduce:

  1. when starting zeronet click update py3 quickly
  2. click on update even if it's green background
  3. probably fail to open zeronet again

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
Can you please paste the full error message and when do you see this error?

**Comment by Noruka** [comment]
I was updating and it just did that, now when I open it it automaticly generates the issue report. It also opens a txt file:

/******************************/

Traceback (most recent call last):
  File "C:\Users\WorkSpace\Desktop\ZeroNet-win-dist-win64\core\zeronet.py", line 16, in main
    import main
  File "C:\Users\WorkSpace\Desktop\ZeroNet-win-dist-win64\core\src\main.py", line 64, in <module>
    config.loadPlugins()
  File "C:\Users\WorkSpace\Desktop\ZeroNet-win-dist-win64\core\src\Config.py", line 466, in loadPlugins
    ConfigPlugin(self)
  File "C:\Users\WorkSpace\Desktop\ZeroNet-win-dist-win64\core\src\Config.py", line 461, in __init__
    self.createArguments()
  File "C:/Users/WorkSpace/Desktop/ZeroNet-win-dist-win64/data/__plugins__/1NAMEz7stUPZErkV1d3yLkVWQFa4PTqDNv/plugins\NameYo\UiRequestPlugin.py", line 32, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "C:\Users\WorkSpace\Desktop\ZeroNet-win-dist-win64\core\plugins\Zeroname\SiteManagerPlugin.py", line 69, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "C:\Users\WorkSpace\Desktop\ZeroNet-win-dist-win64\core\plugins\OptionalManager\OptionalManagerPlugin.py", line 239, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "C:\Users\WorkSpace\Desktop\ZeroNet-win-dist-win64\core\plugins\Bigfile\BigfilePlugin.py", line 791, in createArguments
    return super(ConfigPlugin, self).createArguments()
  File "C:\Users\WorkSpace\Desktop\ZeroNet-win-dist-win64\core\plugins\Benchmark\BenchmarkPlugin.py", line 347, in createArguments
    if self.getCmdlineValue("test") == "benchmark":
AttributeError: 'ConfigPlugin' object has no attribute 'getCmdlineValue'


/******************************/


So yeah, now when I try to run zeronet it dosen't open and it generates the issue.

**Comment by Noruka** [comment]
I think the issue is with peermessage plugin. I have done a clean install and when I go to install peermessage plugin it crashes the zite.

**Comment by purplesyringa** [comment]
It looks like it's a Name.YO bug actually. @HelloZeroNet can we please maintain backward compatibility??

**Comment by HelloZeroNet** [comment]
I just installed the plugin and I don't have the problem.

Can you please check core/src/Config.py if you have `def getCmdlineValue(self, key):` function there (line 465)? And whats the value of `self.rev =` (line16) for you?

**Comment by purplesyringa** [comment]
@HelloZeroNet Thanks for a quick response, at least I won't have to fix Name.YO... thanks.

**Comment by ghost** [comment]
My /opt/zeronet/src/Config.py has no getCmdlineValue method and my zeronet version is [0.7.1-1](https://aur.archlinux.org/packages/zeronet/)
```
self.version = "0.7.0"
self.rev = 4206
```

Seems not like an OS problem, but I am using the latest arch linux

My `journalctl -xe` output
```
Jan 14 17:24:04 archer zeronet[13806]: [17:24:04] - Libsecpk256k1 loaded: CompiledLib in 1.170s
Jan 14 17:24:05 archer zeronet[13806]: [17:24:05] - Unhandled exception: 'ConfigPlugin' object has no attribute 'getCmdlineValue'
Jan 14 17:24:05 archer zeronet[13806]: Traceback (most recent call last):
Jan 14 17:24:05 archer zeronet[13806]:   File "zeronet.py", line 16, in main
Jan 14 17:24:05 archer zeronet[13806]:     import main
Jan 14 17:24:05 archer zeronet[13806]:   File "/opt/zeronet/src/main.py", line 64, in <module>
Jan 14 17:24:05 archer zeronet[13806]:     config.loadPlugins()
Jan 14 17:24:05 archer zeronet[13806]:   File "/opt/zeronet/src/Config.py", line 464, in loadPlugins
Jan 14 17:24:05 archer zeronet[13806]:     ConfigPlugin(self)
Jan 14 17:24:05 archer zeronet[13806]:   File "/opt/zeronet/src/Config.py", line 459, in __init__
Jan 14 17:24:05 archer zeronet[13806]:     self.createArguments()
Jan 14 17:24:05 archer zeronet[13806]:   File "/opt/zeronet/plugins/Zeroname/UiRequestPlugin.py", line 30, in createArguments
Jan 14 17:24:05 archer zeronet[13806]:     return super(ConfigPlugin, self).createArguments()
Jan 14 17:24:05 archer zeronet[13806]:   File "/opt/zeronet/plugins/OptionalManager/OptionalManagerPlugin.py", line 239, in createArguments
Jan 14 17:24:05 archer zeronet[13806]:     return super(ConfigPlugin, self).createArguments()
Jan 14 17:24:05 archer zeronet[13806]:   File "/opt/zeronet/plugins/Bigfile/BigfilePlugin.py", line 791, in createArguments
Jan 14 17:24:05 archer zeronet[13806]:     return super(ConfigPlugin, self).createArguments()
Jan 14 17:24:05 archer zeronet[13806]:   File "/opt/zeronet/plugins/Benchmark/BenchmarkPlugin.py", line 347, in createArguments
Jan 14 17:24:05 archer zeronet[13806]:     if self.getCmdlineValue("test") == "benchmark":
Jan 14 17:24:05 archer zeronet[13806]: AttributeError: 'ConfigPlugin' object has no attribute 'getCmdlineValue'
Jan 14 17:24:05 archer zeronet[13806]: - Starting ZeroNet...
Jan 14 17:24:05 archer zeronet[13806]: ---
Jan 14 17:24:05 archer zeronet[13806]: Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-repo>
Jan 14 17:24:05 archer systemd[1]: zeronet.service: Succeeded.
```

EDIT: Even after removing /opt/zeronet and reinstalling, the Config.py file is still the same with no getCmdlineValue method. However I've found another Config.py in my data_dir  `/var/lib/zeronet/1uPDaT3uSyWAPdCv1WkMb5hBQjWSNNACf/core/src/Config.py` that:
- has the getCmdlineValue method in line 465
- self.version = "0.7.1"
- self.rev = 4325

I don't know if it is safe to move the second Config.py to /opt/zeronet/src/Config.py but I just did it and the log shows a successful start.
