### ISSUE TITLE
With master_seed false, is not possible to siteSign

### ISSUE THREAD

**Issue by ExtremelyMassiveStar** [HelloZeroNet/ZeroNet#2346]
- Starting ZeroNet...
- Libsecpk256k1 loaded: CompiledLib in 0.018s
- Patching sockets to tor socks proxy: 127.0.0.1:9050
- Version: 0.7.1 r4253, Python 3.7.5 (default, Oct 27 2019, 15:43:29) 
[GCC 9.2.1 20191022], Gevent: 1.4.0
SiteManager Deleting orphan site from content.db: 1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx #
- Signing site: 1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...
- Unhandled exception: encoding without a string argument
Traceback (most recent call last):
  File "zeronet.py", line 17, in main
    main.start()
  File "/opt/ZeroNet-py3/src/main.py", line 550, in start
    actions.call(config.action, action_kwargs)
  File "/opt/ZeroNet-py3/src/main.py", line 121, in call
    back = func(**kwargs)
  File "/opt/ZeroNet-py3/src/main.py", line 204, in siteSign
    site_data = user.getSiteData(address)
  File "/opt/ZeroNet/src/User/User.py", line 78, in getSiteData
    self.generateAuthAddress(address)
  File "/opt/ZeroNet-py3/src/util/Noparallel.py", line 57, in wrapper
    raise(err)
  File "/opt/ZeroNet-py3/src/util/Noparallel.py", line 50, in wrapper
    res = func(*args, **kwargs)
  File "/opt/ZeroNet-py3/src/User/User.py", line 63, in generateAuthAddress
    auth_privatekey = CryptBitcoin.hdPrivatekey(self.master_seed, address_id)
  File "/opt/ZeroNet-py3/src/Crypt/CryptBitcoin.py", line 69, in hdPrivatekey
    masterkey = btctools.bip32_master_key(bytes(seed, "ascii"))
TypeError: encoding without a string argument

**Comment by ExtremelyMassiveStar** [comment]
The warning of `SiteManager Deleting orphan site from content.db` is very annoying as well.

**Comment by ExtremelyMassiveStar** [comment]
@imachug you can reproduce it if you set this to False: https://github.com/HelloZeroNet/ZeroNet/commit/ee8e3c3c9c1fc7938f38502d85cd1ae2500683b5
