### ISSUE TITLE
Zeronet failure on boot.

### ISSUE THREAD

**Issue by TommyJerryMairo** [HelloZeroNet/ZeroNet#2375]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1
  * Operating system: ArchLinux
  * Web browser: N/A
  * Tor status: always
  * Opened port: no
  * Special configuration: N/A

#### Steps to reproduce:

  1. With an up-to-date ArchLinux environment, install [aur/zeronet](https://aur.archlinux.org/packages/zeronet)
  2. Run `systemctl start zeronet.service`
  3. Copy log with `journalctl --utc -e -u zeronet -b`

#### Error logs
```
-- Logs begin at Fri 2019-10-04 22:06:41 UTC, end at Tue 2019-12-24 10:54:04 UTC. --
Dec 24 08:37:48 ArchPad systemd[1]: Started Decentralized websites using Bitcoin crypto and the BitTorrent network.
Dec 24 08:38:25 ArchPad zeronet[1451]: [00:38:25] PluginManager Plugin AnnounceBitTorrent load error: ImportError: bad magic number in 'bencode': b'\x03\xf3\r\n' in PluginManager.py line 138 > AnnounceBitTorrent/__init__.py line 1 > AnnounceBitTorrent/AnnounceBitTorrentPlugin.py line 6
Dec 24 08:38:30 ArchPad zeronet[1451]: [00:38:30] PluginManager Plugin Bigfile load error: ImportError: bad magic number in 'merkletools': b'\x03\xf3\r\n' in PluginManager.py line 138 > Bigfile/__init__.py line 1 > Bigfile/BigfilePlugin.py line 20
Dec 24 08:38:36 ArchPad zeronet[1451]: [00:38:36] - Libsecp256k1 load failed: No module named 'base58', try to load OpenSSL
Dec 24 08:38:36 ArchPad zeronet[1451]: [00:38:36] - OpenSSL load failed: No module named 'bitcoin', falling back to slow bitcoin verify
Dec 24 08:38:36 ArchPad zeronet[1451]: [00:38:36] - Patching sockets to tor socks proxy: 127.0.0.1:9050
Dec 24 08:38:36 ArchPad zeronet[1451]: [00:38:36] - Version: 0.7.0 r4206, Python 3.8.0 (default, Oct 23 2019, 18:51:26)
Dec 24 08:38:36 ArchPad zeronet[1451]: [GCC 9.2.0], Gevent: 1.4.0
Dec 24 08:38:52 ArchPad zeronet[1451]: [00:38:52] - Unhandled exception: bad magic number in 'geventwebsocket': b'\x03\xf3\r\n'
Dec 24 08:38:52 ArchPad zeronet[1451]: Traceback (most recent call last):
Dec 24 08:38:52 ArchPad zeronet[1451]:   File "zeronet.py", line 17, in main
Dec 24 08:38:52 ArchPad zeronet[1451]:     main.start()
Dec 24 08:38:52 ArchPad zeronet[1451]:   File "/opt/zeronet/src/main.py", line 537, in start
Dec 24 08:38:52 ArchPad zeronet[1451]:     actions.call(config.action, action_kwargs)
Dec 24 08:38:52 ArchPad zeronet[1451]:   File "/opt/zeronet/src/main.py", line 121, in call
Dec 24 08:38:52 ArchPad zeronet[1451]:     back = func(**kwargs)
Dec 24 08:38:52 ArchPad zeronet[1451]:   File "/opt/zeronet/src/main.py", line 129, in main
Dec 24 08:38:52 ArchPad zeronet[1451]:     from Ui import UiServer
Dec 24 08:38:52 ArchPad zeronet[1451]:   File "/opt/zeronet/src/Ui/__init__.py", line 1, in <module>
Dec 24 08:38:52 ArchPad zeronet[1451]:     from .UiServer import UiServer
Dec 24 08:38:52 ArchPad zeronet[1451]:   File "/opt/zeronet/src/Ui/UiServer.py", line 10, in <module>
Dec 24 08:38:52 ArchPad zeronet[1451]:     from geventwebsocket.handler import WebSocketHandler
Dec 24 08:38:52 ArchPad zeronet[1451]: ImportError: bad magic number in 'geventwebsocket': b'\x03\xf3\r\n'
Dec 24 08:38:52 ArchPad zeronet[1451]: - Starting ZeroNet...
Dec 24 08:38:52 ArchPad zeronet[1451]: ---
Dec 24 08:38:52 ArchPad zeronet[1451]: Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md
Dec 24 08:38:56 ArchPad systemd[1]: zeronet.service: Succeeded.
```

**Comment by HelloZeroNet** [comment]
Usually this happens when the package is shipped with the *.pyc files that is compiled with different version of python that you have.
Looks like gevent-websocket package has the *pyc files included for python3.8:
https://www.archlinux.org/packages/community/any/python-gevent-websocket/
Based on the logs you also have Python 3.8, so you can try update that package, ~~but I think best would be if the package owner would remove the pyc files~~ (Update: after checking other python packages looks like it's pretty common to include pyc files, probably because of write permissions)

**Comment by frankenstein91** [comment]
same error on my system
```
-- Logs begin at Wed 2019-07-10 15:19:56 CEST, end at Sat 2020-01-11 18:07:59 CET. --
Jan 11 18:06:11 frank-nano systemd[1]: Started ZeroNet: a decentralized web platform.
Jan 11 18:06:12 frank-nano zeronet[907]: [18:06:12] PluginManager Plugin Bigfile load error: ImportError: bad magic number in 'merkletools': b'\x03\xf3\r\n' in PluginManager.py line 138 > Bigfile/__init__.py line 1 > Bigfile/BigfilePlugin>
Jan 11 18:06:12 frank-nano zeronet[907]: [18:06:12] - Libsecp256k1 load failed: No module named 'base58', try to load OpenSSL
Jan 11 18:06:12 frank-nano zeronet[907]: [18:06:12] - OpenSSL load failed: No module named 'bitcoin', falling back to slow bitcoin verify
Jan 11 18:06:12 frank-nano zeronet[907]: [18:06:12] - Version: 0.7.1 r4382, Python 3.8.1 (default, Dec 21 2019, 20:57:38)
Jan 11 18:06:12 frank-nano zeronet[907]: [GCC 9.2.0], Gevent: 1.4.0
Jan 11 18:06:13 frank-nano zeronet[907]: [18:06:13] - Unhandled exception: bad magic number in 'geventwebsocket': b'\x03\xf3\r\n'
Jan 11 18:06:13 frank-nano zeronet[907]: Traceback (most recent call last):
Jan 11 18:06:13 frank-nano zeronet[907]:   File "zeronet.py", line 17, in main
Jan 11 18:06:13 frank-nano zeronet[907]:     main.start()
Jan 11 18:06:13 frank-nano zeronet[907]:   File "/opt/zeronet/src/main.py", line 602, in start
Jan 11 18:06:13 frank-nano zeronet[907]:     actions.call(config.action, action_kwargs)
Jan 11 18:06:13 frank-nano zeronet[907]:   File "/opt/zeronet/src/main.py", line 133, in call
Jan 11 18:06:13 frank-nano zeronet[907]:     back = func(**kwargs)
Jan 11 18:06:13 frank-nano zeronet[907]:   File "/opt/zeronet/src/main.py", line 141, in main
Jan 11 18:06:13 frank-nano zeronet[907]:     from Ui import UiServer
Jan 11 18:06:13 frank-nano zeronet[907]:   File "/opt/zeronet/src/Ui/__init__.py", line 1, in <module>
Jan 11 18:06:13 frank-nano zeronet[907]:     from .UiServer import UiServer
Jan 11 18:06:13 frank-nano zeronet[907]:   File "/opt/zeronet/src/Ui/UiServer.py", line 9, in <module>
Jan 11 18:06:13 frank-nano zeronet[907]:     from geventwebsocket.handler import WebSocketHandler
Jan 11 18:06:13 frank-nano zeronet[907]: ImportError: bad magic number in 'geventwebsocket': b'\x03\xf3\r\n'
Jan 11 18:06:13 frank-nano zeronet[907]: - Starting ZeroNet...
Jan 11 18:06:13 frank-nano zeronet[907]: ---

```

**Comment by HelloZeroNet** [comment]
According to the log multiple modules failed to load, so the problem is not just with the geventwebsocket module. 
Until Python3.8 version of these modules get updated in the repo I suggest to use the mainline distribution for Linux: https://github.com/HelloZeroNet/ZeroNet-linux/archive/dist-linux64/ZeroNet-py3-linux64.tar.gz

**Comment by TommyJerryMairo** [comment]
FYI, this problem can be temporarily fixed by removing all those `.pyc` files from the Zeronet installation directory.

**Comment by TommyJerryMairo** [comment]
Another observation: those `.pyc` files are automatically generated by Zeronet when the Zeronet service back to running. It's probably a good idea to remove the `.pyc` file in the installation directory automatically every time after upgrading Zeronet.
