### ISSUE TITLE
ModuleNotFoundError: No module named 'pyaes'

### ISSUE THREAD

**Issue by GulshanBC** [HelloZeroNet/ZeroNet#2506]
- Please report snap specific errors (e.g. Read-only file system) to: https://github.com/mkg20001/zeronet-snap/issues
- and ZeroNet specific errors to: https://github.com/HelloZeroNet/ZeroNet/issues
- Linking plugins...
- Starting ZeroNet...
[16:33:00] PluginManager Plugin CryptMessage load error: ModuleNotFoundError: No module named 'pyaes' in PluginManager.py line 138 > CryptMessage/__init__.py line 1 > CryptMessage/CryptMessagePlugin.py line 7 > CryptBitcoin.py line 12 > __init__.py line 4 > 1 > aes.py line 4 > __init__.py line 1 > aes.py line 2
[16:33:01] - Version: 0.7.1 r4473, Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0], Gevent: 1.4.0
[16:33:01] - Unhandled exception: No module named 'pyaes'
Traceback (most recent call last):
  File "/home/gulshan/snap/zeronet/common/zeronet.py", line 17, in main
    main.start()
  File "/home/gulshan/snap/zeronet/common/src/main.py", line 602, in start
    actions.call(config.action, action_kwargs)
  File "/home/gulshan/snap/zeronet/common/src/main.py", line 133, in call
    back = func(**kwargs)
  File "/home/gulshan/snap/zeronet/common/src/main.py", line 141, in main
    from Ui import UiServer
  File "/home/gulshan/snap/zeronet/common/src/Ui/__init__.py", line 1, in <module>
    from .UiServer import UiServer
  File "/home/gulshan/snap/zeronet/common/src/Ui/UiServer.py", line 10, in <module>
    from .UiRequest import UiRequest
  File "/home/gulshan/snap/zeronet/common/src/Ui/UiRequest.py", line 14, in <module>
    from User import UserManager
  File "/home/gulshan/snap/zeronet/common/src/User/__init__.py", line 1, in <module>
    from .User import User
  File "/home/gulshan/snap/zeronet/common/src/User/User.py", line 9, in <module>
    from Crypt import CryptBitcoin
  File "/home/gulshan/snap/zeronet/common/src/Crypt/CryptBitcoin.py", line 12, in <module>
    from lib import sslcrypto
  File "/home/gulshan/snap/zeronet/common/src/lib/sslcrypto/__init__.py", line 4, in <module>
    from .openssl import aes, ecc, rsa
  File "/home/gulshan/snap/zeronet/common/src/lib/sslcrypto/openssl/__init__.py", line 1, in <module>
    from .aes import aes
  File "/home/gulshan/snap/zeronet/common/src/lib/sslcrypto/openssl/aes.py", line 4, in <module>
    from ..fallback.aes import aes as fallback_aes
  File "/home/gulshan/snap/zeronet/common/src/lib/sslcrypto/fallback/__init__.py", line 1, in <module>
    from .aes import aes
  File "/home/gulshan/snap/zeronet/common/src/lib/sslcrypto/fallback/aes.py", line 2, in <module>
    import pyaes
ModuleNotFoundError: No module named 'pyaes'

I installed it on Ubuntu 18.04 but the icon didn't appear in app launcher.
I searched it using: which zeronet
It showed: /snap/bin/zeronet
on running zeronet in terminal, it presented me with above message!!

**Comment by purplesyringa** [comment]
Okay, this problem is caused by a missing `from lib` in sslcrypto. Adding it will fix the problem and I'd recommend it as a hotfix, but it'll also make sslcrypto update more difficult. @HelloZeroNet Do you know why is `from lib` is required in the first place? Perhaps we should fix the problem instead of making hacks.

**Comment by GulshanBC** [comment]
@imachug how do I add sslcrypto, please guide me

**Comment by HelloZeroNet** [comment]
it happens because the snap package does not inserts src/lib to sys.path:

https://github.com/ZeroNerds/zeronet-snap/blob/master/src/scripts/launcher.py#L142

vs

https://github.com/HelloZeroNet/ZeroNet/blob/py3/zeronet.py#L125

So the easiest fix would be add it to the snap package's launcher.py

or call zeronet.start() instead of zeronet.main() if `os.environ['SNAP_USER_COMMON'] == os.path.dirname(os.path.abspath(__file__))`

**Comment by mkg20001** [comment]
Should be released soon

**Comment by HelloZeroNet** [comment]
Thanks, can anyone confirm it's working? (For some reasons Snap images does not work on my VPS)

**Comment by GulshanBC** [comment]
@HelloZeroNet now, its working!!
