### ISSUE TITLE
Don't use "master_seed"! master_seed "False" in config, users.json without master_seed will result in "siteSign" failure, missing auth_addresses in users.json, updates not working!! :/

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2512]
```
Traceback (most recent call last):
  File "zeronet.py", line 17, in main
    main.start()
  File "/opt/zero/src/main.py", line 589, in start
    actions.call(config.action, action_kwargs)
  File "/opt/zero/src/main.py", line 123, in call
    back = func(**kwargs)
  File "/opt/zero/src/main.py", line 206, in siteSign
    site_data = user.getSiteData(address)
  File "/opt/zero/src/User/User.py", line 78, in getSiteData
    self.generateAuthAddress(address)
  File "/opt/zero/src/util/Noparallel.py", line 57, in wrapper
    raise(err)
  File "/opt/zero/src/util/Noparallel.py", line 50, in wrapper
    res = func(*args, **kwargs)
  File "/opt/zero/src/User/User.py", line 63, in generateAuthAddress
    auth_privatekey = CryptBitcoin.hdPrivatekey(self.master_seed, address_id)
  File "/opt/zero/src/Crypt/CryptBitcoin.py", line 69, in hdPrivatekey
    masterkey = btctools.bip32_master_key(bytes(seed, "ascii"))
TypeError: encoding without a string argument
```

I urge everyone who using ZeroNet **not to use "master_seed"** at all! @HelloZeroNet and @imachug working on Windows and Google Chrome and they have been notified prior to turn "master_seed" off!

**Comment by SatoshiNakamotoSwitzerland** [comment]
@HelloZeroNet I have way over 200 zites and your "master_seed" messed up my users.json badly. You turned on the master_seed without asking anyone about it. Well, now you gonna turn it off!

**Comment by SatoshiNakamotoSwitzerland** [comment]
absolutely bullshit this master seed shit, now you gonna fix this genius @HelloZeroNet

**Comment by SatoshiNakamotoSwitzerland** [comment]
"123BiglonghardstickDeepinyourass": {
    "certs": {},
    "master_seed": "mymomishungarianfascistandmynameis1tamaskocsishex",
    "settings": {},
    "sites": {

**Comment by purplesyringa** [comment]
> absolutely bullshit this master seed shit, now you gonna fix this genius

It helps to recover your private keys. You can always disable master seed if you don't want to. Also, creating sites via terminal was never recommended and the modification only changed the behavour when using console, not browser UI, so saying that this change affected users much is wrong. And if you know how to use terminal, perhaps you know how to fix `users.json` as well (how the heck did master_seed manage to corrupt it though?).

**Comment by ghost** [comment]
@imachug I only want site address and privatekey in users.json which is not possible. If master_seed is turned off than `siteSign` will fail!

**Comment by purplesyringa** [comment]
> If master_seed is turned off than `siteSign` will fail!

Are you talking about CLI `siteSign` command or ZeroNet UI?

**Comment by ghost** [comment]
CLI

**Comment by ghost** [comment]
@imachug 
![notcool](https://user-images.githubusercontent.com/63308648/78836016-bf756b00-79e0-11ea-95ea-5ade8cd4755e.png)

**Comment by ghost** [comment]
@HelloZeroNet @imachug okay, now my log is full of messages regarding auth_address, no other than 1Hello has auth_address in my users.json. :roll_eyes: 

Is there any way to generate those auth_addresses? :thinking: 

Please turn off master_seed, if user need than it should request that. users.json seems all the time have master_seed even if in config that is turned off. Removing master_seed from users.json manually will result again in failure of siteSign. Additionally, I don't see any option to regenerate auth_address and so the log is filled with error messages.

example: 
`KeyError: 'auth_address' in UiWebsocket.py line 79 > UiWebsocket.py line 232 > UiWebsocket.py line 348 > Newsfeed/NewsfeedPlugin.py line 14 > UiWebsocket.py line 264 > User.py line 115 
 {"cmd":"siteInfo","params":{},"id":1000001}
`

**updates not working** and because auth_address is missing not even see the sites in UI...

**Comment by ghost** [comment]
sitePublish also doesn't work!!! Congratulations @HelloZeroNet @shortcutme @imachug @filips123 you just destroyed ZeroNet with your stupid "master_seed" mania! 

Again, **turn off master_seed!** Clean up users.json and encourage everyone to **BACK UP PRIVATEKEYS!**

**Comment by purplesyringa** [comment]
> Clean up users.json and encourage everyone to BACK UP PRIVATEKEYS!

We already do.
