### ISSUE TITLE
Unhandled exception: ImportError: cannot import name 'ThreadPool' from 'util' (C:\Users\PC PORTABLE\Desktop\ZeroNet-win-dist-win64\ZeroNet-win-dist-win64\core\src\util\__init__.py)

### ISSUE THREAD

**Issue by djukonline** [HelloZeroNet/ZeroNet#2533]
### Step 1: Please describe your environment

  * ZeroNet version: _____
  * Operating system: _____win10
  * Web browser: _____brave
  * Tor status: not available
  * Opened port: yes
  * Special configuration: ____
Traceback (most recent call last):
  File "C:\Users\PC PORTABLE\Desktop\ZeroNet-win-dist-win64\ZeroNet-win-dist-win64\core\zeronet.py", line 16, in main
    import main
  File "C:\Users\PC PORTABLE\Desktop\ZeroNet-win-dist-win64\ZeroNet-win-dist-win64\core\src\main.py", line 36, in <module>
    try:
  File "C:\Users\PC PORTABLE\Desktop\ZeroNet-win-dist-win64\ZeroNet-win-dist-win64\core\src\util\__init__.py", line 2, in <module>
    from .Noparallel import Noparallel
  File "C:\Users\PC PORTABLE\Desktop\ZeroNet-win-dist-win64\ZeroNet-win-dist-win64\core\src\util\Noparallel.py", line 5, in <module>
    from . import ThreadPool
ImportError: cannot import name 'ThreadPool' from 'util' (C:\Users\PC PORTABLE\Desktop\ZeroNet-win-dist-win64\ZeroNet-win-dist-win64\core\src\util\__init__.py)

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
Did it worked before?
Have you updated the client recently?
Do you have ThreadPool.py file in `\ZeroNet-win-dist-win64\ZeroNet-win-dist-win64\core\src\util\` directory?

**Comment by djukonline** [comment]
After reinstall! it's ok!
