### ISSUE TITLE
Gevent 20.6.2 gevent._threading.Queue compatibility issue

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#2574]
```
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "e:\Do\ZeroNet-py3\src\util\ThreadPool.py", line 144, in run
    func, args, kwargs, event_done = self.pool.apply(self.queue_call.get)
  File "C:\Python3\lib\site-packages\gevent\pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src\\gevent\\event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src\\gevent\\event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "C:\Python3\lib\site-packages\gevent\_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "C:\Python3\lib\site-packages\gevent\threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
TypeError: get() missing 1 required positional argument: 'cookie'
```

**Comment by HelloZeroNet** [comment]
Fixed in Rev4493 https://github.com/HelloZeroNet/ZeroNet/commit/ea6016d004eeb1c8f2927d171fae615d1afc7d8e
