### ISSUE TITLE
Unhandled exception: ModuleNotFoundError: No module named 'msgpack'

### ISSUE THREAD

**Issue by TomerGamerTV** [HelloZeroNet/ZeroNet#2620]
### Step 1: Please describe your environment

  * ZeroNet version: latest
  * Operating system: windows 10 pro
  * Web browser: chrome
  * Tor status: always
  * Opened port: yes
  * Special configuration: ____

### Step 2: Describe the problem:
im trying to make a website but its just crashing after im saying yes
#### Steps to reproduce:

  1.python .\zeronet.py siteCreate
  2.say yes
  3. crash

#### Observed Results:

```
 Traceback (most recent call last):
  File ".\zeronet.py", line 17, in main
    main.start()
  File "D:\Downloads\ZeroNet-win-dist-win64\core\src\main.py", line 537, in start
    actions.call(config.action, action_kwargs)
  File "D:\Downloads\ZeroNet-win-dist-win64\core\src\main.py", line 121, in call
    back = func(**kwargs)
  File "D:\Downloads\ZeroNet-win-dist-win64\core\src\main.py", line 164, in siteCreate
    from Site.Site import Site
  File "D:\Downloads\ZeroNet-win-dist-win64\core\src\Site\Site.py", line 26, in <module>
    from File import FileServer
  File "D:\Downloads\ZeroNet-win-dist-win64\core\src\File\__init__.py", line 1, in <module>
    from .FileServer import FileServer
  File "D:\Downloads\ZeroNet-win-dist-win64\core\src\File\FileServer.py", line 13, in <module>
    from .FileRequest import FileRequest
  File "D:\Downloads\ZeroNet-win-dist-win64\core\src\File\FileRequest.py", line 14, in <module>
    from util import Msgpack
  File "D:\Downloads\ZeroNet-win-dist-win64\core\src\util\Msgpack.py", line 5, in <module>
    import msgpack
ModuleNotFoundError: No module named 'msgpack'
```
![image](https://user-images.githubusercontent.com/44266242/94344629-51be0980-0029-11eb-93fb-bf079ee9f2c7.png)

#### Expected Results:

  enable my site or something like that

**Comment by purplesyringa** [comment]
Have you installed the dependencies via `pip -r requirements.txt`?

**Comment by TomerGamerTV** [comment]
> Have you installed the dependencies via `pip -r requirements.txt`?

i think i installed now but im getting something like this
![image](https://user-images.githubusercontent.com/44266242/94344733-f9d3d280-0029-11eb-99b6-6ffdd00396af.png)

**Comment by TomerGamerTV** [comment]
> Have you installed the dependencies via `pip -r requirements.txt`?

i think its worked now i installed the site, I won't close the issue i will wait around 1 or 2 days and then will close

**Comment by TomerGamerTV** [comment]
![image](https://user-images.githubusercontent.com/44266242/94345080-22f56280-002c-11eb-93e3-f8637b84cfa4.png)
now i cant update the sign the site

**Comment by HelloZeroNet** [comment]
The easiest way is by using the bundled libs:

 - `cd D:\Downloads\ZeroNet-win-dist-win64\`
 - `lib\zeronet.cmd siteCreate`
