### ISSUE TITLE
Hundreds of FileNotFoundError after deleting sites manually from data folder. 

### ISSUE THREAD

**Issue by JabbaDesilijicTiure** [HelloZeroNet/ZeroNet#2644]
```
FileNotFoundError: [Errno 2] No such file or directory: './data/1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27/content.json'
[20:26:36] - Unhandled exception: FileNotFoundError: [Errno 2] No such file or directory: './data/1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27/data/users/content.json' in threadpool.py line 142 > SiteStorage.py line 421 > 290
Traceback (most recent call last):
  File "./lib/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "./src/Site/SiteStorage.py", line 421, in loadJson
    with self.open(inner_path, "r", encoding="utf8") as file:
  File "./src/Site/SiteStorage.py", line 290, in open
    return open(file_path, mode, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: './data/1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27/data/users/content.json'
[20:26:36] - Unhandled exception: FileNotFoundError: [Errno 2] No such file or directory: './data/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/content.json' in threadpool.py line 142 > SiteStorage.py line 421 > 290
Traceback (most recent call last):
  File "./lib/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "./src/Site/SiteStorage.py", line 421, in loadJson
    with self.open(inner_path, "r", encoding="utf8") as file:
  File "./src/Site/SiteStorage.py", line 290, in open
    return open(file_path, mode, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: './data/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/content.json'
[20:26:36] - Unhandled exception: FileNotFoundError: [Errno 2] No such file or directory: './data/1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27/content.json' in threadpool.py line 142 > SiteStorage.py line 421 > 290
Traceback (most recent call last):
  File "./lib/python3.8/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "./src/Site/SiteStorage.py", line 421, in loadJson
    with self.open(inner_path, "r", encoding="utf8") as file:
  File "./src/Site/SiteStorage.py", line 290, in open
    return open(file_path, mode, **kwargs)
```

Removing the deleted sites from the data folder will download them again.. Manually need to edit and delete entries regarding the deleted sites from sites.json, users.json and throw out content.db will fix this...

**Comment by imachug** [comment]
> Removing the deleted sites from the data folder will download them again

That ZeroNet automatically redownloads deleted sites is actually a feature -- it allows you to backup ZeroNet code and data without backing up some popular sites that will be automatically redownloaded when you visit them.

> Manually need to edit and delete entries regarding the deleted sites from sites.json, users.json and throw out content.db will fix this...

Just clicking 'Delete' in site sidebar or on ZeroHello should be enough.

**Comment by JabbaDesilijicTiure** [comment]
@imachug here is the thing. I don't have neither homepage nor sidebar. :smile:

**Comment by imachug** [comment]
What do you have then? A fork with no admin page and sidebar plugin disabled? In this case, if you disable half of the features, I'm afraid I can't help.

On the other hand, maybe you still have the CLI? Try siteDelete command then.

**Comment by JabbaDesilijicTiure** [comment]
@imachug 
> A fork with no admin page and sidebar plugin disabled?

That is correct. In fact my fork don't have most of the plugins either. The admin page what you call "HelloZero_" is **not part of the software!**

siteDelete returns: **PermissionError: [Errno 13] Permission denied**

**Comment by JabbaDesilijicTiure** [comment]
The permission error fixed. Now I get:

`zeronet.py: error: argument action: invalid choice: 'siteDelete' (choose from 'main', 'siteCreate', 'siteNeedFile', 'siteDownload', 'siteSign', 'sitePublish', 'siteVerify', 'siteCmd', 'dbRebuild', 'dbQuery', 'peerPing', 'peerGetFile', 'peerCmd', 'cryptSign', 'cryptVerify', 'cryptGetPrivatekey', 'getConfig', 'testConnection', 'testAnnounce', 'test')
`

**Comment by imachug** [comment]
Yeah we don't have easy to use CLI... Try this then:

```
python3 zeronet.py siteCmd address_of_homepage siteDelete your_site_address
```

`address_of_homepage` is usually `1HeLLo...` but as you don't have ZeroHello, it's your homepage address.

I admit that this is cumbersome, hopefully #2651 will fix that.

**Comment by JabbaDesilijicTiure** [comment]
@imachug **socks.GeneralProxyError: Socket error: 0x01: General SOCKS server failure**

**Comment by imachug** [comment]
> your command returns

Now that is really weird. Can you please send me the whole traceback?

**Comment by JabbaDesilijicTiure** [comment]
@imachug here: 
```

Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    main.start()
  File "path/src/main.py", line 767, in start
    actions.call(config.action, action_kwargs)
  File "path/src/main.py", line 174, in call
    back = func(**kwargs)
  File "path/src/main.py", line 490, in siteCmd
    ws = self.getWebsocket(site)
  File "path/src/main.py", line 514, in getWebsocket
    ws = websocket.create_connection(ws_address)
  File "env/lib/python3.8/site-packages/websocket/_core.py", line 515, in create_connection
    websock.connect(url, **options)
  File "env/lib/python3.8/site-packages/websocket/_core.py", line 222, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "env/lib/python3.8/site-packages/websocket/_http.py", line 121, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "env/lib/python3.8/site-packages/websocket/_http.py", line 193, in _open_socket
    raise error
  File "env/lib/python3.8/site-packages/websocket/_http.py", line 176, in _open_socket
    sock.connect(address)
  File "env/lib/python3.8/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "env/lib/python3.8/site-packages/socks.py", line 814, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x01: General SOCKS server failure
```

**Comment by imachug** [comment]
Apparently we're not starting ZeroNet in case it's not running when handling `siteCmd`, and the error message is completely incomprehensible when `tor=always` or `proxy` are set. Can you try running the same command while ZeroNet is running in background?

**Comment by JabbaDesilijicTiure** [comment]
The same result.
