### ISSUE TITLE
Loosing multi user functionality without master master seed: Migrating zeronet fail, restoring sites and private keys in users.json will also result in failure.

### ISSUE THREAD

**Issue by JabbaDesilijicTiure** [HelloZeroNet/ZeroNet#2659]
Migrating the content of the users.json namely the site address and the corresponding private key to a new user.json file while leaving out master_seed, auth_address, and auth_privatekey will result in the following error while signing:

```
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    main.start()
  File "/path/src/main.py", line 767, in start
    actions.call(config.action, action_kwargs)
  File "/path/src/main.py", line 174, in call
    back = func(**kwargs)
  File "/path/src/main.py", line 293, in siteSign
    site_data = user.getSiteData(address)
  File "/path/src/User/User.py", line 91, in getSiteData
    self.generateAuthAddress(address)
  File "/path/src/util/Noparallel.py", line 75, in wrapper
    raise (err)
  File "/path/src/util/Noparallel.py", line 68, in wrapper
    res = func(*args, **kwargs)
  File "/path/src/User/User.py", line 68, in generateAuthAddress
    auth_privatekey = CryptBitcoin.hdPrivatekey(self.master_seed, address_id)
  File "/path/src/Crypt/CryptBitcoin.py", line 61, in hdPrivatekey
    privatekey_bin = sslcurve.derive_child(seed.encode(), child % 100000000)
AttributeError: 'NoneType' object has no attribute 'encode'
---
```

Master seed is not used by me at all so having requirement to use it in users.json makes no sense. Now what? I will pull out the master seed from thin air? Hmm @imachug ?

**Comment by JabbaDesilijicTiure** [comment]
@HelloZeroNet if the master seed is turned off while siteCreate the user.json will be empty and so there will be no auth_address at all, this way ZeroNet loosing its multi user functionality. Adding sites and they private keys to user.json will complain about the master seed meaning that users can't restore they private keys or use users.json while signing the site with siteSign.

@imachug this is not cool.

**Comment by JabbaDesilijicTiure** [comment]
Adding a new master seed to users.json will **not** create magically the auth_address for any site listed in that file.

**Comment by JabbaDesilijicTiure** [comment]
Solved: https://github.com/HelloZeroNet/ZeroNet/issues/2667#issuecomment-720075806
