### ISSUE TITLE
48 warnings (rev4538)

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2662]
I noticed this after trying to upgrade ZeroNet revision on ZeroNet Mobile, which doesn't work yet. IDK if this bug report belongs here or not.

```
Displaying 72 of 72 lines found in the last 8kB of the log file. (8kB total)
[2020-10-29 08:54:32,139] ERROR - Unhandled exception
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/data/data/in.canews.zeronet/files/ZeroNet-py3/src/File/FileServer.py", line 343, in wakeupWatcher
    last_my_ips = socket.gethostbyname_ex('')[2]
  File "/data/data/in.canews.zeronet/files/usr/lib/python3.8/site-packages/gevent/_socketcommon.py", line 176, in gethostbyname_ex
    return get_hub().resolver.gethostbyname_ex(hostname)
  File "/data/data/in.canews.zeronet/files/usr/lib/python3.8/site-packages/gevent/resolver/thread.py", line 62, in gethostbyname_ex
    return self.pool.apply(_socket.gethostbyname_ex, args)
  File "/data/data/in.canews.zeronet/files/usr/lib/python3.8/site-packages/gevent/pool.py", line 159, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 296, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 286, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 266, in gevent._event.AsyncResult._raise_exception
  File "src/gevent/event.py", line 211, in gevent._event.AsyncResult.exc_info.__get__
  File "/data/data/in.canews.zeronet/files/usr/lib/python3.8/site-packages/gevent/_tblib.py", line 371, in g
    return f(a)
  File "/data/data/in.canews.zeronet/files/usr/lib/python3.8/site-packages/gevent/_tblib.py", line 432, in load_traceback
    return loads(s)
  File "/data/data/in.canews.zeronet/files/usr/lib/python3.8/site-packages/gevent/_tblib.py", line 337, in unpickle_traceback
    return ret.as_traceback()
  File "/data/data/in.canews.zeronet/files/usr/lib/python3.8/site-packages/gevent/_tblib.py", line 202, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
[2020-10-29 15:54:15,799] ERROR Site:12cm58..kWYd [MISSING] data/users/12kgNNnBaR3s7bN761BCQtkzSC7EbrK2Jd/data.json
[2020-10-29 15:54:18,559] ERROR Site:12rTbt..pm8S [MISSING] data/users/1FPqeZshQM57dVG7CErp8jcsQcXMY16RzX/data.json
[2020-10-29 15:54:18,992] ERROR Site:18FheQ..NJ8d [MISSING] data/users/1Fmq99GjF68h8iEh8fjTvx45ueC538EmSa/data.json
[2020-10-29 15:54:19,032] ERROR Site:18FheQ..NJ8d [MISSING] data/users/1KNe8oqdHjEAYSEZByAikQi66GjZB1rSxL/data.json
[2020-10-29 15:54:19,037] ERROR Site:18FheQ..NJ8d [MISSING] data/users/1Kj8ctbkj4SCAtwzL1Y4vQojD5ByzYV8nQ/data.json
[2020-10-29 15:54:19,048] ERROR Site:18FheQ..NJ8d [MISSING] data/users/1LeMoKRoASd3geqkk1rj9Ls8dDgev6fYQv/data.json
[2020-10-29 15:54:20,094] ERROR Site:1ABFCa..bz3m [MISSING] data/users/1GA316mzCizSQDfMF6xizYVATuZpkpPQn2/data.json
[2020-10-29 15:54:20,483] ERROR Site:1AbRRD..tMJZ [MISSING] data/users/1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS/content_goodquite.json
[2020-10-29 15:54:20,487] ERROR Site:1AbRRD..tMJZ [MISSING] data/users/1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS/data - kopie.json
[2020-10-29 15:54:20,488] ERROR Site:1AbRRD..tMJZ [MISSING]
```

**Comment by HelloZeroNet** [comment]
Based on https://github.com/gevent/gevent/issues/1491 it happens when using Python 3.8 with gevent 1.4 or older
