### ISSUE TITLE
Unable to start after Rev4548

### ISSUE THREAD

**Issue by rex4539** [HelloZeroNet/ZeroNet#2672]
```
[09:57:30] - Unhandled exception: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/Users/rex/Library/Application Support/ZeroNet/core/zeronet.py", line 17, in main
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/main.py", line 602, in start
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/main.py", line 133, in call
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/main.py", line 141, in main
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/Ui/__init__.py", line 1, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/Ui/UiServer.py", line 10, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/Ui/UiRequest.py", line 14, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/User/__init__.py", line 1, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/User/User.py", line 9, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/Crypt/CryptBitcoin.py", line 14, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/lib/sslcrypto/__init__.py", line 4, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/lib/sslcrypto/openssl/__init__.py", line 1, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/lib/sslcrypto/openssl/aes.py", line 5, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/lib/sslcrypto/openssl/library.py", line 83, in <module>
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/lib/sslcrypto/openssl/library.py", line 74, in discover_library
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/lib/sslcrypto/openssl/library.py", line 22, in discover_paths
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/util/OpensslFindPatch.py", line 61, in findLibraryPatched
  File "/Users/rex/Library/Application Support/ZeroNet/core/src/util/OpensslFindPatch.py", line 51, in getOpensslPath
[...]
File "/Users/rex/Library/Application Support/ZeroNet/core/src/util/OpensslFindPatch.py", line 64, in findLibraryPatched
  File "ctypes/util.pyc", line 78, in find_library
  File "ctypes/macholib/dyld.pyc", line 124, in dyld_find
  File "ctypes/macholib/dyld.pyc", line 84, in dyld_override_search
  File "ctypes/macholib/dyld.pyc", line 48, in dyld_library_path
  File "ctypes/macholib/dyld.pyc", line 34, in dyld_env
  File "_collections_abc.pyc", line 660, in get
  File "os.pyc", line 675, in __getitem__
  File "os.pyc", line 752, in encode
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by rex4539** [comment]
Introduced by c515e26cd6b5e6363a4ce4f4e5c062044c1779d4.

**Comment by purplesyringa** [comment]
@shortcutme Please use `sslcrypto.openssl.discover` API.

**Comment by JabbaDesilijicTiure** [comment]
@HelloZeroNet I think you need to reverse that pr, why the hell anyone would need to use API? Either ZeroNet works or not, you don't need to use the API...

**Comment by JabbaDesilijicTiure** [comment]
@imachug :+1: :partying_face:

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be fixed in Rev4549 https://github.com/HelloZeroNet/ZeroNet/commit/57dda4e6d6c20bd795ecaa18902289d516a87c6d

To fix it manually you have to replace the file /Users/rex/Library/Application Support/ZeroNet/core/src/util/OpensslFindPatch.py

with

https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/src/util/OpensslFindPatch.py

**Comment by HelloZeroNet** [comment]
> @shortcutme Please use `sslcrypto.openssl.discover` API.

I  give it an another look, but for some reasons it did not worked well as it was before.

Update, opened an issue for it at https://github.com/imachug/sslcrypto/issues/15
