### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by OSRebooting** [HelloZeroNet/ZeroNet#2674]
### Step 1: Please describe your environment

  * ZeroNet version: ___	nofish/zeronet:latest__
  * Operating system: __Linux Docker 19.03___
  * Web browser: _____
  * Tor status: not available/always/disabled
  * Opened port: yes
  * Special configuration: ____

### Step 2: Describe the problem:
RecursionError: maximum recursion depth exceeded while calling a Python object

#### Steps to reproduce:

  1. ___docker run -d -e "ENABLE_TOR=true" -v data:/root/data -p 15441:15441 -p 127.0.0.1:43110:43110 nofish/zeronet__
  
  
#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

```
Nov 05 09:53:05.123 [notice] Tor 0.4.1.9 running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1g, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.,
Nov 05 09:53:05.123 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning,
Nov 05 09:53:05.123 [notice] Read configuration file "/etc/tor/torrc".,
Nov 05 09:53:05.128 [notice] Opening Socks listener on 127.0.0.1:9050,
Nov 05 09:53:05.128 [notice] Opened Socks listener on 127.0.0.1:9050,
Nov 05 09:53:05.128 [notice] Opening Control listener on 127.0.0.1:9051,
Nov 05 09:53:05.128 [notice] Opened Control listener on 127.0.0.1:9051,
Nov 05 09:53:05.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.,
Nov 05 09:53:05.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.,
Nov 05 09:53:05.000 [warn] You are running Tor as root. You don't need to, and you probably shouldn't.,
Nov 05 09:53:05.000 [notice] Bootstrapped 0% (starting): Starting,
Nov 05 09:53:05.000 [notice] Starting with guard context "default",
[09:53:05] PluginManager Plugin CryptMessage load error: RecursionError: maximum recursion depth exceeded while calling a Python object in PluginManager.py line 138 > CryptMessage/__init__.py line 1 > CryptMessage/CryptMessagePlugin.py line 7 > CryptBitcoin.py line 14 > __init__.py line 4 > 1 > aes.py line 5 > library.py line 83 > 74 > 64 > OpensslFindPatch.py line 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 61 > 51 > 64 > ctypes/util.py line 286 > ... > glob.py line 129,
[09:53:05] - Version: 0.7.2 r4548, Python 3.8.2 (default, Jul 18 2020, 19:35:03) ,
[GCC 9.2.0], Gevent: 20.9.0,
[09:53:05] - Unhandled exception: maximum recursion depth exceeded while calling a Python object,
Traceback (most recent call last):,
  File "zeronet.py", line 17, in main,
    main.start(),
  File "/root/src/main.py", line 602, in start,
    actions.call(config.action, action_kwargs),
  File "/root/src/main.py", line 133, in call,
    back = func(**kwargs),
  File "/root/src/main.py", line 141, in main,
    from Ui import UiServer,
  File "/root/src/Ui/__init__.py", line 1, in <module>,
    from .UiServer import UiServer,
  File "/root/src/Ui/UiServer.py", line 10, in <module>,
    from .UiRequest import UiRequest,
  File "/root/src/Ui/UiRequest.py", line 14, in <module>,
    from User import UserManager,
  File "/root/src/User/__init__.py", line 1, in <module>,
    from .User import User,
  File "/root/src/User/User.py", line 9, in <module>,
    from Crypt import CryptBitcoin,
  File "/root/src/Crypt/CryptBitcoin.py", line 14, in <module>,
    from lib import sslcrypto,
  File "/root/src/lib/sslcrypto/__init__.py", line 4, in <module>,
    from .openssl import aes, ecc, rsa,
  File "/root/src/lib/sslcrypto/openssl/__init__.py", line 1, in <module>,
    from .aes import aes,
  File "/root/src/lib/sslcrypto/openssl/aes.py", line 5, in <module>,
    from .library import lib, openssl_backend,
  File "/root/src/lib/sslcrypto/openssl/library.py", line 83, in <module>,
    lib = discover_library(),
  File "/root/src/lib/sslcrypto/openssl/library.py", line 74, in discover_library,
    for path in discover_paths():,
  File "/root/src/lib/sslcrypto/openssl/library.py", line 64, in discover_paths,
    openssl_paths.append(ctypes.util.find_library("ssl")),
  File "/root/src/util/OpensslFindPatch.py", line 61, in findLibraryPatched,
    lib_path = getOpensslPath(),[..]
  File "/root/src/util/OpensslFindPatch.py", line 51, in getOpensslPath,
    ctypes.util.find_library('ssl.so') or ctypes.util.find_library('ssl') or,
  File "/root/src/util/OpensslFindPatch.py", line 64, in findLibraryPatched,
    return find_library_original(name),
  File "/usr/lib/python3.8/ctypes/util.py", line 286, in find_library,
    for f in glob('{0}{1}'.format(prefix, suffix)):,
  File "/usr/lib/python3.8/glob.py", line 21, in glob,
    return list(iglob(pathname, recursive=recursive)),
  File "/usr/lib/python3.8/glob.py", line 74, in _iglob,
    for name in glob_in_dir(dirname, basename, dironly):,
  File "/usr/lib/python3.8/glob.py", line 82, in _glob1,
    names = list(_iterdir(dirname, dironly)),
  File "/usr/lib/python3.8/glob.py", line 123, in _iterdir,
    with os.scandir(dirname) as it:,
RecursionError: maximum recursion depth exceeded while calling a Python object,
- Starting ZeroNet...,
---,
Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md,
```

#### Expected Results:

  * What did you expect to happen?

**Comment by jlxip** [comment]
Please, edit the issue and add a pastebin link instead of that flood.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be fixed in Rev4549 https://github.com/HelloZeroNet/ZeroNet/commit/57dda4e6d6c20bd795ecaa18902289d516a87c6d

To fix it manually you have to replace the file /root/src/util/OpensslFindPatch.py

with

https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/src/util/OpensslFindPatch.py
