### ISSUE TITLE
PluginManager Plugin CryptMessage load error

### ISSUE THREAD

**Issue by siddonj** [HelloZeroNet/ZeroNet#2676]
[15:49:58] - Version: 0.7.2 r4548, Python 3.8.2 (default, Jul 18 2020, 19:35:03) ,
[GCC 9.2.0], Gevent: 20.9.0,
[15:49:58] - Unhandled exception: maximum recursion depth exceeded while calling a Python object,
Traceback (most recent call last):,
  File "zeronet.py", line 17, in main,
    main.start(),
  File "/root/src/main.py", line 602, in start,
    actions.call(config.action, action_kwargs),
  File "/root/src/main.py", line 133, in call,
    back = func(**kwargs),
  File "/root/src/main.py", line 141, in main,
    from Ui import UiServer,
  File "/root/src/Ui/__init__.py", line 1, in <module>,
    from .UiServer import UiServer,
  File "/root/src/Ui/UiServer.py", line 10, in <module>,
    from .UiRequest import UiRequest,
  File "/root/src/Ui/UiRequest.py", line 14, in <module>,
    from User import UserManager,
  File "/root/src/User/__init__.py", line 1, in <module>,
    from .User import User,
  File "/root/src/User/User.py", line 9, in <module>,
    from Crypt import CryptBitcoin,
  File "/root/src/Crypt/CryptBitcoin.py", line 14, in <module>,
    from lib import sslcrypto,
  File "/root/src/lib/sslcrypto/__init__.py", line 4, in <module>,
    from .openssl import aes, ecc, rsa,
  File "/root/src/lib/sslcrypto/openssl/__init__.py", line 1, in <module>,
    from .aes import aes,
  File "/root/src/lib/sslcrypto/openssl/aes.py", line 5, in <module>,
    from .library import lib, openssl_backend,
  File "/root/src/lib/sslcrypto/openssl/library.py", line 83, in <module>,
    lib = discover_library(),
  File "/root/src/lib/sslcrypto/openssl/library.py", line 74, in discover_library,
    for path in discover_paths():,
  File "/root/src/lib/sslcrypto/openssl/library.py", line 64, in discover_paths,
    openssl_paths.append(ctypes.util.find_library("ssl")),
  File "/root/src/util/OpensslFindPatch.py", line 61, in findLibraryPatched,
    lib_path = getOpensslPath(),
  File "/root/src/util/OpensslFindPatch.py", line 51, in getOpensslPath,
    ctypes.util.find_library('ssl.so') or ctypes.util.find_library('ssl') or,
  File "/root/src/util/OpensslFindPatch.py", line 61, in findLibraryPatched,
    lib_path = getOpensslPath(),

**Comment by HelloZeroNet** [comment]
This error has been fixed in rev4549 https://github.com/HelloZeroNet/ZeroNet/commit/57dda4e6d6c20bd795ecaa18902289d516a87c6d

To fix it manually you have to replace the file /root/src/util/OpensslFindPatch.py

with

https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/src/util/OpensslFindPatch.py
