### ISSUE TITLE
zeronet on manjaro.

### ISSUE THREAD

**Issue by pepoangel** [HelloZeroNet/ZeroNet#2735]
┌─[root@manjaro] - [/opt/zeronet] - [309]
└─[$] systemctl start zeronet.service                                                                                                        [0:18:43]
┌─[root@manjaro] - [/opt/zeronet] - [310]
└─[$] systemctl status zeronet.service                                                                                                       [0:18:46]
● zeronet.service - Decentralized websites using Bitcoin crypto and the BitTorrent network
     Loaded: loaded (/usr/lib/systemd/system/zeronet.service; enabled; vendor preset: disabled)
     Active: inactive (dead) since Fri 2021-02-19 00:18:46 AST; 2s ago
    Process: 98605 ExecStart=/usr/bin/env python zeronet.py --config_file /etc/zeronet.conf (code=exited, status=0/SUCCESS)
   Main PID: 98605 (code=exited, status=0/SUCCESS)

Feb 19 00:18:46 manjaro zeronet[98605]: Traceback (most recent call last):
Feb 19 00:18:46 manjaro zeronet[98605]:   File "/opt/zeronet/zeronet.py", line 16, in main
Feb 19 00:18:46 manjaro zeronet[98605]:     import main
Feb 19 00:18:46 manjaro zeronet[98605]:   File "/opt/zeronet/src/main.py", line 31, in <module>
Feb 19 00:18:46 manjaro zeronet[98605]:     open("%s/sites.json" % config.data_dir, "w").write("{}")
Feb 19 00:18:46 manjaro zeronet[98605]: PermissionError: [Errno 13] Permission denied: './data/sites.json'
Feb 19 00:18:46 manjaro zeronet[98605]: - Starting ZeroNet...
Feb 19 00:18:46 manjaro zeronet[98605]: ---
Feb 19 00:18:46 manjaro zeronet[98605]: Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md
Feb 19 00:18:46 manjaro systemd[1]: zeronet.service: Succeeded.

**Comment by krzotr** [comment]
Hi, pepoangel,

Something is wrong with your `data` directory. Probably you do not have permission to write/read. Please check if your data dir `/opt/zeronet/data/` exists and has correct permissions.

Please also follow:
1. Edit your `/etc/zeronet.conf` file
2. Add `data_dir = /opt/zeronet/data`
3. Create directory `/opt/zeronet/data` if does not exist
4. Set correct permissions (user/group) to `/opt/zeronet/data`
5. Restart zeronet service
