### ISSUE TITLE
Unhandled exception: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by mahdi-ln** [HelloZeroNet/ZeroNet#2791]
```
(venv) [m@m-pc ZeroNet]$ python3 zeronet.py
- Starting ZeroNet...
[11:44:50] - Unhandled exception: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/m/Downloads/c/ZeroNet/zeronet.py", line 16, in main
    import main
  File "/home/m/Downloads/c/ZeroNet/src/main.py", line 74, in <module>
    from Plugin import PluginManager
  File "/home/m/Downloads/c/ZeroNet/src/Plugin/PluginManager.py", line 211, in <module>
    plugin_manager = PluginManager()  # Singletone
  File "/home/m/Downloads/c/ZeroNet/src/Plugin/PluginManager.py", line 19, in __init__
    self.path_plugins = os.path.abspath(os.path.dirname(plugins.__file__))
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
---
Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md
```

**Comment by mahdi-ln** [comment]
Sorry it was not your fork
