### ISSUE TITLE
Zeronet fault

### ISSUE THREAD

**Issue by DanielNewtonNoesges** [HelloZeroNet/ZeroNet#2850]
- Starting ZeroNet...
[14:07:18] PluginManager Plugin AnnounceBitTorrent load error: ModuleNotFoundError: No module named 'bencode' in PluginManager.py line 138 > AnnounceBitTorrent/__init__.py line 1 > AnnounceBitTorrent/AnnounceBitTorrentPlugin.py line 6
[14:07:18] PluginManager Plugin Bigfile load error: ModuleNotFoundError: No module named 'merkletools' in PluginManager.py line 138 > Bigfile/__init__.py line 1 > Bigfile/BigfilePlugin.py line 20
[14:07:18] - Libsecp256k1 load failed: No module named 'coincurve', try to load OpenSSL
[14:07:18] - OpenSSL load failed: No module named 'bitcoin', falling back to slow bitcoin verify
[14:07:18] - Version: 0.7.0 r4206, Python 3.11.9 (main, Aug 13 2024, 13:46:46) [Clang 18.0.1 (https://android.googlesource.com/toolchain/llvm-project d8003a456, Gevent: 24.2.1
[14:07:18] - Unhandled exception: No module named 'socks'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/opt/zeronet/zeronet.py", line 17, in main
    main.start()                                        File "/data/data/com.termux/files/usr/opt/zeronet/src/main.py", line 537, in start
    actions.call(config.action, action_kwargs)
  File "/data/data/com.termux/files/usr/opt/zeronet/src/main.py", line 121, in call
    back = func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/opt/zeronet/src/main.py", line 128, in main
    from File import FileServer
  File "/data/data/com.termux/files/usr/opt/zeronet/src/File/__init__.py", line 1, in <module>
    from .FileServer import FileServer                  File "/data/data/com.termux/files/usr/opt/zeronet/src/File/FileServer.py", line 16, in <module>
    from Connection import ConnectionServer
  File "/data/data/com.termux/files/usr/opt/zeronet/src/Connection/__init__.py", line 1, in <module>
    from .ConnectionServer import ConnectionServer
  File "/data/data/com.termux/files/usr/opt/zeronet/src/Connection/ConnectionServer.py", line 19, in <module>
    from Tor import TorManager                          File "/data/data/com.termux/files/usr/opt/zeronet/src/Tor/__init__.py", line 1, in <module>
    from .TorManager import TorManager                  File "/data/data/com.termux/files/usr/opt/zeronet/src/Tor/TorManager.py", line 17, in <module>
    import socks
ModuleNotFoundError: No module named 'socks'

**Comment by code-zer001** [comment]
Are you running it on android?

**Comment by DanielNewtonNoesges** [comment]
Yes I am running it on android

**Comment by code-zer001** [comment]
I don't think it would work with termux. But they have an android app. You could check it out

**Comment by caryoscelus** [comment]
you can make it work on termux. but this (non-fork) version is very old and has significant issues

**Comment by JackLongBow** [comment]
The windows version has the same issues
