### ISSUE TITLE
Gevent install error

### ISSUE THREAD

**Issue by ASBaumgarten** [HelloZeroNet/ZeroNet#287]
`Alexanders-MBP:ZeroNet-master Alexander$ pip install gevent msgpack-python
Collecting gevent
  Using cached gevent-1.0.2.tar.gz
Collecting msgpack-python
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in /usr/local/lib/python3.5/site-packages (from gevent)
Building wheels for collected packages: gevent
  Running setup.py bdist_wheel for gevent ... error
  Complete output from command /usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/tmpe6gh2f0xpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-3.5
  creating build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/__init__.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/_ssl2.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/_sslgte279.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/_threading.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/backdoor.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/baseserver.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/coros.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/event.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/fileobject.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/greenlet.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/hub.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/local.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/lock.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/monkey.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/os.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/pool.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/pywsgi.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/queue.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/resolver_ares.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/resolver_thread.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/select.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/server.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/socket.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/ssl.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/subprocess.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/thread.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/threading.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/threadpool.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/timeout.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/util.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/win32util.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  copying gevent/wsgi.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
  running build_ext
  Running '/bin/sh /private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/libev/configure > configure-output.txt' in /private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/build/temp.macosx-10.11-x86_64-3.5/libev
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 317, in <module>
      run_setup(ext_modules)
    File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 312, in run_setup
      "Development Status :: 4 - Beta"])
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 176, in run
      self.run_command('build')
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
      self.build_extensions()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 234, in build_extension
      self.gevent_prepare(ext)
    File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 231, in gevent_prepare
      configure(self, ext)
    File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 139, in configure_libev
      make_universal_header('config.h', 'SIZEOF_LONG', 'SIZEOF_SIZE_T', 'SIZEOF_TIME_T')
    File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 111, in make_universal_header
      print >>f, line
  TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

  ----------------------------------------
  Failed building wheel for gevent
  Running setup.py clean for gevent
Failed to build gevent
Installing collected packages: gevent, msgpack-python
  Running setup.py install for gevent ... error
    Complete output from command /usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-wfiqvlcs-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-3.5
    creating build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/__init__.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/_ssl2.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/_sslgte279.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/_threading.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/backdoor.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/baseserver.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/coros.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/event.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/fileobject.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/greenlet.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/hub.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/local.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/lock.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/monkey.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/os.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/pool.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/pywsgi.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/queue.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/resolver_ares.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/resolver_thread.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/select.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/server.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/socket.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/ssl.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/subprocess.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/thread.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/threading.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/threadpool.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/timeout.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/util.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/win32util.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    copying gevent/wsgi.py -> build/lib.macosx-10.11-x86_64-3.5/gevent
    running build_ext
    Running '/bin/sh /private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/libev/configure > configure-output.txt' in /private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/build/temp.macosx-10.11-x86_64-3.5/libev
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 317, in <module>
        run_setup(ext_modules)
      File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 312, in run_setup
        "Development Status :: 4 - Beta"])
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 234, in build_extension
        self.gevent_prepare(ext)
      File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 231, in gevent_prepare
        configure(self, ext)
      File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 139, in configure_libev
        make_universal_header('config.h', 'SIZEOF_LONG', 'SIZEOF_SIZE_T', 'SIZEOF_TIME_T')
      File "/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py", line 111, in make_universal_header
        print >>f, line
    TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-wfiqvlcs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/s9/h4qsl5vj1yx80k58lp3211580000gn/T/pip-build-4gr3dygb/gevent
Alexanders-MBP:ZeroNet-master Alexander$`

**Comment by HelloZeroNet** [comment]
we need python2, so try `python2 -m pip install gevent` or `python2.7 -m pip install gevent` please

**Comment by ASBaumgarten** [comment]
`python -m pip install gevent msgpack-python` got it installed and working. Thanks.

**Comment by HelloZeroNet** [comment]
nice!
