### ISSUE TITLE
error: [Errno 24] Too many open files (after mac wake up)

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroNet#320]
[12:52:44] Site:1CpGZy..bEzd Announce to 0 trackers in 9.810s, failed
[12:52:45] Site:1MaiL5..Ju27 Announce to 0 trackers in 1.228s, failed
[12:52:46] Site:192dZ1..s4t3 Announce to 0 trackers in 0.078s, failed
[12:52:49] Site:1NJyPo..XcLT Announce to 0 trackers in 1.034s, failed
[12:52:52] Site:1TaLkF..jipT Announce to 0 trackers in 1.819s, failed
[12:53:11] - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "plugins/AnnounceZero/AnnounceZeroPlugin.py", line 43, in announceTracker
    tracker_protocol, tracker_address, fileserver_port, add_types, my_peer_id, mode
  File "/Users/Shift/ZeroNet/src/Site/Site.py", line 583, in announceTracker
    tracker = UdpTrackerClient(ip, int(port))
  File "/Users/Shift/ZeroNet/src/lib/subtl/subtl.py", line 42, in __init__
    self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  File "/usr/local/lib/python2.7/site-packages/gevent/socket.py", line 227, in **init**
    self._sock = _realsocket(family, type, proto)
error: [Errno 24] Too many open files

**Comment by HelloZeroNet** [comment]
can you please run `ulimit -a` ?

**Comment by HelloZeroNet** [comment]
I have created a simple script, please save it, then run using `python test_max.py` and paste the result here.

https://gist.githubusercontent.com/HelloZeroNet/d9bf888693e66a573815/raw/afdb058ad9709036172ef5ccfc9ad38bf1619c28/test_max.py

**Comment by iShift** [comment]
`MacBook-Pro:Desktop Shift$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited`

MacBook-Pro:Desktop Shift$ python test_max.py 
Max open files without changing settings: 253
Current RLIMIT_NOFILE limit: 256 9223372036854775807 Changing to 3000...
Max open files after changing settings: 2997

**Comment by HelloZeroNet** [comment]
Yeah 256 is pretty low, 1024 on linux and 512 on win by default.

Good news is looks like we can change it from python code. I will add it later today to ZeroNet

**Comment by kseistrup** [comment]
@HelloZeroNet you can only change it from python if you haven't already reached the upper limit (and it seems 1024 was the limit on my box).

I added the following lines to `/etc/security/limits.conf`:
```sh
*               hard    nofile          8192
*               soft    nofile          4096
```
and
```ini
LimitNOFILE=8192
```
to the `[Service]` section of the `zeronet.service` file.

**Comment by HelloZeroNet** [comment]
I checked my VPS-s using `ulimit -Ha` and the lowest hard limit was 4096 (Debian 7), the others (CentOS7, Debian8) has 65535.

At the startup ZeroNet will try to change the max opened files to 1024.

**Comment by HelloZeroNet** [comment]
Fixed in latest version (rev948), please update!
After restart you can verify if its working by searching for `Current RLIMIT_NOFILE:` in `log/debug.log` (it's right after web interface address displaying)

**Comment by iShift** [comment]
get  it again on 948 

IOError: [Errno 24] Too many open files: 'data/sites.json'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
  File "/Users/Shift/ZeroNet/src/File/FileServer.py", line 223, in announceSites
  File "/Users/Shift/ZeroNet/src/Site/Site.py", line 707, in announce
  File "/Users/Shift/ZeroNet/src/Site/Site.py", line 93, in saveSettings
IOError: [Errno 24] Too many open files: 'data/sites.json'
[02:21:57] - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/Shift/ZeroNet/src/Site/Site.py", line 280, in update
    self.storage.checkFiles(quick_check=True)  # Quick check and mark bad files based on file size
  File "/Users/Shift/ZeroNet/src/Site/SiteStorage.py", line 334, in checkFiles
  File "/Users/Shift/ZeroNet/src/Site/SiteStorage.py", line 269, in verifyFiles
  File "/Users/Shift/ZeroNet/src/Site/SiteStorage.py", line 248, in getPath
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 362, in abspath
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
  File "/Users/Shift/ZeroNet/src/Site/Site.py", line 280, in update
  File "/Users/Shift/ZeroNet/src/Site/SiteStorage.py", line 334, in checkFiles
  File "/Users/Shift/ZeroNet/src/Site/SiteStorage.py", line 269, in verifyFiles
  File "/Users/Shift/ZeroNet/src/Site/SiteStorage.py", line 248, in getPath
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 362, in abspath
OSError: [Errno 24] Too many open files

**Comment by HelloZeroNet** [comment]
sorry i have no osx access, maybe need to change other os settings

**Comment by HelloZeroNet** [comment]
Any update if `--max_files_opened 10240` fixed it?

**Comment by iShift** [comment]
i don't sure for now, wait some time...

**Comment by HelloZeroNet** [comment]
Probably fixed by: https://github.com/HelloZeroNet/ZeroNet/commit/6f2445c417e59c3bf948ff5c3fd0a722c710f9d3
