### ISSUE TITLE
Unhandled exception: Wrong encoding

### ISSUE THREAD

**Issue by t4ec** [HelloZeroNet/ZeroNet#340]
Hello,

While trying to open one site which dynamically loads content (images + text) I get following error and images/text are not loaded, so the site is partially broken.

Here you can see the traceback:

```
[20:07:06] - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 56, in downloader
    correct = site.content_manager.verifyFile(task["inner_path"], buff)
  File "src/Content/ContentManager.py", line 594, in verifyFile
    if inner_path != "content.json" and not self.verifyCert(inner_path, new_content):  # Check if cert valid
  File "src/Content/ContentManager.py", line 475, in verifyCert
    "%s#%s/%s" % (rules["user_address"], content["cert_auth_type"], name), cert_address, content["cert_sign"]
  File "src/Crypt/CryptBitcoin.py", line 63, in verify
    pub = opensslVerify.getMessagePubkey(data, sign)
  File "src/lib/opensslVerify/opensslVerify.py", line 422, in getMessagePubkey
    eckey = SetCompactSignature(pkey, Hash(msg_magic(message)), sig)
  File "src/lib/opensslVerify/opensslVerify.py", line 329, in SetCompactSignature
    raise BaseException("Wrong encoding")
BaseException: Wrong encoding
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 56, in downloader
    correct = site.content_manager.verifyFile(task["inner_path"], buff)
  File "src/Content/ContentManager.py", line 594, in verifyFile
    if inner_path != "content.json" and not self.verifyCert(inner_path, new_content):  # Check if cert valid
  File "src/Content/ContentManager.py", line 475, in verifyCert
    "%s#%s/%s" % (rules["user_address"], content["cert_auth_type"], name), cert_address, content["cert_sign"]
  File "src/Crypt/CryptBitcoin.py", line 63, in verify
    pub = opensslVerify.getMessagePubkey(data, sign)
  File "src/lib/opensslVerify/opensslVerify.py", line 422, in getMessagePubkey
    eckey = SetCompactSignature(pkey, Hash(msg_magic(message)), sig)
  File "src/lib/opensslVerify/opensslVerify.py", line 329, in SetCompactSignature
    raise BaseException("Wrong encoding")
BaseException: Wrong encoding
```
I am still able to browse this and other sites, it's just some part of content which is not loaded.
Let me know if you need additional information.

**Comment by border0464111** [comment]
Commit https://github.com/HelloZeroNet/ZeroNet/commit/4c7ff9bb539f55cf1d6352bb55fde736e0267956
Have probably  fixed it. 

Can you check if you can still reproduce with the lastest version ?

**Comment by grez911** [comment]
@HelloZeroNet Please, close.
