### ISSUE TITLE
Ubuntu 15.10 Error

### ISSUE THREAD

**Issue by scriptzteam** [HelloZeroNet/ZeroNet#349]
```
- Starting ZeroNet...
[19:01:18] - OpenSSL loaded, version: 01000204F
[19:01:18] - Version: 0.3.6 r966, Python 2.7.10 (default, Oct 14 2015, 16:09:02)
[GCC 5.2.1 20151010], Gevent: 1.1b1
[19:01:18] - Creating FileServer....
[19:01:18] TorManager Tor controller connect error: AssertionError: Tor version >=0.2.7.5 required, found: 0.2.6.10 in TorManager.py line 156
[19:01:18] - Creating UiServer....
Traceback (most recent call last):
  File "zeronet.py", line 16, in main
    main.start()
  File "src/main.py", line 382, in start
    actions.call(config.action, action_kwargs)
  File "src/main.py", line 112, in call
    func(**kwargs)
  File "src/main.py", line 123, in main
    ui_server = UiServer()
  File "src/Ui/UiServer.py", line 61, in __init__
    self.sites = SiteManager.site_manager.list()
  File "src/Site/SiteManager.py", line 90, in list
    self.load()
  File "plugins/Zeroname/SiteManagerPlugin.py", line 17, in load
    super(SiteManagerPlugin, self).load()
  File "src/Site/SiteManager.py", line 25, in load
    for address in json.load(open("%s/sites.json" % config.data_dir)):
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 4356 column 2 - line 4356 column 3 (char 147007 - 147008)
```

**Comment by Erkan-Yilmaz** [comment]
the first error msg tells, that you need a newer tor version:
[19:01:18] TorManager Tor controller connect error: AssertionError: Tor version >=0.2.7.5 required, found: 0.2.6.10 in TorManager.py line 156

**Comment by HelloZeroNet** [comment]
Tor error is not relevant, your sites.json is broken somehow (probably hdd error), you need to fix it around line 4356. or check if sites.json.old old similar is present.

**Comment by scriptzteam** [comment]
Line 4356 was }} so just removed one of } and it works ;) there should be autof for this if doubled  }} at the end of sites.json file
