### ISSUE TITLE
NameError: global name 'wraper_key' is not defined

### ISSUE THREAD

**Issue by arthurlutz** [HelloZeroNet/ZeroNet#35]
After git pull : 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/home/arthur/local/ZeroNet/src/Ui/UiServer.py", line 21, in run_application
    self.ws_handler.run_application()
  File "/home/arthur/local/ZeroNet/src/lib/geventwebsocket/handler.py", line 81, in run_application
    self.run_websocket()
  File "/home/arthur/local/ZeroNet/src/lib/geventwebsocket/handler.py", line 57, in run_websocket
    self.application(self.environ, lambda s, h: [])
  File "/home/arthur/local/ZeroNet/src/Ui/UiServer.py", line 49, in handleRequest
    return self.ui_request.route(path)
  File "/home/arthur/local/ZeroNet/src/Ui/UiRequest.py", line 41, in route
    return self.actionWebsocket()
  File "/home/arthur/local/ZeroNet/src/Ui/UiRequest.py", line 239, in actionWebsocket
    self.log.error("Wrapper key not found: %s" % wraper_key)
NameError: global name 'wraper_key' is not defined
```

**Comment by arthurlutz** [comment]
Then I have a bunch of 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/arthur/local/ZeroNet/src/Worker/Worker.py", line 34, in downloader
    buff = self.peer.getFile(task["site"].address, task["inner_path"])
  File "/home/arthur/local/ZeroNet/src/Peer/Peer.py", line 87, in getFile
    back = self.sendCmd("getFile", {"site": site, "inner_path": inner_path, "location": location}) # Get file content from last location
  File "/home/arthur/local/ZeroNet/src/Peer/Peer.py", line 71, in sendCmd
    self.onConnectionError()
  File "/home/arthur/local/ZeroNet/src/Peer/Peer.py", line 137, in onConnectionError
    self.remove()
  File "/home/arthur/local/ZeroNet/src/Peer/Peer.py", line 127, in remove
    del(self.site.peers[self.key])
KeyError: '104.156.231.236:15441'
<Greenlet at 0x7f92ea96a050: <bound method Worker.downloader of <Worker.Worker.Worker instance at 0x7f92ea95dd88>>> failed with KeyError

[09:48:56] Site:1EU1tb..E4Vr Can't update content.json
```

**Comment by ymski** [comment]
I had this error too, but the page loaded and I couldn't replicate it again, even after restarting. Do you know if this is replicable?

**Comment by ymski** [comment]
We'll need to figure out why the wrapper_key from the top error wasn't found. However, the NameError itself is because wrapper_key is improperly spelled as wraper_key in the log. I put in a quick fix for the NameError.
