### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by WeirdCarrotMonster** [HelloZeroNet/ZeroNet#382]
I think that zeronet can be packaged via setuptools and uploaded to PyPI instead of using custom update scripts. You will only need to create setup.py file.

Pros:
- Official way to install python packages
- Easier to install (pip install zeronet, dependencies are downloaded automagically)
- Easier to update (pip install --upgrade zeronet)
- [Command line scripts](https://python-packaging.readthedocs.org/en/latest/command-line-scripts.html)

Cons:
- Some modifications to source code (mostly imports) may be required

If you think that such modifications can be useful, i can work on this issue and create PR later.

**Comment by almet** [comment]
I would love to see this happening!

**Comment by HelloZeroNet** [comment]
Currently ZeroBundle is the default install method it contains all of the liblaries the you need to run zeronet. (SSL+Python is a sad story: had lots of problems with different openssl, gevent and python versions that are incompatible with eachother) It also has built-in update method that downloads the latest version from github, unpacks it and restart itself.

**Comment by almet** [comment]
- For SSL + Python, does anything prevents us to pin the versions (like what you're currently doing) in the `setup.py`?
- For the update mechanism, I believe we could do it also with the setup.py. Could you point to the code that's doing this? Thanks!

**Comment by HelloZeroNet** [comment]
It's hard to pin version, because it's also depends on OpenSSL and Python version which is supplied by the OS. The updating is done by `update.py`

**Comment by WeirdCarrotMonster** [comment]
The package itself can be installed in bundle, the only thing that changes is update method - instead of downloading master branch from github, script will use pip to install latest released version.

On the other hand, it won't work with plugins in their current implementation - but if you ask me, marking plugins as disabled by prefixing "disabled-" is bad idea. I don't know much about good practices for pluggable modules, so i'll look into it for now.

**Comment by almet** [comment]
>I don't know much about good practices for pluggable modules, so i'll look into it for now.

In python packaging there is the [concept of entrypoints](http://stackoverflow.com/questions/774824/explain-python-entry-points) which can be installed in separate packages and listed by another package.

This is exactly done for such cases. Then we could enable/disable modules based on a configuration file, for instance (and default configuration associated).

**Comment by WeirdCarrotMonster** [comment]
[Here is full example](http://stackoverflow.com/a/9615473/3315512).

We can agree on common entrypoint name (i.e. "zeronet") and expect function to return plugin object.

**Comment by FedericoCeratto** [comment]
Vendorizing libraries and not having a setup.py is going to make it very difficult for distributions to package ZeroNet. Distros have their own dependency management. Having a list of acceptable ranges for all dependencies could be helpful.

**Comment by leycec** [comment]
**This needs to happen.**

As a [Gentoo Linux contributor](https://github.com/leycec/raiagent), ZeroNet's inclusion of vendorized dependencies *and* failure to comply with basic Python packaging standards (e.g., `setup.py`, PyPI) all but guarantees that ZeroNet will never hit [Portage](https://wiki.gentoo.org/wiki/Portage) – the official package tree for Gentoo. While I fully intend to publish and maintain an unofficial ZeroNet ebuild (i.e., Gentoo package) at my [third-party overlay](https://github.com/leycec/raiagent) despite these deficiencies, this is only a stop-gap measure. ZeroNet deserves better.

Ultimately, ZeroNet needs to comply with industry-standard installation practices for open-source Python software. This means `setup.py` and PyPI.

Authoring and submitting a working `setup.py` script to PyPI is, frankly, trivial. By compare to the mammoth effort of designing and maintaining a decentralized, demonetized, anonymized, censorship-resistent Internet, interfacing with the [CheeseShop](https://wiki.python.org/moin/CheeseShop) should be literal child's play.

Are we children? Or are we men?

**Comment by leycec** [comment]
@ulrichard I note that you've already authored a [preliminary `setup.py`](https://github.com/HelloZeroNet/ZeroNet/issues/417#issuecomment-256174420) for use in your Ubuntu PPA. _Excellent._

Would you be willing to submit a pull request officially integrating that into ZeroNet? It doesn't necessarily need to be perfect (particularly with respect to dependencies and version ranges). Something is absolutely better than nothing. And nothing is what ZeroNet currently has.

**Comment by bignose-debian** [comment]
> Are we children? Or are we men?

I'm pretty confident those are not the only options. We adults are not limited to men in gender :-)

**Comment by bignose-debian** [comment]
Having a sensible importable name for the top-level package is a pre-requisite for a sane packaging setup, so issue #940 is IMO a pre-requisite for this issue.

**Comment by leycec** [comment]
> I'm pretty confident those are not the only options. We adults are not limited to men in gender :-)

As much as we all appreciate restatements of the self-obvious, the "Are we children? Or are we men?" hypothetical was a tongue-in-cheek reference to [Devo](https://rateyourmusic.com/artist/devo)'s 1978 synthpop classic [**"Q: Are We Not Men? A: We Are Devo!"**](https://rateyourmusic.com/release/album/devo/q__are_we_not_men__a__we_are_devo_)

I assumed we were all sufficiently familiar with 70's-era New Wave (art|post|proto)-punk experimental synthpop rock here. Clearly, I assumed incorrectly.

> Having a sensible importable name for the top-level package is a pre-requisite for a sane packaging setup...

👍 🤐 👍 

ZeroNet has deviated *so* far afield from a sane packaging setup that I'm unsure what, if anything, can reasonably be done at this late hour. It's *not* simply the lack of a `setup.py` script, PyPI wheel, or eponymous top-level package. It's also:

* The extreme number of bundled mandatory runtime dependencies, most patched in a ZeroNet-specific manner in unclear and probably unsafe ways.
* The lack of an official list of mandatory and optional build-, run-, and test-time dependencies, complete with acceptable version ranges.
* The lack of a documented protocol for performing system-wide installation, particularly with respect to requisite users, groups, permissions, and directory structure.
* The lack of a default system-wide installation shell script.
* The lack of a default configuration file template.
* The lack of a default `systemd` unit.
* The lack of a default OpenRC script.
* The lack of a default `/usr/bin/zeronet` shell script. The bundled `zeronet.py` script fails to suffice for a medley of reasons. In particular, `zeronet.py`:
* Fails to include the system-wide ZeroNet configuration file (e.g., `/etc/zeronet.conf`) if any.
* Fails to generalize to Python 3.x (e.g., due to the shebang line `#!/usr/bin/env python2.7`). While ZeroNet does *not* yet support Python 3.x, it clearly [needs to](https://github.com/HelloZeroNet/ZeroNet/issues/149).

Frankly, ZeroNet is a Turing-complete nightmare with respect to packaging. To simplify packaging ZeroNet for other Linux distributions, consider pilfering the `src_install()` function of my [recently complete ZeroNet ebuild](https://github.com/leycec/raiagent/blob/master/net-vpn/zeronet/zeronet-9999.ebuild#L112) for Gentoo Linux. This function dynamically synthesizes sane users, groups, permissions, directory structure, system-wide configuration file, `systemd` unit, OpenRC script, `/usr/bin/zeronet` launcher from user-supplied choices (e.g., whether or not to enable Tor-based anonymization).

The [ZeroNet PKGBUILD tree](https://aur.archlinux.org/cgit/aur.git/tree/?h=zeronet) for Arch Linux also comes recommended for this purpose.

May the genderless penguin be with you, fellow packagers.

**Comment by madovsky** [comment]
please first stop to bully. Secondly, if you think that zeronet is a nightmare so fork it and make your own.

**Comment by bignose-debian** [comment]
> It's not simply the lack of a setup.py script, PyPI wheel, or eponymous top-level package. It's also […]

That's a good solid list of specific issues.

They all seem tractable; how about we have each of them in a separate issue and work on addressing them?

@HelloZeroNet, those all look like real issues that should be addressed. Is there anything there you don't want corrected?

**Comment by rachmadaniHaryono** [comment]
hi, i'm interested on this issue and try to create a solution for this

at first i thought the package is need to be renamed but based on this, it doesn't have to https://github.com/pypa/python-packaging-user-guide/issues/320

so my first step is to include setup.py and manifest file (https://github.com/rachmadaniHaryono/ZeroNet/commit/5f9e4d3f08a150c6e517001c4f95c7970342f942)

to run the program, the `setup.py` require an entry point. my first try is simply moving `zeronet.py` to src and set `zeronet:main` as entry point, but that didn't work. (https://github.com/rachmadaniHaryono/ZeroNet/commit/e557edb4941892dc2a7a746de86bd9be2fb0ad1f)

my second try is create a folder `zeronet`, rename `zeronet.py` to `zeronet/__main__.py` and use it as entry point. (https://github.com/rachmadaniHaryono/ZeroNet/commit/2eac1a2ee99876ad895f5bcb79138d3acc182077)

that last step at least made zeronet pip installable but not working. i made two test on 2 different folder with 2 different virtualenv:
- folder with zeronet source (result from `git clone`)
- empty folder

folder with zeronet source will run and reachable from browser but i suspect there is unseen error because of this line 
```
[13:06:58] Site:<string1> data/users/<string2>/blacklist.json fileGet error: [Errno 2] No such file or directory: 
```

empty folder will raise following error
```
[13:37:40] - Unhandled exception: [Errno 2] No such file or directory: 'plugins'
Traceback (most recent call last):
  File "/home/q/git/ZeroNet/src/zeronet/__main__.py", line 18, in main
    import main
  File "/home/q/git/ZeroNet/src/main.py", line 112, in <module>
    from Plugin import PluginManager
  File "/home/q/envs/temp/local/lib/python2.7/site-packages/gevent/builtins.py", line 96, in __import__
    result = _import(*args, **kwargs)
  File "/home/q/git/ZeroNet/src/Plugin/PluginManager.py", line 115, in <module>
    plugin_manager = PluginManager()  # Singletone
  File "/home/q/git/ZeroNet/src/Plugin/PluginManager.py", line 23, in __init__
    self.migratePlugins()
  File "/home/q/git/ZeroNet/src/Plugin/PluginManager.py", line 30, in migratePlugins
    for dir_name in os.listdir(self.plugin_path):
OSError: [Errno 2] No such file or directory: 'plugins'
[13:37:40] - Unhandled exception
None
Traceback (most recent call last):
  File "/home/q/envs/temp/bin/zeronet", line 11, in <module>
    load_entry_point('zeronet', 'console_scripts', 'zeronet')()
  File "/home/q/git/ZeroNet/src/zeronet/__main__.py", line 53, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'
``` 
2 things happen here:
- empty folder don't have plugins folder, even when manifest include them
- Config object is different when run on emtpy folder

**Comment by radfish** [comment]
packaged for setuptools in this branch:
https://github.com/radfish/ZeroNet/tree/setuptools

I'm in the process of upstream it to here.
