### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [HelloZeroNet/ZeroNet#438]
I had just restarted ZeroNet (1) and I got:

[06:40:56] - Unhandled exception

Traceback (most recent call last):
  File "/home/BarackObama/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Site/Site.py", line 311, in update
    self.storage.checkFiles(quick_check=True)  # Quick check and mark bad files based on file size
  File "src/Site/SiteStorage.py", line 356, in checkFiles
    add_changed=not self.site.settings.get("own")  # Don't overwrite changed files if site owned
  File "src/Site/SiteStorage.py", line 286, in verifyFiles
    for content_inner_path, content in self.site.content_manager.contents.iteritems():
RuntimeError: dictionary changed size during iteration

Traceback (most recent call last):
  File "/home/BarackObama/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Site/Site.py", line 311, in update
    self.storage.checkFiles(quick_check=True)  # Quick check and mark bad files based on file size
  File "src/Site/SiteStorage.py", line 356, in checkFiles
    add_changed=not self.site.settings.get("own")  # Don't overwrite changed files if site owned
  File "src/Site/SiteStorage.py", line 286, in verifyFiles
    for content_inner_path, content in self.site.content_manager.contents.iteritems():
RuntimeError: dictionary changed size during iteration

used versions:
- ZeroNet 0.3.7 r1274
- gevent 1.0.2
- greenlet 0.4.9

(1) it was running for less than 2 mins

**Comment by HelloZeroNet** [comment]
thx fixd 93e598cc596c023b035507fe018c2163cad2aa32
