### ISSUE TITLE
Unhandled exception/Traceback: KeyError: 'data/users/13rBMTrszAYoc5jPgSMzkrBWNKCvJNY9zp/content.json'

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [HelloZeroNet/ZeroNet#439]
ZeroNet was running for ca. 7.5h when those exceptions happened:

[2016-04-27 01:00:59,567] DEBUG    Site:1MaiL5..Ju27 69.122.63.218:15441 Getting connection...
[2016-04-27 01:00:59,567] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/home/AngelaMerkel/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/File/FileRequest.py", line 139, in actionUpdate
    peer.last_content_json_update = site.content_manager.contents[params["inner_path"]]["modified"]
KeyError: 'data/users/13rBMTrszAYoc5jPgSMzkrBWNKCvJNY9zp/content.json'

[2016-04-27 01:00:59,568] DEBUG    Site:1MaiL5..Ju27 24.203.7.149:15441 Getting connection...
[2016-04-27 01:00:59,568] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/home/AngelaMerkel/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/File/FileRequest.py", line 139, in actionUpdate
    peer.last_content_json_update = site.content_manager.contents[params["inner_path"]]["modified"]
KeyError: 'data/users/13rBMTrszAYoc5jPgSMzkrBWNKCvJNY9zp/content.json'

[2016-04-27 01:00:59,569] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/home/AngelaMerkel/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/File/FileRequest.py", line 139, in actionUpdate
    peer.last_content_json_update = site.content_manager.contents[params["inner_path"]]["modified"]
KeyError: 'data/users/13rBMTrszAYoc5jPgSMzkrBWNKCvJNY9zp/content.json'

[2016-04-27 01:00:59,569] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/home/AngelaMerkel/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/File/FileRequest.py", line 139, in actionUpdate
    peer.last_content_json_update = site.content_manager.contents[params["inner_path"]]["modified"]
KeyError: 'data/users/13rBMTrszAYoc5jPgSMzkrBWNKCvJNY9zp/content.json'
[2016-04-27 01:00:59,574] DEBUG    Site:1MaiL5..Ju27 Downloading data/users/13rBMTrszAYoc5jPgSMzkrBWNKCvJNY9zp/content.json...

used versions:
* ZeroNet 0.3.7 r1275
* gevent 1.0.2
* greenlet 0.4.9

**Comment by HelloZeroNet** [comment]
thx, fixed: 432aa037cbda0368ceb3b07dba526a8044eaa821
