### ISSUE TITLE
ZeroNet fails to start after an ungraceful shutdown

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#471]
After the system crash ZeroNet doesn't start any more:
```
[12:30:53] - OpenSSL loaded, version: 01000114F
[12:30:53] - Version: 0.3.6 r1098, Python 2.7.11 (default, May  6 2016, 08:39:38)
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)], Gevent: 1.1.1
[12:30:53] - Creating FileServer....
[12:30:53] TorManager Tor controller connect error: AssertionError: Authenticate error 515 Authentication failed: Password did not match HashedControlPassword value from configuration. Maybe you tried a plain text password? If so, the standard requires that you put it in double quotes.^M
 in TorManager.py line 170
[12:30:53] - Creating UiServer....
Traceback (most recent call last):
  File "/usr/local/share/zeronet/zeronet.py", line 16, in main
    main.start()
  File "/usr/local/share/zeronet/src/main.py", line 412, in start
    actions.call(config.action, action_kwargs)
  File "/usr/local/share/zeronet/src/main.py", line 115, in call
    func(**kwargs)
  File "/usr/local/share/zeronet/src/main.py", line 126, in main
    ui_server = UiServer()
  File "/usr/local/share/zeronet/src/Ui/UiServer.py", line 61, in __init__
    self.sites = SiteManager.site_manager.list()
  File "/usr/local/share/zeronet/src/Site/SiteManager.py", line 90, in list
    self.load()
  File "plugins/Zeroname/SiteManagerPlugin.py", line 17, in load
    super(SiteManagerPlugin, self).load()
  File "/usr/local/share/zeronet/src/Site/SiteManager.py", line 25, in load
    for address in json.load(open("%s/sites.json" % config.data_dir)):
  File "/usr/local/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
- Starting ZeroNet...
```

**Comment by HelloZeroNet** [comment]
normally it should not happen: https://github.com/HelloZeroNet/ZeroNet/blob/master/src/util/helper.py#L12
 - It writes new content to data/sites.json-new
 - Renames current to sites.json-old
 - Renames sites.json-new to sites.json
 - Deletes sites.json-old

Have you checked the sites.json content? Was it incomplete or random bytes? Was there sites.json-old file?

Im not sure if sqlite is a good solution to store configuration files, because it's harder to edit.

**Comment by yurivict** [comment]
sites.json was blank, sites.json-new was valid. So I copied it over.

**Comment by border0464111** [comment]
yurivict's specific problem have been solved, it might hide a bug but no others users have reported alike issues and it append on a now outdated issue. Not much can be done here for this issue in 2017.

**Comment by yurivict** [comment]
I use UFS on FreeBSD. Most people use linux, this is why this hasn't been reported by others.

This issue basically means that sites.json-new isn't actually used when sites.json is damaged/truncated.
Do you have a commit that solved this issue?
