### ISSUE TITLE
127.0.0.1 refused to connect.

### ISSUE THREAD

**Issue by zerotrix** [HelloZeroNet/ZeroNet#532]
This site can’t be reached

127.0.0.1 refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

I use Chrome. Both Chrome and Firefox have permission under my windows defender. I was using zeronet a few days ago with no issue, and have not changed any settings. I am unsure what could be causing this problem. If anyone has information or advice, please, I am all ears.

**Comment by CPCer** [comment]
same problem here... someone suggest me using .exe version on my win8. Seemed fine now  #770

**Comment by CPCer** [comment]
After I inserted "import os" and "os.system("pause") " in start.py, it won't force close

but still get a ERR_CONNECTION_REFUSED in Chrome

`[13:34:22] - OpenSSL loaded, version: 01000201F
[13:34:22] - Version: 0.5.1 r1795, Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2
016, 15:19:22) [MSC v.1500 32 bit (Intel)], Gevent: 1.1.2
[13:34:22] - Creating FileServer....
[13:34:23] TorManager Tor controller connect error: error: [Errno 10061] [Error
10061] No connection could be made because the target machine actively refused i
t. in TorManager.py line 157 > _socket2.py line 228
[13:34:23] TorManager Starting Tor client tools/tor/tor.exe...
Jan 16 13:34:24.375 [notice] Tor v0.2.8.11 (git-31e7b47fbebe8caf) running on Win
dows 8 with Libevent 2.0.22-stable, OpenSSL 1.0.1u and Zlib 1.2.8.
Jan 16 13:34:24.375 [notice] Tor can't help you if you use it wrong! Learn how t
o be safe at https://www.torproject.org/download/download#warning
Jan 16 13:34:24.391 [notice] Read configuration file "×××\ZeroBundle\
ZeroNet\tools\tor\torrc".
Jan 16 13:34:24.391 [warn] Path for GeoIPFile (geoip\geoip) is relative and will
 resolve to ×××\ZeroBundle\ZeroNet\tools\tor\geoip\geoip. Is this wha
t you wanted?
Jan 16 13:34:24.391 [warn] Path for GeoIPv6File (geoip\geoip6) is relative and w
ill resolve to ×××\ZeroBundle\ZeroNet\tools\tor\geoip\geoip6. Is this
 what you wanted?
Jan 16 13:34:24.391 [warn] Path for DataDirectory (data) is relative and will re
solve to ×××\ZeroBundle\ZeroNet\tools\tor\data. Is this what you want
ed?
Jan 16 13:34:24.407 [notice] Opening Socks listener on 127.0.0.1:49050
Jan 16 13:34:24.407 [notice] Opening Control listener on 127.0.0.1:49051
Jan 16 13:34:24.000 [notice] Bootstrapped 0%: Starting
Jan 16 13:34:25.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Jan 16 13:34:25.000 [notice] New control connection opened from 127.0.0.1.
[13:34:25] - Creating UiServer....
Traceback (most recent call last):
  File "×××\ZeroBundle\ZeroNet\zeronet.py", line 18, in main
    main.start()
  File "×××\ZeroBundle\ZeroNet\src\main.py", line 450, in start
    actions.call(config.action, action_kwargs)
  File "×××\ZeroBundle\ZeroNet\src\main.py", line 129, in call
    func(**kwargs)
  File "plugins\Trayicon\TrayiconPlugin.py", line 65, in main
    super(ActionsPlugin, self).main()
  File "×××\ZeroBundle\ZeroNet\src\main.py", line 139, in main
    ui_server = UiServer()
  File "×××\ZeroBundle\ZeroNet\src\Ui\UiServer.py", line 61, in __ini
t__
    self.sites = SiteManager.site_manager.list()
  File "×××\ZeroBundle\ZeroNet\src\Site\SiteManager.py", line 146, in
 list
    self.load()
  File "plugins\Zeroname\SiteManagerPlugin.py", line 20, in load
    super(SiteManagerPlugin, self).load(*args, **kwargs)
  File "plugins\MergerSite\MergerSitePlugin.py", line 333, in load
    self.updateMergerSites()
  File "plugins\MergerSite\MergerSitePlugin.py", line 301, in updateMergerSites
    merged_type = site.content_manager.contents.get("content.json", {}).get("mer
ged_type")
  File "×××\ZeroBundle\ZeroNet\src\Content\ContentDbDict.py", line 10
5, in get
    return self.__getitem__(key)
  File "×××\ZeroBundle\ZeroNet\src\Content\ContentDbDict.py", line 55
, in __getitem__
    return self.loadItem(key)
  File "×××\ZeroBundle\ZeroNet\src\Content\ContentDbDict.py", line 23
, in loadItem
    content = self.site.storage.loadJson(key)
  File "×××\ZeroBundle\ZeroNet\src\Site\SiteStorage.py", line 231, in
 loadJson
    return json.load(file)
  File "×××\ZeroBundle\Python\lib\json\__init__.py", line 291, in loa
d
    **kw)
  File "×××\ZeroBundle\Python\lib\json\__init__.py", line 339, in loa
ds
    return _default_decoder.decode(s)
  File "×××\ZeroBundle\Python\lib\json\decoder.py", line 364, in deco
de
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "×××\ZeroBundle\Python\lib\json\decoder.py", line 382, in raw_
decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Press any key to continue . . . Jan 16 13:34:27.000 [notice] Bootstrapped 85%: F
inishing handshake with first hop
Jan 16 13:34:28.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Jan 16 13:34:29.000 [notice] Tor has successfully opened a circuit. Looks like c
lient functionality is working.
Jan 16 13:34:29.000 [notice] Bootstrapped 100%: Done

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "×××\ZeroBundle\Python\lib\atexit.py", line 24, in _run_exitfu
ncs
    func(*targs, **kargs)
  File "plugins\MergerSite\MergerSitePlugin.py", line 337, in save
    self.updateMergerSites()
  File "plugins\MergerSite\MergerSitePlugin.py", line 301, in updateMergerSites
    merged_type = site.content_manager.contents.get("content.json", {}).get("mer
ged_type")
  File "×××\ZeroBundle\ZeroNet\src\Content\ContentDbDict.py", line 10
5, in get
    return self.__getitem__(key)
  File "×××\ZeroBundle\ZeroNet\src\Content\ContentDbDict.py", line 55
, in __getitem__
    return self.loadItem(key)
  File "×××\ZeroBundle\ZeroNet\src\Content\ContentDbDict.py", line 23
, in loadItem
    content = self.site.storage.loadJson(key)
  File "×××\ZeroBundle\ZeroNet\src\Site\SiteStorage.py", line 231, in
 loadJson
    return json.load(file)
  File "×××\ZeroBundle\Python\lib\json\__init__.py", line 291, in loa
d
    **kw)
  File "×××\ZeroBundle\Python\lib\json\__init__.py", line 339, in loa
ds
    return _default_decoder.decode(s)
  File "×××\ZeroBundle\Python\lib\json\decoder.py", line 364, in deco
de
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "×××\ZeroBundle\Python\lib\json\decoder.py", line 382, in raw_
decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Icon thread stopped, removing icon...
Error in sys.exitfunc:
[13:37:35] - Unhandled exception
None
Traceback (most recent call last):
  File "×××\ZeroBundle\Python\lib\atexit.py", line 24, in _run_exitfu
ncs
    func(*targs, **kargs)
  File "plugins\MergerSite\MergerSitePlugin.py", line 337, in save
    self.updateMergerSites()
  File "plugins\MergerSite\MergerSitePlugin.py", line 301, in updateMergerSites
    merged_type = site.content_manager.contents.get("content.json", {}).get("mer
ged_type")
  File "×××\ZeroBundle\ZeroNet\src\Content\ContentDbDict.py", line 10
5, in get
    return self.__getitem__(key)
  File "×××\ZeroBundle\ZeroNet\src\Content\ContentDbDict.py", line 55
, in __getitem__
    return self.loadItem(key)
  File "×××\ZeroBundle\ZeroNet\src\Content\ContentDbDict.py", line 23
, in loadItem
    content = self.site.storage.loadJson(key)
  File "×××\ZeroBundle\ZeroNet\src\Site\SiteStorage.py", line 231, in
 loadJson
    return json.load(file)
  File "×××\ZeroBundle\Python\lib\json\__init__.py", line 291, in loa
d
    **kw)
  File "×××\ZeroBundle\Python\lib\json\__init__.py", line 339, in loa
ds
    return _default_decoder.decode(s)
  File "×××\ZeroBundle\Python\lib\json\decoder.py", line 364, in deco
de
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "×××\ZeroBundle\Python\lib\json\decoder.py", line 382, in raw_
decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

×××\ZeroBundle\ZeroNet>pause
Press any key to continue . . .`
