### ISSUE TITLE
content publish failed

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#535]
upon this command:
`Page.cmd("fileWrite", [inner_path, btoa(json_raw)], function(res) {
	console.log(res);
	Page.cmd("sitePublish",{"inner_path":inner_path,"sign":false}, function(res) {
		console.log(res);
		$scope.$apply(function() {
			Page.cmd("wrapperNotification", ["done", "Comment posted!", 10000]);
			$scope.comments.push(comment);
		});
	});
});`

im getting this console error - content publish failed

terminal log:
`[13:11:12] - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Site/Site.py", line 425, in publish
    inner_path, limit, len(self.peers), num_connected_peers, diffs.keys(), float(len(str(diffs))) / 1024
AttributeError: 'NoneType' object has no attribute 'keys'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Site/Site.py", line 425, in publish
    inner_path, limit, len(self.peers), num_connected_peers, diffs.keys(), float(len(str(diffs))) / 1024
AttributeError: 'NoneType' object has no attribute 'keys'
`

**Comment by HelloZeroNet** [comment]
I was unable to reproduce it, can you give me pelase more details on what kind of data you want to sign? And maybe pelase check the log/debug.log if there any any more error message around it.

**Comment by DaniellMesquito** [comment]
@HelloZeroNet, I think it is relationed with #544.
