### ISSUE TITLE
too many SQL variables

### ISSUE THREAD

**Issue by kavamaken** [HelloZeroNet/ZeroNet#568]
After upgrading my zerobundle to vertion 0.4.1, I've got an error:
Traceback (most recent call last):
  File "G:\ZeroBundle\ZeroNet\zeronet.py", line 16, in main
    main.start()
  File "G:\ZeroBundle\ZeroNet\src\main.py", line 419, in start
    actions.call(config.action, action_kwargs)
  File "G:\ZeroBundle\ZeroNet\src\main.py", line 118, in call
    func(**kwargs)
  File "plugins\Trayicon\TrayiconPlugin.py", line 62, in main
    super(ActionsPlugin, self).main()
  File "G:\ZeroBundle\ZeroNet\src\main.py", line 129, in main
    ui_server = UiServer()
  File "G:\ZeroBundle\ZeroNet\src\Ui\UiServer.py", line 61, in __init__
    self.sites = SiteManager.site_manager.list()
  File "G:\ZeroBundle\ZeroNet\src\Site\SiteManager.py", line 128, in list
    self.load()
  File "plugins\Zeroname\SiteManagerPlugin.py", line 17, in load
    super(SiteManagerPlugin, self).load()
  File "plugins\MergerSite\MergerSitePlugin.py", line 301, in load
    super(SiteManagerPlugin, self).load(*args, **kwags)
  File "G:\ZeroBundle\ZeroNet\src\Site\SiteManager.py", line 49, in load
    for row in ContentDb.content_db.execute("SELECT * FROM site WHERE ?", {"not__address": self.sites.keys()}):
  File "G:\ZeroBundle\ZeroNet\src\Db\Db.py", line 74, in execute
    return self.cur.execute(query, params)
  File "G:\ZeroBundle\ZeroNet\src\Db\DbCursor.py", line 49, in execute
    res = self.cursor.execute(query, params)
OperationalError: too many SQL variables

Quick googling showed that is SQLite limitation, at my system it limited to 999.
I've got ~1500 sites in my sites.json at the momment.

**Comment by HelloZeroNet** [comment]
Thanks for reporting it should work not: https://github.com/HelloZeroNet/ZeroNet/commit/dae5cd396931db239560a3d2e4b5ff225fbad5d4 (the first startup after the update will be slow, because it has to generate the content.db cache)
