### ISSUE TITLE
"Name or service not known" unhandled exception periodically pops up

### ISSUE THREAD

**Issue by wigy-opensource-developer** [HelloZeroNet/ZeroNet#575]
I love the 0.4.1 update, the startup time really went down. Great!

I do not remember though getting these every few seconds in 0.3.x though on my Ubuntu MATE 15.10:

```
[16:49:39] - Unhandled exception
None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/threadpool.py", line 203, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known
[16:49:43] - Unhandled exception
None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/threadpool.py", line 203, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known
[16:49:47] - Unhandled exception
None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/threadpool.py", line 203, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known
```

I do not have tor, but the port is opened.

**Comment by HelloZeroNet** [comment]
Can you please run `zeronet.py sitePublish 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D` then paste log/cmd.log file's content here?

**Comment by wigy-opensource-developer** [comment]
Probably one of the trackers cannot be resolved from my place?

```
[2016-09-07 17:18:30,346] INFO     - Creating FileServer....
[2016-09-07 17:18:30,346] DEBUG    TorManager Connecting to 127.0.0.1:9051
[2016-09-07 17:18:30,354] ERROR    TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > _socket2.py line 186
[2016-09-07 17:18:30,354] DEBUG    TorManager Tor proxy port 127.0.0.1:9050 check error: No connection
[2016-09-07 17:18:30,354] DEBUG    FileServer Binding to: *:15441, (msgpack: 0.4.2), supported crypt: ['tls-rsa']
[2016-09-07 17:18:30,354] DEBUG    Site:15GAu5..M54h Need connections: 0, Current: 0, Total: 0
[2016-09-07 17:18:30,988] DEBUG    FileServer Conn# 1 89.46.99.147 [?] > Incoming connection...
[2016-09-07 17:18:31,026] DEBUG    FileServer Conn# 2 122.173.236.39 [?] > Incoming connection...
[2016-09-07 17:18:31,030] DEBUG    FileServer Conn# 2 122.173.236.39 [v2] > Crypt in connection using: tls-rsa (server side: True)...
[2016-09-07 17:18:31,342] DEBUG    FileServer Conn# 3 112.102.78.195 [?] > Incoming connection...
[2016-09-07 17:18:31,356] INFO     FileServer Checking port 15441 using portchecker.co...
[2016-09-07 17:18:31,388] DEBUG    FileServer Conn# 3 112.102.78.195 [v2] > Crypt in connection using: tls-rsa (server side: True)...
[2016-09-07 17:18:31,431] DEBUG    FileServer Conn# 1 89.46.99.147 [v2] > Crypt in connection using: tls-rsa (server side: True)...
[2016-09-07 17:18:31,851] DEBUG    FileServer Conn# 4 192.241.144.195 [?] > Incoming connection...
[2016-09-07 17:18:31,851] DEBUG    FileServer Removing Conn# 4 192.241.144.195 [v2]...
[2016-09-07 17:18:31,943] INFO     FileServer [OK :)] Port open: Port 15441 is open.
[2016-09-07 17:18:31,944] INFO     - Gathering peers from tracker
[2016-09-07 17:18:31,945] DEBUG    FileServer Conn# 5 boot.zeronet.io [?] > Connecting...
[2016-09-07 17:18:31,965] ERROR    - Unhandled exception
None
[2016-09-07 17:18:31,970] DEBUG    Site:1HeLLo..Tf3D Http tracker http://torrent.gresille.org/announce?uploaded=0&downloaded=0&numwant=30&compact=1&event=started&peer_id=-ZN0041-2Xs10nX42opj&port=15441&info_hash=%86%D6%5B%F5%A8%DE%A3%EB%E1%96%5C%FEi%06g%25%5D%90d%7E&left=0 error: <urlopen error [Errno -2] Name or service not known>
[2016-09-07 17:18:32,019] DEBUG    Site:1HeLLo..Tf3D Found 50 peers, new: 23, total: 23
[2016-09-07 17:18:32,036] DEBUG    Site:1HeLLo..Tf3D Found 50 peers, new: 27, total: 50
```

also I did this from the command prompt:

```
$ ping torrent.gresille.org
ping: unknown host torrent.gresille.org
```

**Comment by HelloZeroNet** [comment]
Same here, so probably that tracker is down. I will find an another one instead of that, until then removing it from src/Config.py should fix it.

**Comment by wigy-opensource-developer** [comment]
The tracker is still unresolvable, but ZeroNet 0.4.1 r1523 does not spam the console, so the issue is fixed. Thanks.
