### ISSUE TITLE
user/data directories are not synchronised with peers

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#589]
on this site: http://127.0.0.1:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG
im seeing different user generated content (comments,votes, channels) on different peers.
for example on https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/ there are more comments / votes / channels (visible on register.html) then on local.
on the console im getting these errors:

```
[12:25:49] Site:1KQTZ4..FsuW data/channel.json file size does not match 494 <> 446, Hash: False
[12:25:49] Site:1KQTZ4..FsuW data/channel.json file size does not match 494 <> 446, Hash: False
[12:25:49] - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Site/Site.py", line 340, in update
    self.storage.updateBadFiles(quick_check=True)  # Quick check and mark bad files based on file size
  File "src/Site/SiteStorage.py", line 372, in updateBadFiles
    add_changed=not self.site.settings.get("own")  # Don't overwrite changed files if site owned
  File "src/Site/SiteStorage.py", line 302, in verifyFiles
    for content_inner_path, content in self.site.content_manager.contents.items():
  File "src/Content/ContentDbDict.py", line 84, in items
    val = self[key]
  File "src/Content/ContentDbDict.py", line 56, in __getitem__
    return self.loadItem(key)
  File "src/Content/ContentDbDict.py", line 29, in loadItem
    raise KeyError(key)
KeyError: u'data/users/1PW1iDGhbE8DGnWRTY369uNjVoN5FF4aay/content.json'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Site/Site.py", line 340, in update
    self.storage.updateBadFiles(quick_check=True)  # Quick check and mark bad files based on file size
  File "src/Site/SiteStorage.py", line 372, in updateBadFiles
    add_changed=not self.site.settings.get("own")  # Don't overwrite changed files if site owned
  File "src/Site/SiteStorage.py", line 302, in verifyFiles
    for content_inner_path, content in self.site.content_manager.contents.items():
  File "src/Content/ContentDbDict.py", line 84, in items
    val = self[key]
  File "src/Content/ContentDbDict.py", line 56, in __getitem__
    return self.loadItem(key)
  File "src/Content/ContentDbDict.py", line 29, in loadItem
    raise KeyError(key)
KeyError: u'data/users/1PW1iDGhbE8DGnWRTY369uNjVoN5FF4aay/content.json'
```

how can i synchronise user data through all peers e,g that all peers see the same comments / votes / channels? why is this happening? do i have to delete everything and start again with 0 content?

**Comment by HelloZeroNet** [comment]
This error was fixed earlier, please update to latest version: https://github.com/HelloZeroNet/ZeroNet/commit/ca2a30f7ae266b4ad437e5ed24986b0ce45f67db

**Comment by grez911** [comment]
@HelloZeroNet Please, close.
