### ISSUE TITLE
Error when publishing a site

### ISSUE THREAD

**Issue by AvelinoMorganti** [HelloZeroNet/ZeroNet#595]
Hello, I have a problem posting my site. Can you help me?

```
root@ubuntu-512mb:/home/ZeroBundle/ZeroNet# python zeronet.py sitePublish 1$$$$$$$$$$$$$$$$$$$$$$3
- Starting ZeroNet...
- OpenSSL loaded, version: 01000207F
- Version: 0.4.1 r1525, Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609], Gevent: 1.1.2
- Loading site...
Traceback (most recent call last):
  File "zeronet.py", line 16, in main
    main.start()
  File "src/main.py", line 420, in start
    actions.call(config.action, action_kwargs)
  File "src/main.py", line 120, in call
    func(**kwargs)
  File "src/main.py", line 303, in sitePublish
    site = SiteManager.site_manager.list()[address]
KeyError: '13$$$$$$$$$$$$$$$$$$$$$$$$$3'
root@ubuntu-512mb:/home/ZeroBundle/ZeroNet# 

```

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed in latest version: 3331e2305b02c660736c8c6970ffb561e6e85e39
