### ISSUE TITLE
Could you tell me what wrong they are? I wanna run zeronet on vps.

### ISSUE THREAD

**Issue by yangleitj** [HelloZeroNet/ZeroNet#601]
```
apt-get install python-dev
apt-get install python-setuptools
apt-get install python-pip
pip install --upgrade pip
apt-get install msgpack-python
pip install msgpack-python --upgrade
apt-get install python-gevent 
pip install gevent --upgrade
wget --no-check-certificate https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz
tar -xzvf master.tar.gz
cd ZeroNet-master
nohup python zeronet.py --ui_ip 0.0.0.0
```

```
- Starting ZeroNet...
[15:01:37] - OpenSSL loaded, version: 01000207F
[15:01:37] - Version: 0.4.1 r1533, Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609], Gevent: 1.1.0
[15:01:37] - Creating FileServer....
[15:01:37] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > _socket2.py line 228
[15:01:37] - Creating UiServer....
[15:01:37] - Removing old SSL certs...
[15:01:37] - Starting servers....
[15:01:37] Ui.UiServer --------------------------------------
[15:01:37] Ui.UiServer Web interface: http://0.0.0.0:43110/
[15:01:37] Ui.UiServer --------------------------------------
[15:01:38] FileServer Checking port 15441 using portchecker.co...
[15:01:40] FileServer [BAD :(] Port closed: Port 15441 is closed.
[15:01:40] FileServer Trying to open port using UpnpPunch...
[15:01:45] - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/File/FileServer.py", line 190, in checkSites
    self.openport()
  File "src/File/FileServer.py", line 72, in openport
    UpnpPunch.ask_to_open_port(self.port, 'ZeroNet', retries=3, protos=["TCP"])
  File "src/util/UpnpPunch.py", line 317, in ask_to_open_port
    protos=protos)
  File "src/util/UpnpPunch.py", line 296, in _communicate_with_igd
    _orchestrate_soap_request(local_ip, port, fn, desc, protos)
  File "src/util/UpnpPunch.py", line 271, in _orchestrate_soap_request
    idg_data = _collect_idg_data(ip)
  File "src/util/UpnpPunch.py", line 252, in _collect_idg_data
    idg_response = perform_m_search(ip_addr)
  File "src/util/UpnpPunch.py", line 48, in perform_m_search
    sock.bind((local_ip, 10000))
  File "<string>", line 1, in bind
error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/File/FileServer.py", line 190, in checkSites
    self.openport()
  File "src/File/FileServer.py", line 72, in openport
    UpnpPunch.ask_to_open_port(self.port, 'ZeroNet', retries=3, protos=["TCP"])
  File "src/util/UpnpPunch.py", line 317, in ask_to_open_port
    protos=protos)
  File "src/util/UpnpPunch.py", line 296, in _communicate_with_igd
    _orchestrate_soap_request(local_ip, port, fn, desc, protos)
  File "src/util/UpnpPunch.py", line 271, in _orchestrate_soap_request
    idg_data = _collect_idg_data(ip)
  File "src/util/UpnpPunch.py", line 252, in _collect_idg_data
    idg_response = perform_m_search(ip_addr)
  File "src/util/UpnpPunch.py", line 48, in perform_m_search
    sock.bind((local_ip, 10000))
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use
```

**Comment by casept** [comment]
Seems like an instance of ZN is already running on that port. Try a different port.

**Comment by HelloZeroNet** [comment]
Can you please specify your os/version you running?

**Comment by HelloZeroNet** [comment]
I was able to reproduce and fix it, please update to latest version (Rev1534) by `python update.py` and run again.
