### ISSUE TITLE
Set stack size to let zeronet run on router

### ISSUE THREAD

**Issue by cxgreat2014** [HelloZeroNet/ZeroNet#627]
RT-AC54U /opt/home/admin/ZeroNet-master]# opkg install libopenssl
Upgrading libopenssl on root from 1.0.2h-1 to 1.0.2j-1...
Downloading http://pkg.entware.net/binaries/mipsel/libopenssl_1.0.2j-1_mipselsf.ipk.
Configuring libopenssl.
[RT-AC54U /opt/home/admin/ZeroNet-master]# opkg install python-openssl
Upgrading python-openssl on root from 2.7.11-9 to 2.7.12-2...
Downloading http://pkg.entware.net/binaries/mipsel/python-openssl_2.7.12-2_mipselsf.ipk.
Configuring python-openssl.
[RT-AC54U /opt/home/admin/ZeroNet-master]# ./zeronet.py
- Starting ZeroNet...
[23:49:28] - OpenSSL load failed: File not found, falling back to slow bitcoin verify
[23:49:30] - Version: 0.4.1 r1536, Python 2.7.11 (default, Aug 15 2016, 19:04:16)
[GCC 5.3.0], Gevent: 1.1.2
[23:49:35] - Creating FileServer....
[23:49:36] TorManager Tor controller connect error: error: can't start new thread in TorManager.py line 154 > _socket2.py line 218 > _socketcommon.py line 268 > resolver_thread.py line 64 > pool.py line 300 > threadpool.py line 175 > threadpool.py line 136 > threadpool.py line 116 > threadpool.py line 145
[23:49:36] - Creating UiServer....
[23:49:36] SiteManager Deleting orphan site from content.db: 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F
Traceback (most recent call last):
  File "./zeronet.py", line 16, in main
    main.start()
  File "./src/main.py", line 420, in start
    actions.call(config.action, action_kwargs)
  File "./src/main.py", line 120, in call
    func(**kwargs)
  File "./src/main.py", line 130, in main
    ui_server = UiServer()
  File "./src/Ui/UiServer.py", line 61, in __init__
    self.sites = SiteManager.site_manager.list()
  File "./src/Site/SiteManager.py", line 130, in list
    self.load()
  File "plugins/Zeroname/SiteManagerPlugin.py", line 17, in load
    super(SiteManagerPlugin, self).load(*args, **kwargs)
  File "plugins/MergerSite/MergerSitePlugin.py", line 301, in load
    super(SiteManagerPlugin, self).load(*args, **kwags)
  File "./src/Site/SiteManager.py", line 53, in load
    ContentDb.getContentDb().deleteSite(row["address"])
  File "./src/Content/ContentDb.py", line 65, in deleteSite
    site_id = self.site_ids[site_address]
KeyError: u'1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F'
[RT-AC54U /opt/home/admin/ZeroNet-master]#

**Comment by HelloZeroNet** [comment]
please try delete data/content.db and try again

**Comment by cxgreat2014** [comment]
BusyBox v1.24.2 (2016-10-28 01:25:25 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

[RT-AC54U /opt/home/admin]# cd Z*
[RT-AC54U /opt/home/admin/ZeroNet-master]# netstat -apn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:843             0.0.0.0:*               LISTEN      7055/ikuacc
tcp        0      0 192.168.123.1:139       0.0.0.0:*               LISTEN      758/smbd
tcp        0      0 0.0.0.0:9900            0.0.0.0:*               LISTEN      7055/ikuacc
tcp        0      0 0.0.0.0:8908            0.0.0.0:*               LISTEN      7055/ikuacc
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      614/httpd
tcp        0      0 0.0.0.0:4466            0.0.0.0:*               LISTEN      7055/ikuacc
tcp        0      0 0.0.0.0:36947           0.0.0.0:*               LISTEN      622/miniupnpd
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      1775/dnsmasq
tcp        0      0 192.168.123.1:53        0.0.0.0:*               LISTEN      1775/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      618/dropbear
tcp        0      0 192.168.123.1:445       0.0.0.0:*               LISTEN      758/smbd
tcp        0      0 192.168.123.1:22        192.168.123.60:46645    ESTABLISHED 4310/dropbear
tcp        0      0 110.207.107.174:49280   222.163.202.186:80      ESTABLISHED 2226/python
tcp       32      0 110.207.107.174:61665   119.75.222.98:443       CLOSE_WAIT  2226/python
tcp       32      0 110.207.107.174:61675   119.75.222.98:443       CLOSE_WAIT  2226/python
tcp        0      0 110.207.107.174:63509   222.163.202.187:80      TIME_WAIT   -
tcp        0      0 110.207.107.174:63539   222.163.202.187:80      ESTABLISHED 2226/python
tcp       32      0 110.207.107.174:61652   119.75.222.98:443       CLOSE_WAIT  2226/python
tcp        0      0 192.168.123.1:22        192.168.123.171:57747   ESTABLISHED 7190/dropbear
tcp        0      0 110.207.107.174:16042   220.194.200.201:80      ESTABLISHED 2226/python
tcp       32      0 110.207.107.174:61661   119.75.222.98:443       CLOSE_WAIT  2226/python
tcp        0      0 110.207.107.174:49284   222.163.202.186:80      ESTABLISHED 2226/python
udp        0      0 127.0.0.1:53            0.0.0.0:*                           1775/dnsmasq
udp        0      0 192.168.123.1:53        0.0.0.0:*                           1775/dnsmasq
udp        0      0 0.0.0.0:67              0.0.0.0:*                           1775/dnsmasq
udp        0      0 192.168.123.1:58710     0.0.0.0:*                           622/miniupnpd
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           622/miniupnpd
udp        0      0 0.0.0.0:4466            0.0.0.0:*                           7055/ikuacc
udp        0      0 192.168.123.1:137       0.0.0.0:*                           755/nmbd
udp        0      0 0.0.0.0:137             0.0.0.0:*                           755/nmbd
udp        0      0 192.168.123.1:138       0.0.0.0:*                           755/nmbd
udp        0      0 0.0.0.0:138             0.0.0.0:*                           755/nmbd
udp        0      0 0.0.0.0:8909            0.0.0.0:*                           7055/ikuacc
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
unix  10     [ ]         DGRAM                       316 336/syslogd         /dev/log
unix  2      [ ACC ]     STREAM     LISTENING      37038 7190/dropbear       /tmp/dropbear-3d091c9a/auth-fabf33b8-7
unix  2      [ ACC ]     STREAM     LISTENING      21993 4310/dropbear       /tmp/dropbear-ae59ac9e/auth-2032eb2a-7
unix  2      [ ]         DGRAM                      3141 2196/crond          unix  2      [ ]         DGRAM                      2345 1775/dnsmasq        unix  2      [ ]

**Comment by cxgreat2014** [comment]
RT-AC54U /opt/home/admin/ZeroNet-master]# ./zeronet.py
- Starting ZeroNet...
[00:14:52] - OpenSSL load failed: File not found, falling back to slow bitcoin verify
[00:14:54] - Version: 0.4.1 r1536, Python 2.7.11 (default, Aug 15 2016, 19:04:16)
[GCC 5.3.0], Gevent: 1.1.2
[00:14:59] - Creating FileServer....
[00:14:59] TorManager Tor controller connect error: error: can't start new thread in TorManager.py line 154 > _socket2.py line 218 > _socketcommon.py line 268 > resolver_thread.py line 64 > pool.py line 300 > threadpool.py line 175 > threadpool.py line 136 > threadpool.py line 116 > threadpool.py line 145
[00:14:59] - Creating UiServer....
[00:14:59] SiteManager Deleting orphan site from content.db: 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F
Traceback (most recent call last):
  File "./zeronet.py", line 16, in main
    main.start()
  File "./src/main.py", line 420, in start
    actions.call(config.action, action_kwargs)
  File "./src/main.py", line 120, in call
    func(**kwargs)
  File "./src/main.py", line 130, in main
    ui_server = UiServer()
  File "./src/Ui/UiServer.py", line 61, in __init__
    self.sites = SiteManager.site_manager.list()
  File "./src/Site/SiteManager.py", line 130, in list
    self.load()
  File "plugins/Zeroname/SiteManagerPlugin.py", line 17, in load
    super(SiteManagerPlugin, self).load(*args, **kwargs)
  File "plugins/MergerSite/MergerSitePlugin.py", line 301, in load
    super(SiteManagerPlugin, self).load(*args, **kwags)
  File "./src/Site/SiteManager.py", line 53, in load
    ContentDb.getContentDb().deleteSite(row["address"])
  File "./src/Content/ContentDb.py", line 65, in deleteSite
    site_id = self.site_ids[site_address]
KeyError: u'1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F'
[RT-AC54U /opt/home/admin/ZeroNet-master]# rm data/content.db
[RT-AC54U /opt/home/admin/ZeroNet-master]# ./zeronet.py
- Starting ZeroNet...
[00:15:43] - OpenSSL load failed: File not found, falling back to slow bitcoin verify
[00:15:44] - Version: 0.4.1 r1536, Python 2.7.11 (default, Aug 15 2016, 19:04:16)
[GCC 5.3.0], Gevent: 1.1.2
[00:15:49] - Creating FileServer....
[00:15:49] TorManager Tor controller connect error: error: can't start new thread in TorManager.py line 154 > _socket2.py line 218 > _socketcommon.py line 268 > resolver_thread.py line 64 > pool.py line 300 > threadpool.py line 175 > threadpool.py line 136 > threadpool.py line 116 > threadpool.py line 145
[00:15:49] - Creating UiServer....
[00:15:49] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json
[00:15:49] - Removing old SSL certs...
[00:15:49] - Starting servers....
[00:15:50] Ui.UiServer --------------------------------------
[00:15:50] Ui.UiServer Web interface: http://127.0.0.1:43110/
[00:15:50] Ui.UiServer --------------------------------------
[00:15:50] Ui.UiServer Web interface bind error, must be running already, exiting.... can't start new thread
[00:16:09] FileServer StreamServer bind error, must be running already: 'StreamServer' object has no attribute 'handle'
[RT-AC54U /opt/home/admin/ZeroNet-master]#

**Comment by cxgreat2014** [comment]
And I don't know why it can't load openssl .

**Comment by HelloZeroNet** [comment]
That "can't start new thread" error does not looks good, no idea why.

to locate openssl we use this:
```
$ python -c "import ctypes.util; print ctypes.util.find_library('crypto')"
libcrypto.so.1.0.0
```

**Comment by cxgreat2014** [comment]
[RT-AC54U /opt/home/admin/ZeroNet-master]# python -c "import ctypes.util; print ctypes.util.find_library('crypto')"
None
[RT-AC54U /opt/home/admin/ZeroNet-master]# pip install crypto
Collecting crypto
  Downloading crypto-1.4.1-py2.py3-none-any.whl
Collecting Naked (from crypto)
  Downloading Naked-0.1.31-py2.py3-none-any.whl (590kB)
    100% |████████████████████████████████| 593kB 84kB/s
Collecting shellescape (from crypto)
  Downloading shellescape-3.4.1-py2.py3-none-any.whl
Collecting pyyaml (from Naked->crypto)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 200kB/s
Collecting requests (from Naked->crypto)
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 93kB/s
Installing collected packages: pyyaml, requests, Naked, shellescape, crypto
  Running setup.py install for pyyaml ... done
Successfully installed Naked-0.1.31 crypto-1.4.1 pyyaml-3.12 requests-2.11.1 shellescape-3.4.1
[RT-AC54U /opt/home/admin/ZeroNet-master]# python -c "import ctypes.util; print ctypes.util.find_library('crypto')"
None
[RT-AC54U /opt/home/admin/ZeroNet-master]#

😂I have no idear to slove that too，it seems that zeronet can't run in entware env。。。wait。。i think maybe it's memory use up， router only have 120Mb mem and 90mb in use，maybe that is the problem maker

**Comment by cxgreat2014** [comment]
today is too late，im in China。。tomorrow morning i will try to slove it 。。wish expand swap will work

**Comment by cxgreat2014** [comment]
It seems that expand swap not helpful...Thanks for your help

**Comment by cxgreat2014** [comment]
Me.ZeroNetwork.bit/?Post/1RedkCkVaXuVXrqCMpoXQS29bwaqsuFdL/13Z7XxTa7JuFat3KzzMWu3onwM6biLuurJ/1484814283
@Ysc3839 find out that if set threading.stack_size to 32768 that "can't start new thread" error sloved

**Comment by ysc3839** [comment]
```from thread import stack_size
stack_size(32768)```
the module threading is a wrapper for thread.

**Comment by cxgreat2014** [comment]
![image](https://cloud.githubusercontent.com/assets/15062548/22105327/69ea2802-de7e-11e6-84b2-7ca4ca7e35df.png)
zeronet runs so great on router!
