### ISSUE TITLE
KeyError on Debian GNU/Linux 8 at launch

### ISSUE THREAD

**Issue by RyDroid** [HelloZeroNet/ZeroNet#631]
Hi.

I am running on Debian GNU/Linux 8 "Jessie".
I clone the repo and installed python-msgpack and python-gevent.

I tried to start ZeroNet:

```
$ ./zeronet.py - Starting ZeroNet...
[12:36:23] - OpenSSL loaded, version: 01000114F
[12:36:23] - Version: 0.4.1 r1536, Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2], Gevent: 1.0.1
[12:36:23] - Creating FileServer....
[12:36:23] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > socket.py line 342
[12:36:23] ConnServer Error: Unsupported msgpack version: (0, 1, 10) (<0.4.0), please run `sudo apt-get install python-pip; sudo pip install msgpack-python --upgrade`
[12:36:23] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json
```

On Debian 8, the version of python-msgpack is 0.4.2, so it was strange. https://packages.debian.org/jessie/python-msgpack
I decided to give a try to the version of Debian 9 "Stretch" (`aptitude install python-msgpack/stretch`) that is 0.4.8. https://packages.debian.org/stretch/python-msgpack

I have now this error:
```
$ ./zeronet.py
- Starting ZeroNet...
[12:39:13] - OpenSSL loaded, version: 01000114F
[12:39:13] - Version: 0.4.1 r1536, Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2], Gevent: 1.0.1
[12:39:13] - Creating FileServer....
[12:39:13] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > socket.py line 342
[12:39:13] - Creating UiServer....
[12:39:13] SiteManager Deleting orphan site from content.db: 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F
Traceback (most recent call last):
  File "./zeronet.py", line 16, in main
    main.start()
  File "./src/main.py", line 420, in start
    actions.call(config.action, action_kwargs)
  File "./src/main.py", line 120, in call
    func(**kwargs)
  File "./src/main.py", line 130, in main
    ui_server = UiServer()
  File "./src/Ui/UiServer.py", line 61, in __init__
    self.sites = SiteManager.site_manager.list()
  File "./src/Site/SiteManager.py", line 130, in list
    self.load()
  File "plugins/Zeroname/SiteManagerPlugin.py", line 17, in load
    super(SiteManagerPlugin, self).load(*args, **kwargs)
  File "plugins/MergerSite/MergerSitePlugin.py", line 301, in load
    super(SiteManagerPlugin, self).load(*args, **kwags)
  File "./src/Site/SiteManager.py", line 53, in load
    ContentDb.getContentDb().deleteSite(row["address"])
  File "./src/Content/ContentDb.py", line 65, in deleteSite
    site_id = self.site_ids[site_address]
KeyError: u'1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F'
```

Apparently, it is now an error in the code of ZeroNet. I tried with the version of the commit 4ac933fa294344833231b6a4a771e47207cd0a4b (19 13:19:32 2016 -0700).

Regards.

**Comment by ysc3839** [comment]
Remove `/data/content.db` and try again.

**Comment by RyDroid** [comment]
```
$ ps -ef | grep ero
$ rm data/content.db
$ ./zeronet.py- Starting ZeroNet...
[20:54:46] - OpenSSL loaded, version: 01000114F
[20:54:46] - Version: 0.4.1 r1536, Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2], Gevent: 1.0.1
[20:54:47] - Creating FileServer....
[20:54:47] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > socket.py line 342
[20:54:47] - Creating UiServer....
[20:54:47] - Removing old SSL certs...
[20:54:47] - Starting servers....
[20:54:47] Ui.UiServer --------------------------------------
[20:54:47] Ui.UiServer Web interface: http://127.0.0.1:43110/
[20:54:47] Ui.UiServer --------------------------------------
[20:54:49] FileServer Checking port 15441 using portchecker.co...
[20:54:50] FileServer [BAD :(] Port closed: Port 15441 is closed.
[20:54:50] FileServer Trying to open port using UpnpPunch...
[20:55:05] FileServer UpnpPunch run error: UpnpError: Failed to communicate with igd using port 15441 on local machine after 3 tries. in FileServer.py line 73 > UpnpPunch.py line 319 > UpnpPunch.py line 310
[21:05:47] FileServer Internet offline
[21:07:50] FileServer Internet online
[21:07:51] FileServer Checking port 15441 using portchecker.co...
[21:07:52] FileServer [BAD :(] Port closed: Port 15441 is closed.
[21:07:52] FileServer Trying to open port using UpnpPunch...
```

5 minutes later, nothing changed. But it worked. The messages were not clear about that for me.
However, it does not launch the web browser like the bundle version. Is it normal?

**Comment by HelloZeroNet** [comment]
If you want to open the borwser, then use start.py

**Comment by RyDroid** [comment]
Ok, thanks.
