### ISSUE TITLE
can not login to zerotalk 

### ISSUE THREAD

**Issue by lostfile** [HelloZeroNet/ZeroNet#72]
the log its self is a bit long so i just copied and pasted what looked like a error
im more of a server and network guy then a coder how ever it kind of looks like a connectoin error

[2015-03-31 08:35:13,290] DEBUG    Site:1TaLk3..sPKQ data/users/1Nzmu4bpM4o8w2pUSx2p59CW5GZZB8vskU/content.json: Downloading 0 includes...
[2015-03-31 08:35:13,291] DEBUG    Site:1TaLk3..sPKQ data/users/1Nzmu4bpM4o8w2pUSx2p59CW5GZZB8vskU/content.json: Includes downloaded
[2015-03-31 08:35:13,292] DEBUG    Site:1TaLk3..sPKQ data/users/1Nzmu4bpM4o8w2pUSx2p59CW5GZZB8vskU/content.json: Downloading 1 files, changed: 0...
[2015-03-31 08:35:13,352] DEBUG    WorkerManager:1TaLk3..sPKQ 198.23.177.55:15441: Hash correct: data/users/15QJoGcY7kCCQn5NK1sgVsCj2nc3McLuNk/data.json
[2015-03-31 08:35:13,356] DEBUG    Site:1TaLk3..sPKQ Loading json file to db: data/users/15QJoGcY7kCCQn5NK1sgVsCj2nc3McLuNk/data.json
[2015-03-31 08:35:13,359] DEBUG    Db:ZeroTalk Connecting (sqlite version: 2.6.0)...
[2015-03-31 08:35:13,360] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 58, in downloader
    site.storage.write(task["inner_path"], buff)
  File "src/Site/SiteStorage.py", line 138, in write
    self.getDb().loadJson(file_path)
  File "src/Db/Db.py", line 134, in loadJson
    cur = self.getCursor()
  File "src/Db/Db.py", line 47, in getCursor
    if not self.conn: self.connect()
  File "src/Db/Db.py", line 22, in connect
    self.conn = sqlite3.connect(self.db_path)
OperationalError: unable to open database file
[2015-03-31 08:35:13,394] DEBUG    WorkerManager:1TaLk3..sPKQ 24.108.77.4:15441: Hash correct: data/users/1PTHmbBk2dhkz1ryNcgwNEkKCdpD16ypcu/data.json
[2015-03-31 08:35:13,398] DEBUG    Site:1TaLk3..sPKQ Loading json file to db: data/users/1PTHmbBk2dhkz1ryNcgwNEkKCdpD16ypcu/data.json
[2015-03-31 08:35:13,400] DEBUG    Db:ZeroTalk Connecting (sqlite version: 2.6.0)...
[2015-03-31 08:35:13,401] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 58, in downloader
    site.storage.write(task["inner_path"], buff)
  File "src/Site/SiteStorage.py", line 138, in write
    self.getDb().loadJson(file_path)
  File "src/Db/Db.py", line 134, in loadJson
    cur = self.getCursor()
  File "src/Db/Db.py", line 47, in getCursor
    if not self.conn: self.connect()
  File "src/Db/Db.py", line 22, in connect
    self.conn = sqlite3.connect(self.db_path)
OperationalError: unable to open database file
[2015-03-31 08:35:13,414] DEBUG    WorkerManager:1TaLk3..sPKQ 82.230.85.110:15441: Hash correct: data/users/14jGjAV8wrsrmKSZEARS4CnZDD9paMB72S/data.json
[2015-03-31 08:35:13,418] DEBUG    Site:1TaLk3..sPKQ Loading json file to db: data/users/14jGjAV8wrsrmKSZEARS4CnZDD9paMB72S/data.json
[2015-03-31 08:35:13,420] DEBUG    Db:ZeroTalk Connecting (sqlite version: 2.6.0)...
[2015-03-31 08:35:13,421] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 58, in downloader
    site.storage.write(task["inner_path"], buff)
  File "src/Site/SiteStorage.py", line 138, in write
    self.getDb().loadJson(file_path)
  File "src/Db/Db.py", line 134, in loadJson
    cur = self.getCursor()
  File "src/Db/Db.py", line 47, in getCursor
    if not self.conn: self.connect()
  File "src/Db/Db.py", line 22, in connect
    self.conn = sqlite3.connect(self.db_path)
OperationalError: unable to open database file
[2015-03-31 08:35:13,434] DEBUG    WorkerManager:1TaLk3..sPKQ 87.121.52.234:15441: Hash correct: data/users/18v4RV7s9kqWT2RAuBm6QktdUK3riW76tp/data.json
[2015-03-31 08:35:13,438] DEBUG    Site:1TaLk3..sPKQ Loading json file to db: data/users/18v4RV7s9kqWT2RAuBm6QktdUK3riW76tp/data.json
[2015-03-31 08:35:13,440] DEBUG    Db:ZeroTalk Connecting (sqlite version: 2.6.0)...
[2015-03-31 08:35:13,441] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 58, in downloader
    site.storage.write(task["inner_path"], buff)
  File "src/Site/SiteStorage.py", line 138, in write
    self.getDb().loadJson(file_path)
  File "src/Db/Db.py", line 134, in loadJson
    cur = self.getCursor()
  File "src/Db/Db.py", line 47, in getCursor
    if not self.conn: self.connect()
  File "src/Db/Db.py", line 22, in connect
    self.conn = sqlite3.connect(self.db_path)
OperationalError: unable to open database file
[2015-03-31 08:35:13,454] DEBUG    WorkerManager:1TaLk3..sPKQ 128.204.28.99:15441: Hash correct: data/users/1BZah2BjFd4CanYU4QjwdNbEZXbk9gVs9R/data.json
[2015-03-31 08:35:13,458] DEBUG    Site:1TaLk3..sPKQ Loading json file to db: data/users/1BZah2BjFd4CanYU4QjwdNbEZXbk9gVs9R/data.json
[2015-03-31 08:35:13,460] DEBUG    Db:ZeroTalk Connecting (sqlite version: 2.6.0)...
[2015-03-31 08:35:13,462] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 58, in downloader
    site.storage.write(task["inner_path"], buff)
  File "src/Site/SiteStorage.py", line 138, in write
    self.getDb().loadJson(file_path)
  File "src/Db/Db.py", line 134, in loadJson
    cur = self.getCursor()
  File "src/Db/Db.py", line 47, in getCursor
    if not self.conn: self.connect()
  File "src/Db/Db.py", line 22, in connect
    self.conn = sqlite3.connect(self.db_path)
OperationalError: unable to open database file
[2015-03-31 08:35:13,473] DEBUG    Conn#11 178.238.41.134 [v2] Unpacker created
[2015-03-31 08:35:13,475] DEBUG    WorkerManager:1TaLk3..sPKQ 178.238.41.134:15441: Hash correct: data/users/1N1NNMWQ8bfLSHb8YQeyLnvW6NNRYbxDGG/data.json
[2015-03-31 08:35:13,479] DEBUG    Site:1TaLk3..sPKQ Loading json file to db: data/users/1N1NNMWQ8bfLSHb8YQeyLnvW6NNRYbxDGG/data.json
[2015-03-31 08:35:13,481] DEBUG    Db:ZeroTalk Connecting (sqlite version: 2.6.0)...
[2015-03-31 08:35:13,482] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 58, in downloader
    site.storage.write(task["inner_path"], buff)
  File "src/Site/SiteStorage.py", line 138, in write
    self.getDb().loadJson(file_path)
  File "src/Db/Db.py", line 134, in loadJson
    cur = self.getCursor()
  File "src/Db/Db.py", line 47, in getCursor
    if not self.conn: self.connect()
  File "src/Db/Db.py", line 22, in connect
    self.conn = sqlite3.connect(self.db_path)
OperationalError: unable to open database file
[2015-03-31 08:35:14,018] DEBUG    WorkerManager:1TaLk3..sPKQ 78.158.149.247:15441: Hash correct: data/users/1753kNUDAzrRLdmv2XVgKUnKqQLgnesVaa/data.json
[2015-03-31 08:35:14,022] DEBUG    Site:1TaLk3..sPKQ Loading json file to db: data/users/1753kNUDAzrRLdmv2XVgKUnKqQLgnesVaa/data.json
[2015-03-31 08:35:14,024] DEBUG    Db:ZeroTalk Connecting (sqlite version: 2.6.0)...
[2015-03-31 08:35:14,026] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 58, in downloader
    site.storage.write(task["inner_path"], buff)
  File "src/Site/SiteStorage.py", line 138, in write
    self.getDb().loadJson(file_path)
  File "src/Db/Db.py", line 134, in loadJson
    cur = self.getCursor()
  File "src/Db/Db.py", line 47, in getCursor
    if not self.conn: self.connect()
  File "src/Db/Db.py", line 22, in connect
    self.conn = sqlite3.connect(self.db_path)
OperationalError: unable to open database file
[2015-03-31 08:35:18,683] DEBUG    WorkerManager:1TaLk3..sPKQ 115.205.165.189:15441: Force stopping, thread: <ErrorhookedGreenlet at 0xb4e6507cL: <bound method Worker.downloader of <Worker 1TaLk3..sPKQ 115.205.165.189:15441>>>
[2015-03-31 08:35:18,685] DEBUG    File.FileServer 115.205.165.189 Connect error: Notify: Worker stopped in ConnectionServer.py line 88 > Connection.py line 68 > socket.py line 347 > socket.py line 298 > hub.py line 341 > hub.py line 568 > hub.py line 331
[2015-03-31 08:35:18,687] DEBUG    Peer:115.205.165.189:15441 1TaLk3..sPKQ Getting connection error: Notify: Worker stopped in Peer.py line 40 > ConnectionServer.py line 94 (connection_error: 2, hash_failed: 0)
[2015-03-31 08:35:18,688] DEBUG    Peer:115.205.165.189:15441 1TaLk3..sPKQ Removing peer...Connection error: 3, Hash failed: 0
[2015-03-31 08:35:18,689] DEBUG    WorkerManager:1TaLk3..sPKQ 115.205.165.189:15441: No longer needed, returning: data/users/13NXisQxpmjSgMFSY1rsTfLcwkSX33Uji8/content.json
[2015-03-31 08:35:18,690] DEBUG    WorkerManager:1TaLk3..sPKQ Removed worker, workers: 9/10
[2015-03-31 08:35:18,691] DEBUG    WorkerManager:1TaLk3..sPKQ 82.73.156.95:15441: Force stopping, thread: <ErrorhookedGreenlet at 0xb4e6516cL: <bound method Worker.downloader of <Worker 1TaLk3..sPKQ 82.73.156.95:15441>>>
[2015-03-31 08:35:18,693] DEBUG    File.FileServer 82.73.156.95 Connect error: Notify: Worker stopped in ConnectionServer.py line 88 > Connection.py line 68 > socket.py line 347 > socket.py line 298 > hub.py line 341 > hub.py line 568 > hub.py line 331
[2015-03-31 08:35:18,695] DEBUG    Peer:82.73.156.95:15441 1TaLk3..sPKQ Getting connection error: Notify: Worker stopped in Peer.py line 40 > ConnectionServer.py line 94 (connection_error: 0, hash_failed: 0)
[2015-03-31 08:35:18,696] DEBUG    WorkerManager:1TaLk3..sPKQ 82.73.156.95:15441: No longer needed, returning: data/users/1N1NNMWQ8bfLSHb8YQeyLnvW6NNRYbxDGG/content.json
[2015-03-31 08:35:18,698] DEBUG    WorkerManager:1TaLk3..sPKQ Removed worker, workers: 8/10
[2015-03-31 08:35:18,699] DEBUG    WorkerManager:1TaLk3..sPKQ 212.92.214.123:15441: Force stopping, thread: <ErrorhookedGreenlet at 0xb4e650ccL: <bound method Worker.downloader of <Worker 1TaLk3..sPKQ 212.92.214.123:15441>>>
[2015-03-31 08:35:18,701] DEBUG    File.FileServer 212.92.214.123 Connect error: Notify: Worker stopped in ConnectionServer.py line 88 > Connection.py line 68 > socket.py line 347 > socket.py line 298 > hub.py line 341 > hub.py line 568 > hub.py line 331
[2015-03-31 08:35:18,703] DEBUG    Peer:212.92.214.123:15441 1TaLk3..sPKQ Getting connection error: Notify: Worker stopped in Peer.py line 40 > ConnectionServer.py line 94 (connection_error: 0, hash_failed: 0)
[2015-03-31 08:35:18,704] DEBUG    WorkerManager:1TaLk3..sPKQ 212.92.214.123:15441: No longer needed, returning: data/users/1DKKgeu54B2gb5m1UbK3S1kvrt1BhNRSUm/content.json
[2015-03-31 08:35:18,705] DEBUG    WorkerManager:1TaLk3..sPKQ Removed worker, workers: 7/10
[2015-03-31 08:35:26,043] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:26] "GET /ZeroNetwork.bit HTTP/1.1" 200 1815 0.055441
[2015-03-31 08:35:26,050] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:26] "GET /media/ZeroNetwork.bit/index.html HTTP/1.1" 200 2966 0.004283
[2015-03-31 08:35:26,055] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:26] "GET /uimedia/all.css HTTP/1.1" 200 15856 0.002152
[2015-03-31 08:35:26,057] DEBUG    lib.geventwebsocket.handler Closed WebSocket
[2015-03-31 08:35:26,059] DEBUG    lib.geventwebsocket.handler Failed to write closing frame -> closing socket
[2015-03-31 08:35:26,060] DEBUG    lib.geventwebsocket.handler Closed WebSocket
[2015-03-31 08:35:26,061] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:26] "GET /Websocket?wrapper_key=QAlouWb5wWt8 HTTP/1.1" 101 129 26.638448
[2015-03-31 08:35:26,086] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:26] "GET /media/ZeroNetwork.bit/css/all.css HTTP/1.1" 200 81861 0.012992
[2015-03-31 08:35:26,089] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:26] "GET /media/ZeroNetwork.bit/js/all.js HTTP/1.1" 200 124937 0.024412
[2015-03-31 08:35:26,101] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:26] "GET /uimedia/all.js HTTP/1.1" 200 122305 0.007725
[2015-03-31 08:35:26,144] DEBUG    lib.geventwebsocket.handler Initializing WebSocket
[2015-03-31 08:35:26,146] DEBUG    lib.geventwebsocket.handler Validating WebSocket request
[2015-03-31 08:35:26,147] DEBUG    lib.geventwebsocket.handler Attempting to upgrade connection
[2015-03-31 08:35:26,148] DEBUG    lib.geventwebsocket.handler WebSocket request accepted, switching protocols
[2015-03-31 08:35:26,199] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:26] "GET /media/ZeroNetwork.bit/img/loading.gif HTTP/1.1" 200 1045 0.004177
[2015-03-31 08:35:29,452] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:29] "GET /Board.ZeroNetwork.bit HTTP/1.1" 200 1820 0.056671
[2015-03-31 08:35:29,459] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:29] "GET /media/Board.ZeroNetwork.bit/index.html HTTP/1.1" 200 1435 0.004205
[2015-03-31 08:35:29,464] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:29] "GET /uimedia/all.css HTTP/1.1" 200 15856 0.002035
[2015-03-31 08:35:29,467] DEBUG    lib.geventwebsocket.handler Closed WebSocket
[2015-03-31 08:35:29,468] DEBUG    lib.geventwebsocket.handler Failed to write closing frame -> closing socket
[2015-03-31 08:35:29,469] DEBUG    lib.geventwebsocket.handler Closed WebSocket
[2015-03-31 08:35:29,471] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:29] "GET /Websocket?wrapper_key=QAlouWb5wWt8 HTTP/1.1" 101 129 3.326747
[2015-03-31 08:35:29,492] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:29] "GET /media/Board.ZeroNetwork.bit/js/all.js HTTP/1.1" 200 106954 0.018129
[2015-03-31 08:35:29,496] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:29] "GET /media/Board.ZeroNetwork.bit/css/all.css HTTP/1.1" 200 71297 0.013782
[2015-03-31 08:35:29,508] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:29] "GET /uimedia/all.js HTTP/1.1" 200 122305 0.008480
[2015-03-31 08:35:29,554] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:29] "OPTIONS /media/Board.ZeroNetwork.bit/messages.json HTTP/1.1" 200 322 0.003693
[2015-03-31 08:35:29,563] DEBUG    lib.geventwebsocket.handler Initializing WebSocket
[2015-03-31 08:35:29,564] DEBUG    lib.geventwebsocket.handler Validating WebSocket request
[2015-03-31 08:35:29,565] DEBUG    lib.geventwebsocket.handler Attempting to upgrade connection
[2015-03-31 08:35:29,566] DEBUG    lib.geventwebsocket.handler WebSocket request accepted, switching protocols
[2015-03-31 08:35:29,626] DEBUG    Ui.UiServer 192.168.1.5 - - [2015-03-31 08:35:29] "GET /media/Board.ZeroNetwork.bit/messages.json HTTP/1.1" 200 156980 0.016296
[2015-03-31 08:35:33,708] DEBUG    WorkerManager:1TaLk3..sPKQ Task taking more than 15 secs, find more peers: data/users/15QJoGcY7kCCQn5NK1sgVsCj2nc3McLuNk/data.json
[2015-03-31 08:35:33,919] DEBUG    WorkerManager:1TaLk3..sPKQ Added worker: 212.92.214.123:15441, workers: 8/10
[2015-03-31 08:35:33,920] DEBUG    WorkerManager:1TaLk3..sPKQ Added worker: 82.73.156.95:15441, workers: 9/10
[2015-03-31 08:35:33,922] DEBUG    WorkerManager:1TaLk3..sPKQ Added worker: 104.156.231.236:15441, workers: 10/10
[2015-03-31 08:35:33,928] DEBUG    Site:1TaLk3..sPKQ Found 13 peers, new: 1
[2015-03-31 08:35:33,953] DEBUG    Peer:212.92.214.123:15441 1TaLk3..sPKQ Getting connection...
[2015-03-31 08:35:33,955] DEBUG    Conn#55 212.92.214.123 [?] Connecting...
[2015-03-31 08:35:33,957] DEBUG    Peer:82.73.156.95:15441 1TaLk3..sPKQ Getting connection...
[2015-03-31 08:35:33,959] DEBUG    Conn#56 82.73.156.95 [?] Connecting...
[2015-03-31 08:35:34,056] DEBUG    WorkerManager:1TaLk3..sPKQ 104.156.231.236:15441: Hash correct: data/users/1CtKJv2gGR3tSDfkqPmSVF1WNS7meEh2L3/data.json
[2015-03-31 08:35:34,061] DEBUG    Site:1TaLk3..sPKQ Loading json file to db: data/users/1CtKJv2gGR3tSDfkqPmSVF1WNS7meEh2L3/data.json
[2015-03-31 08:35:34,063] DEBUG    Db:ZeroTalk Connecting (sqlite version: 2.6.0)...
[2015-03-31 08:35:34,064] ERROR    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "src/Worker/Worker.py", line 58, in downloader
    site.storage.write(task["inner_path"], buff)
  File "src/Site/SiteStorage.py", line 138, in write
    self.getDb().loadJson(file_path)
  File "src/Db/Db.py", line 134, in loadJson
    cur = self.getCursor()
  File "src/Db/Db.py", line 47, in getCursor
    if not self.conn: self.connect()
  File "src/Db/Db.py", line 22, in connect
    self.conn = sqlite3.connect(self.db_path)
OperationalError: unable to open database file
[2015-03-31 08:35:34,848] DEBUG    Site:1TaLk3..sPKQ Announced to 5 trackers, errors: []
[2015-03-31 08:35:48,893] DEBUG    Conn# 3 24.108.77.4  [v2] Unpacker deleted
[2015-03-31 08:35:48,894] DEBUG    Conn# 9 78.158.149.247 [v2] Unpacker deleted

**Comment by HelloZeroNet** [comment]
Thanks for reporting for some reason your python is unable to open an sqlite database. After some googling maybe specifying absolute path could help.

To find out if this is a problem I made a testcase for Db connection. To run please update your zeronet by running `python update.py` (or git pull), then `python -m src.Test.test`

The output should look like this:
```
f:\Work\ZeroNet-git\ZeroNet>python -m src.Test.test
testBitcoinSign (__main__.TestCase) ... Taken: 0.542s, ok
testBitcoinSignCompressed (__main__.TestCase) ... skipped 'Not working'
testBitcoinSignOld (__main__.TestCase) ...  Taken: 0.786s, ok
testDb (__main__.TestCase) ...  Importing db...
Creating db using f:\Work\ZeroNet-git\ZeroNet\data\test\zeronet.db... ok
Creating db using data/test/zeronet.db... ok
ok
testMediaRoute (__main__.TestCase) ... ok
testTrackers (__main__.TestCase) ... skipped 'Notyet'

----------------------------------------------------------------------
Ran 6 tests in 1.466s

OK (skipped=2)

f:\Work\ZeroNet-git\ZeroNet>
```

**Comment by lostfile** [comment]
thanks

**Comment by lostfile** [comment]
come to think about it i dont have sqlite installed but then again i dont think it needs to be

**Comment by HelloZeroNet** [comment]
In theory its comes with every python and your log says:
`[2015-03-31 08:35:13,460] DEBUG Db:ZeroTalk Connecting (sqlite version: 2.6.0)...`
So I'm not sure if thats the problem.
