### ISSUE TITLE
ImportError: No module named coros (gevent)

### ISSUE THREAD

**Issue by kseistrup** [HelloZeroNet/ZeroNet#720]
Just upgraded the `gevent` module from python2-gevent 1.1.2 to 1.2.0 and now Zeronet won't start:
```pytb
Traceback (most recent call last):
  File "zeronet.py", line 18, in main
    main.start()
  File "…/zeronet/src/main.py", line 450, in start
    actions.call(config.action, action_kwargs)
  File "…/zeronet/src/main.py", line 129, in call
    func(**kwargs)
  File "…/zeronet/src/main.py", line 134, in main
    from File import FileServer
  File "/usr/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "…/zeronet/src/File/__init__.py", line 1, in <module>
    from FileServer import FileServer
  File "/usr/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "…/zeronet/src/File/FileServer.py", line 14, in <module>
    from Connection import ConnectionServer
  File "/usr/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "…/zeronet/src/Connection/__init__.py", line 1, in <module>
    from ConnectionServer import ConnectionServer
  File "/usr/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "…/zeronet/src/Connection/ConnectionServer.py", line 15, in <module>
    from Tor import TorManager
  File "/usr/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "…/zeronet/src/Tor/__init__.py", line 1, in <module>
    from TorManager import TorManager
  File "/usr/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "…/zeronet/src/Tor/TorManager.py", line 17, in <module>
    from gevent.coros import RLock
  File "/usr/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named coros
```

**Comment by HelloZeroNet** [comment]
Thanks, fixed in Rev1791 9a1735f37dfc7f9a2f734783f38ca5c8a4e9cbc3

**Comment by sidney9111** [comment]
I dont think it was a fixup, you just remove the import code of gevent.coros?I want to know where is gevent.coros be in 2016? my project used code like this "from gevent.coros import RLock, Semaphore", I could not just remove the import code, where is Semaphore now?sorry, I am not metioning your project

**Comment by HelloZeroNet** [comment]
The fix was:
```
try: 
    from gevent.coros import RLock 
except: 
    from gevent.lock import RLock 
```
So you need
```
try: 
    from gevent.coros import RLock, Semaphore
except: 
    from gevent.lock import RLock, Semaphore
```
