### ISSUE TITLE
I cannot access Zeronet

### ISSUE THREAD

**Issue by simplefreelife** [HelloZeroNet/ZeroNet#745]
> Sorry, My english level Is Low,I use administrator privileges in the windows command console running zeronet.cmd about 30 seconds after the following results. I really need your help. Thank you very much!

Downloading https://github.com/HelloZeroNet/ZeroNet/archive/master.zip to ZeroNet directory.
Traceback (most recent call last):
  File "D:\Program Files\ZeroBundle\Python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Program Files\ZeroBundle\Python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Program Files\ZeroBundle\Python\lib\site-packages\zerobundle\run.py", line 46, in <module>
    download(url, target_dir)
  File "D:\Program Files\ZeroBundle\Python\lib\site-packages\zerobundle\run.py", line 6, in download
    file = urllib.urlopen(url)
  File "D:\Program Files\ZeroBundle\Python\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "D:\Program Files\ZeroBundle\Python\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "D:\Program Files\ZeroBundle\Python\lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "D:\Program Files\ZeroBundle\Python\lib\httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "D:\Program Files\ZeroBundle\Python\lib\httplib.py", line 850, in _send_output
    self.send(msg)
  File "D:\Program Files\ZeroBundle\Python\lib\httplib.py", line 812, in send
    self.connect()
  File "D:\Program Files\ZeroBundle\Python\lib\httplib.py", line 1208, in connect
    HTTPConnection.connect(self)
  File "D:\Program Files\ZeroBundle\Python\lib\httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "D:\Program Files\ZeroBundle\Python\lib\socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 10060]

**Comment by l5h5t7** [comment]
Try running ZeroNet as standard privileges.

**Comment by HelloZeroNet** [comment]
Looks like something is blocking the internet access of ZeroNet

**Comment by MuxZeroNet** [comment]
Windows Sockets Error Code:
```
WSAETIMEDOUT
10060
```
> **Connection timed out.**
> A connection attempt failed because the connected party did not properly respond after a period of time, or the established connection failed because the connected host has failed to respond.

ZeroNet cannot connect to GitHub. It should have decided to download updates from another mirror.

Grab a GitHub IP from here: https://asm.ca.com/en/ping.php
Or specify a SOCKS proxy to use: https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Config.py#L157

**Comment by HelloZeroNet** [comment]
Looks like you using outdated zerobundle, please download, unpack this one and try again: https://github.com/HelloZeroNet/ZeroBundle/raw/master/dist/ZeroBundle-win.zip

**Comment by simplefreelife** [comment]
> Thanks HelloZeroNet reply. this zipped file solves the problem i'm having with the theme.

Now, zeronet.cmd successfully downloaded ZeroNet folder. But not as smooth as imagined.
by default, zeronet.cmd generates the ZeroNet floder in the current directory. which causers the following two commands to fail.
https://github.com/HelloZeroNet/ZeroBundle/blob/master/zeronet.cmd#L12 
https://github.com/HelloZeroNet/ZeroBundle/blob/master/zeronet.cmd#L14
of course, this problem may only exist for me, my method is to use text to open zeronet.cmd and modify line 12 and 14.

> line 12:		..\Python\python.exe ..\ZeroNet\zeronet\start.py
> line14:		..\Python\python.exe ..\ZeroNet\zeronet\zeronet.py %*

OK, My Chrome browser successfully pops up the hello zeronet page.
It seems to be going well now, and thanks again to the author and the person who helped me.

**Comment by border0464111** [comment]
Looks like problem happily solved, Closing ?
