### ISSUE TITLE
UnboundLocalError: local variable 'main' referenced before assignment

### ISSUE THREAD

**Issue by goldenratio** [HelloZeroNet/ZeroNet#85]
I am trying to run ZeroNet on Raspberry Pi and I am getting this error! Not sure what to do.

Python version 2.7.3

```
pi@raspberrypi ~/zeronet/ZeroNet $ python zeronet.py
 - Starting ZeroNet...
Traceback (most recent call last):
  File "zeronet.py", line 8, in main
    import main
  File "src/main.py", line 35, in <module>
    from Debug import DebugHook
  File "src/Debug/DebugHook.py", line 1, in <module>
    import gevent, sys, logging
ImportError: No module named gevent
-- Error happened, press enter to close --
Traceback (most recent call last):
  File "zeronet.py", line 40, in <module>
    main()
  File "zeronet.py", line 28, in main
    if main.update_after_shutdown: # Updater
UnboundLocalError: local variable 'main' referenced before assignment

```

**Comment by HelloZeroNet** [comment]
`ImportError: No module named gevent` means you need to install gevent first.

you can do it using `pip install gevent msgpack-python` (if no pip command found try to find it in your package manager or download & run https://bootstrap.pypa.io/get-pip.py)

**Comment by goldenratio** [comment]
Thanks, kinda works..
But I have some other issue.. I look into it.

```
pi@raspberrypi ~/zeronet/ZeroNet $ python zeronet.py
 - Starting ZeroNet...
[21:48:21] - Version: 0.2.9, Python 2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3], Gevent: 1.0.1
[21:48:22] - Creating UiServer....
[21:48:22] - Creating FileServer....
[21:48:22] - Starting servers....
[21:48:22] Ui.UiServer --------------------------------------
[21:48:22] Ui.UiServer Web interface: http://127.0.0.1:43110/
[21:48:22] Ui.UiServer --------------------------------------
[21:48:23] FileServer Checking port 15441 using canyouseeme.org...
[21:48:31] FileServer [BAD :(] Port closed: Error: I could not see your service on 176.46.27.195 on port (15441) Reason: Connection timed out
[21:48:31] FileServer Trying to open port using UpnpPunch...
[21:48:32] FileServer Checking port 15441 using canyouseeme.org...
[21:48:40] FileServer [BAD :(] Port closed: Error: I could not see your service on 176.46.27.195 on port (15441) Reason: Connection timed out
[21:48:40] FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress
```

**Comment by goldenratio** [comment]
Thanks, kinda works..
Have some other issue now,
```
 - Starting ZeroNet...
[21:48:21] - Version: 0.2.9, Python 2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3], Gevent: 1.0.1
[21:48:22] - Creating UiServer....
[21:48:22] - Creating FileServer....
[21:48:22] - Starting servers....
[21:48:22] Ui.UiServer --------------------------------------
[21:48:22] Ui.UiServer Web interface: http://127.0.0.1:43110/
[21:48:22] Ui.UiServer --------------------------------------
[21:48:23] FileServer Checking port 15441 using canyouseeme.org...
...
...
(15441) Reason: Connection timed out
[21:48:40] FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress

```

**Comment by HelloZeroNet** [comment]
If your router doesn't support upnp then you have forward the port 15441 to your raspberry IP address. But its also works fine if you cant do that.

If you want to access the the web interface from other ip address then you have to start it with `zeronet.py --ui_ip *` after that you can access it using http://raspberryip:15441

**Comment by goldenratio** [comment]
Great! it works!

Btw, a noob question - what is the use upnp? :)

http://i.imgur.com/wQXBZcW.png

**Comment by HelloZeroNet** [comment]
Upnp allows to communicate to your router and automatically forwards required the port to your computer.
