### ISSUE TITLE
AnnounceZero error when publishing site

### ISSUE THREAD

**Issue by gniezen** [HelloZeroNet/ZeroNet#853]
I've been struggling all evening to view my site from another computer. I first thought port forwarding wasn't set up correctly, but after looking at debug.log I found this:

```
[22:21:02] - Unhandled exception
Traceback (most recent call last):
  File "gevent/greenlet.pyo", line 536, in run
  File "plugins/AnnounceZero/AnnounceZeroPlugin.py", line 106, in announceTracker
  File "/Users/gerrit/Downloads/ZeroNet-mac-dist/ZeroNet.app/Contents/Resources/core/src/Tor/TorManager.py", line 261, in getPrivatekey
KeyError: None
Traceback (most recent call last):
  File "gevent/greenlet.pyo", line 536, in run
  File "plugins/AnnounceZero/AnnounceZeroPlugin.py", line 106, in announceTracker
    sign = CryptRsa.sign(res["onion_sign_this"], self.connection_server.tor_manager.getPrivatekey(onion))
  File "/Users/gerrit/Downloads/ZeroNet-mac-dist/ZeroNet.app/Contents/Resources/core/src/Tor/TorManager.py", line 261, in getPrivatekey
    return self.privatekeys[address]
KeyError: None
```

I don't have Tor set up and I'm using ZeroNet.app on Mac - is this what's causing my problem or should I look further?

**Comment by gniezen** [comment]
Hmm, I installed tor using `brew install tor`, to hopefully updated any libraries being used. Restarted ZeroNet a couple of times (including enabling/disabling Tor), and looks like it's finally working! Not entirely sure why though. Last thing I did was to add

`export PATH="/usr/local/opt/openssl/bin:$PATH`

which I got from the post-install instructions in `brew`. Maybe it was just not using the right crypto library? From `brew` instructions:

    Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.
