### ISSUE TITLE
clone ZeroBlog ,publish error

### ISSUE THREAD

**Issue by dudw** [HelloZeroNet/ZeroNet#866]
[10:57:13] Site:18Xzgf..r8PA File content.json signed!
[10:57:13] Site:18Xzgf..r8PA Publishing content.json to 5/0 peers (connected: 0)
 diffs: [u'data/data.json'] (0.16k)...
[10:57:13] - Unhandled exception
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 593, in
 _notify_links
    link(self)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 45, in
__call__
    g.switch(source)
  File "D:\ZeroBundle\ZeroNet\src\Ui\UiWebsocket.py", line 380, in <lambda>
    thread.link(lambda thread: self.cbSitePublish(to, self.site, thread, notific
ation, callback=notification))
  File "D:\ZeroBundle\ZeroNet\src\Ui\UiWebsocket.py", line 427, in cbSitePublish

    {_[on your router to make your site accessible for everyone.]}""").format(co
nfig.fileserver_port)
  File "D:\ZeroBundle\ZeroNet\src\Translate\Translate.py", line 63, in __call__
    return self.format(s, kwargs, nested=nested)
  File "D:\ZeroBundle\ZeroNet\src\Translate\Translate.py", line 52, in format
    return s.format(**kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-19: ordi
nal not in range(128)
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 593, in
 _notify_links
    link(self)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 45, in
__call__
    g.switch(source)
  File "D:\ZeroBundle\ZeroNet\src\Ui\UiWebsocket.py", line 380, in <lambda>
    thread.link(lambda thread: self.cbSitePublish(to, self.site, thread, notific
ation, callback=notification))
  File "D:\ZeroBundle\ZeroNet\src\Ui\UiWebsocket.py", line 427, in cbSitePublish

    {_[on your router to make your site accessible for everyone.]}""").format(co
nfig.fileserver_port)
  File "D:\ZeroBundle\ZeroNet\src\Translate\Translate.py", line 63, in __call__
    return self.format(s, kwargs, nested=nested)
  File "D:\ZeroBundle\ZeroNet\src\Translate\Translate.py", line 52, in format
    return s.format(**kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-19: ordi
nal not in range(128)
[10:57:53] Site:18Xzgf..r8PA Publishing content.json to 5/0 peers (connected: 0)
 diffs: [] (0.00k)...
[10:57:53] - Unhandled exception
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 593, in
 _notify_links
    link(self)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 45, in
__call__
    g.switch(source)
  File "D:\ZeroBundle\ZeroNet\src\Ui\UiWebsocket.py", line 388, in <lambda>
    thread.link(lambda thread: self.cbSitePublish(to, self.site, thread, notific
ation, callback=False))
  File "D:\ZeroBundle\ZeroNet\src\Ui\UiWebsocket.py", line 427, in cbSitePublish

    {_[on your router to make your site accessible for everyone.]}""").format(co
nfig.fileserver_port)
  File "D:\ZeroBundle\ZeroNet\src\Translate\Translate.py", line 63, in __call__
    return self.format(s, kwargs, nested=nested)
  File "D:\ZeroBundle\ZeroNet\src\Translate\Translate.py", line 52, in format
    return s.format(**kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-19: ordi
nal not in range(128)
Traceback (most recent call last):
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 593, in
 _notify_links
    link(self)
  File "D:\ZeroBundle\Python\lib\site-packages\gevent\greenlet.py", line 45, in
__call__
    g.switch(source)
  File "D:\ZeroBundle\ZeroNet\src\Ui\UiWebsocket.py", line 388, in <lambda>
    thread.link(lambda thread: self.cbSitePublish(to, self.site, thread, notific
ation, callback=False))
  File "D:\ZeroBundle\ZeroNet\src\Ui\UiWebsocket.py", line 427, in cbSitePublish

    {_[on your router to make your site accessible for everyone.]}""").format(co
nfig.fileserver_port)
  File "D:\ZeroBundle\ZeroNet\src\Translate\Translate.py", line 63, in __call__
    return self.format(s, kwargs, nested=nested)
  File "D:\ZeroBundle\ZeroNet\src\Translate\Translate.py", line 52, in format
    return s.format(**kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-19: ordi
nal not in range(128)

**Comment by HelloZeroNet** [comment]
Thanks, fixed: d7ba9f6924f23266411edfda1e236f88ea318347
