### ISSUE TITLE
Debian 8 'PROTOCOL_SSLv3' is not defined

### ISSUE THREAD

**Issue by iHedgehog** [HelloZeroNet/ZeroNet#95]
Starting ZeroNet...
Traceback (most recent call last):
  File "zeronet.py", line 9, in main
    import main
  File "src/main.py", line 41, in <module>
    from gevent import monkey; monkey.patch_all(thread=False, ssl=False) # Make time, socket gevent compatible. Not thread: pyfilesystem and system tray icon not compatible, Not ssl: broken in 2.7.9
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 185, in patch_all
    patch_socket(dns=dns, aggressive=aggressive)
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 124, in patch_socket
    from gevent import socket
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/usr/local/lib/python2.7/dist-packages/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined
-- Error happened, press enter to close --

**Comment by HelloZeroNet** [comment]
I throught "ssl=False" fixes this problem, but looks like not :(

Just installed Debian Jessie and this fixes the problem (installing from package instead of source):
```
pip uninstall gevent
apt-get install python-gevent
```

**Comment by iHedgehog** [comment]
It works, thank you.
