### ISSUE TITLE
[.tar.gz] Ui.UiServer Error opening archive file: invalid header

### ISSUE THREAD

**Issue by mkg20001** [HelloZeroNet/ZeroNet#951]
ZeroNet can't open some .tar.gz files on git.mkg20001.bit
Example: http://localhost:43110/git.mkg20001.bit/git/hellozeronet/ZeroNet.tar.gz/ZeroNet/log.html
But the archive file is valid (screenshot below)
![screenshot](https://cloud.githubusercontent.com/assets/7735145/26453702/ee1bdf0a-4164-11e7-9376-9d8dad141737.png)

Log:
```
[16:12:43] Ui.UiServer 127.0.0.1 - - [2017-05-25 16:12:43] "GET /Websocket?wrapper_key=eeeeeeeeeeeeeeeeeeeeeeeeee8e09aeb4f7258e846da692c593ee542d96257c HTTP/1.1" 101 129 90.779358
[16:12:43] Ui.UiServer 127.0.0.1 - - [2017-05-25 16:12:43] "GET http://git.mkg20001.bit/git/hellozeronet/ZeroNet.tar.gz/ZeroNet/log.html HTTP/1.1" 200 3259 0.000991
[16:12:43] Ui.UiServer 127.0.0.1 - - [2017-05-25 16:12:43] "GET http://git.mkg20001.bit/uimedia/all.css?rev=2089 HTTP/1.1" 200 33051 0.001677
[16:12:43] Ui.UiServer Patched /uimedia/all.js (175692 bytes) in 0.007s
[16:12:43] Ui.UiServer 127.0.0.1 - - [2017-05-25 16:12:43] "GET http://git.mkg20001.bit/uimedia/all.js?rev=2089&lang=de HTTP/1.1" 200 176022 0.007410
[16:12:43] Ui.UiServer Error opening archive file: invalid header
[16:12:43] Ui.UiServer 127.0.0.1 - - [2017-05-25 16:12:43] "GET http://git.mkg20001.bit/git/hellozeronet/ZeroNet.tar.gz/ZeroNet/log.html?wrapper_nonce=eeaf6de2a9de03e50a11a9869de854639d11c753a72847820ecc85ce6997e825 HTTP/1.1" 404 1296 0.007621
```

**Comment by HelloZeroNet** [comment]
For some reasons it's not compatible with python's tarfile module, but after extracting it and repacking works for me.
What application you used for packing?

```
$ python -c "import tarfile; tarfile.open('ZeroNet.tar.gz').list()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
$ tar xvpfz ZeroNet.tar.gz
...
tar: ZeroNet/atom.xml: implausibly old time stamp 1970-01-01 00:00:00 
$ tar -zcvf ZeroNet-new.tar.gz ZeroNet
$ python -c "import tarfile; tarfile.open('ZeroNet-new.tar.gz').list()"   
-rwxrwxrwx root/root       1886 2017-05-25 17:33:52 ZeroNet/refs.html
...

**Comment by mkg20001** [comment]
tar on ubuntu 16.10.

**Comment by mkg20001** [comment]
If it matters: I am resetting the timestamp on every file.
https://github.com/mkg20001/mkgs-github-mirror/blob/30311cf0be213ca3cfbc0dccc526d912230fcf0f/host-zeronet.sh#L254
But I think I should change that to 2000-01-01

**Comment by mkg20001** [comment]
I've found this  https://groups.google.com/forum/#!topic/mailing.freebsd.current/gmNTaIJ2tEY
Maybe it is related to libarchive and python's tarfile is using an old version of it?

**Comment by mkg20001** [comment]
Did you fix it?
It started working but I don't know if it was because of the time stamp or another bug

**Comment by HelloZeroNet** [comment]
I haven't modified anything, probably it was related to the invalid timestamp
