### ISSUE TITLE
I get an "Unhandled exception" when I start zeronet in a VM (Ubuntu Server v16.10)  

### ISSUE THREAD

**Issue by Vertux** [HelloZeroNet/ZeroNet#953]
If I try to run the current zeronet version in a VM with Ubuntu v16.10 I get this error:

```
python zeronet.py --ui_ip "*" --ui_password ****deleted****
- Starting ZeroNet...
[10:50:33] - OpenSSL loaded, version: 01000207F
[10:50:33] - Version: 0.5.5 r2089, Python 2.7.12+ (default, Sep 17 2016, 12:08:02)
[GCC 6.2.0 20160914], Gevent: 1.1.1
[10:50:33] - Creating FileServer....
[10:50:33] TorManager Connecting to Tor Controller 127.0.0.1:9051
[10:50:33] TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 165 > _socket2.py line 228
[10:50:33] TorManager Starting self-bundled Tor, due to Tor proxy port 127.0.0.1:9050 check error: No connection
[10:50:33] - Creating UiServer....
[10:50:33] - Removing old SSL certs...
[10:50:33] - Starting servers....
[10:50:33] Ui.UiServer --------------------------------------
[10:50:33] Ui.UiServer Web interface: http://*:43110/
[10:50:33] Ui.UiServer --------------------------------------
[10:50:35] FileServer Checking port 15441 using portchecker.co...
[10:50:36] FileServer [BAD :(] Port closed: Port 15441 is closed.
[10:50:36] FileServer Trying to open port using UpnpPunch...
[10:50:36] - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/zero/zeronet/src/File/FileServer.py", line 193, in checkSites
    self.openport()
  File "/home/zero/zeronet/src/File/FileServer.py", line 74, in openport
    UpnpPunch.ask_to_open_port(self.port, 'ZeroNet', retries=3, protos=["TCP"])
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 325, in ask_to_open_port
    protos=protos)
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 304, in _communicate_with_igd
    _orchestrate_soap_request(local_ip, port, fn, desc, protos)
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 279, in _orchestrate_soap_request
    idg_data = _collect_idg_data(ip)
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 263, in _collect_idg_data
    _retrieve_igd_profile(idg_data['location']))
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 86, in _retrieve_igd_profile
    return urllib2.urlopen(url.geturl(), timeout=5).read().decode('utf-8')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/zero/zeronet/src/File/FileServer.py", line 193, in checkSites
    self.openport()
  File "/home/zero/zeronet/src/File/FileServer.py", line 74, in openport
    UpnpPunch.ask_to_open_port(self.port, 'ZeroNet', retries=3, protos=["TCP"])
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 325, in ask_to_open_port
    protos=protos)
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 304, in _communicate_with_igd
    _orchestrate_soap_request(local_ip, port, fn, desc, protos)
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 279, in _orchestrate_soap_request
    idg_data = _collect_idg_data(ip)
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 263, in _collect_idg_data
    _retrieve_igd_profile(idg_data['location']))
  File "/home/zero/zeronet/src/util/UpnpPunch.py", line 86, in _retrieve_igd_profile
    return urllib2.urlopen(url.geturl(), timeout=5).read().decode('utf-8')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in Rev2091
